// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

/// Which platforms provide each operation the seam exposes.
///
/// Derived from which header declares it. An operation in both is portable; an
/// operation in one is that platform's alone, and the backend that lacks it
/// says so rather than pretending.
const platformSupport = <String, ({bool native, bool web})>{
  'addCustomOpsLibrary': (native: true, web: false),
  'addFreeDimensionOverride': (native: true, web: true),
  'addRunConfigEntry': (native: true, web: true),
  'addSessionConfigEntry': (native: true, web: true),
  'appendExecutionProvider': (native: true, web: true),
  'availableProviders': (native: true, web: true),
  'bindInput': (native: true, web: true),
  'bindOutput': (native: true, web: true),
  'clearBoundInputs': (native: true, web: false),
  'clearBoundOutputs': (native: true, web: true),
  'copyParametersFromBuffer': (native: true, web: true),
  'createBinding': (native: true, web: true),
  'createRunOptions': (native: true, web: true),
  'createSession': (native: true, web: true),
  'createSessionAsync': (native: true, web: true),
  'createSessionOptions': (native: true, web: true),
  'createStringTensor': (native: true, web: true),
  'createTensor': (native: true, web: true),
  'enableProfiling': (native: true, web: false),
  'endProfiling': (native: true, web: true),
  'free': (native: true, web: true),
  'init': (native: true, web: true),
  'initialize': (native: true, web: true),
  'inputOutputCount': (native: true, web: true),
  'inputOutputMetadata': (native: true, web: true),
  'lastError': (native: false, web: true),
  'loadCheckpoint': (native: true, web: true),
  'registerProviderLibrary': (native: true, web: false),
  'releaseBinding': (native: true, web: true),
  'releaseCheckpoint': (native: true, web: true),
  'releaseRunOptions': (native: true, web: true),
  'releaseSession': (native: true, web: true),
  'releaseSessionOptions': (native: true, web: true),
  'releaseTensor': (native: true, web: true),
  'run': (native: true, web: true),
  'runAsync': (native: true, web: true),
  'runWithBinding': (native: true, web: true),
  'runtimeVersion': (native: true, web: true),
  'setCpuMemoryArena': (native: true, web: true),
  'setDeterministicCompute': (native: true, web: true),
  'setExecutionMode': (native: true, web: true),
  'setInterOpNumThreads': (native: true, web: false),
  'setIntraOpNumThreads': (native: true, web: false),
  'setLogId': (native: true, web: true),
  'setLogLevel': (native: true, web: true),
  'setMemoryPattern': (native: true, web: true),
  'setOptimizationLevel': (native: true, web: true),
  'setOptimizedModelPath': (native: true, web: false),
  'stringTensorData': (native: true, web: true),
  'tensorData': (native: true, web: true),
  'trainStep': (native: true, web: true),
  'trainingModelInputCount': (native: true, web: true),
  'trainingModelInputName': (native: true, web: true),
  'unregisterProviderLibrary': (native: true, web: false),
  'webGpuDevice': (native: false, web: true),
};

/// What the Asyncify backend refuses on top of the plain one.
///
/// There are two WebAssembly backends. The plain build cannot suspend, so
/// every call returns a result. The Asyncify build can, and hands back a
/// promise a synchronous signature has nowhere to put, so the calls that
/// suspend are refused there and only there.
///
/// [platformSupport] has one flag for "web" and cannot express this, which is
/// why it is listed separately rather than folded in: the WebGPU and WebNN
/// builds are Asyncify, so this is what an accelerated page actually gets.
const asyncifyRefuses = <String>[
  'bindInput',
  'runWithBinding',
];
