// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

/// Which platforms provide each operation the seam exposes.
///
/// Derived from which header declares it. An operation in both is portable; an
/// operation in one is that platform's alone, and the backend that lacks it
/// says so rather than pretending.
const platformSupport = <String, ({bool native, bool web})>{
  'initialize': (native: true, web: true),
  'runtimeVersion': (native: true, web: true),
  'lastError': (native: false, web: true),
  'createSession': (native: true, web: true),
  'inputOutputCount': (native: true, web: true),
  'inputOutputMetadata': (native: true, web: true),
  'endProfiling': (native: true, web: true),
  'createTensor': (native: true, web: true),
  'tensorData': (native: true, web: true),
  'releaseTensor': (native: true, web: true),
  'createStringTensor': (native: true, web: false),
  'stringTensorData': (native: true, web: false),
  'free': (native: true, web: true),
  'createBinding': (native: true, web: true),
  'releaseBinding': (native: true, web: true),
  'clearBoundInputs': (native: true, web: false),
  'registerProviderLibrary': (native: true, web: false),
  'unregisterProviderLibrary': (native: true, web: false),
  'addCustomOpsLibrary': (native: true, web: false),
  'availableProviders': (native: true, web: true),
  'loadCheckpoint': (native: true, web: true),
  'releaseCheckpoint': (native: true, web: true),
  'trainStep': (native: true, web: true),
  'copyParametersFromBuffer': (native: true, web: true),
  'trainingModelInputCount': (native: true, web: true),
  'trainingModelInputName': (native: true, web: true),
  'webGpuDevice': (native: false, web: true),
};
