/// Produces the generated wrapper files, without writing anything.
///
/// Kept separate from the command so a test can re-run the generator and
/// compare against what is checked in, which is what makes the committed output
/// verifiable rather than merely plausible.
library;

import 'dart:io';

import 'package:dart_style/dart_style.dart';
import 'package:pub_semver/pub_semver.dart';

import 'c_api.dart';
import 'emit.dart';
import 'ffigen_api.dart';
import 'types.dart';

/// The generator's output: files to write, and what it could not handle.
final class Generated {
  const Generated({
    required this.files,
    required this.skipped,
    required this.wrappers,
  });

  /// File name to contents, relative to the output directory.
  final Map<String, String> files;

  /// One line per function left out, with the type that defeated it.
  final List<String> skipped;

  /// How many functions were wrapped.
  final int wrappers;
}

/// Formats to the same style as the rest of the package, so what the generator
/// writes needs no follow-up pass and can be compared byte for byte.
final _formatter = DartFormatter(languageVersion: Version(3, 6, 0));

/// Generates wrappers for every API struct declared in [header].
Generated generate({required File header, required File bindings}) {
  final apis = parseApis(header.readAsStringSync());
  final signatures = readApiSignatures(bindings);

  // Keyed by (struct, group), because a wrapper is an extension on the struct
  // that declares it and two structs can declare the same name.
  final byFile = <(String, String), List<String>>{};
  final skipped = <String>[];

  for (final api in apis.entries) {
    final members = signatures[api.key];
    if (members == null) continue;

    for (final function in api.value) {
      final group = groupOf(function.name);
      final name = '${api.key}.${function.name}';
      final signature = members[function.name];
      if (signature == null) {
        skipped.add('$name: not in the ffigen bindings');
        continue;
      }

      final code = emit(function, signature);
      if (code == null) {
        skipped.add('$name: ${unmappedReasons(function).join(', ')}');
        continue;
      }
      (byFile[(api.key, group)] ??= []).add(code);
    }
  }

  final names = [
    for (final key in byFile.keys) '${fileName(key.$1, key.$2)}.g.dart',
  ]..sort();

  return Generated(
    files: {
      for (final entry in byFile.entries)
        '${fileName(entry.key.$1, entry.key.$2)}.g.dart':
            _formatter.format(_source(entry.key.$1, entry.key.$2, entry.value)),
      'api.g.dart': _formatter.format(_barrel(names)),
      'unmapped.txt': _unmapped(skipped),
    },
    skipped: skipped,
    wrappers: byFile.values.fold(0, (n, methods) => n + methods.length),
  );
}

/// `OrtApi` calls keep the plain group name; the sibling tables are prefixed.
String fileName(String struct, String group) =>
    struct == 'OrtApi' ? group : '${_snake(struct)}_$group';

String _snake(String name) => name
    .replaceAllMapped(RegExp(r'(?<=[a-z0-9])([A-Z])'), (m) => '_${m[1]}')
    .toLowerCase();

String _capital(String name) => name[0].toUpperCase() + name.substring(1);

/// Re-exports every wrapper file, so adding a group does not mean remembering
/// to export it.
String _barrel(List<String> files) => '''
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

/// Dart wrappers over the ONNX Runtime C API.
library;

${files.map((f) => "export '$f';").join('\n')}
''';

String _unmapped(List<String> skipped) =>
    'Functions the generator does not handle.\n'
    'Each needs a rule in tool/src/types.dart, or a wrapper written by hand\n'
    'in lib/src/bindings/api/manual.dart.\n\n'
    '${([...skipped]..sort()).join('\n')}\n';

String _source(String struct, String group, List<String> methods) => '''
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// ${_capital(group)} calls on `$struct`.
extension $struct${_capital(group)}Api on $struct {
${methods.join('\n')}}
''';
