// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Binding calls on `OrtApi`.
extension OrtApiBindingApi on OrtApi {
  /// `CreateIoBinding`
  Pointer<OrtIoBinding> createIoBinding(Pointer<OrtSession> session) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtIoBinding>>();
        checkOrtStatus(this.CreateIoBinding.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtSession>,
                Pointer<Pointer<OrtIoBinding>>)>()(session, out0));
        return out0.value;
      });

  /// `BindInput`
  void bindInput(Pointer<OrtIoBinding> bindingPtr, String name,
          Pointer<OrtValue> valPtr) =>
      withArena((arena) {
        checkOrtStatus(this.BindInput.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtIoBinding>, Pointer<Char>, Pointer<OrtValue>)>()(
            bindingPtr, name.toNativeUtf8(allocator: arena).cast(), valPtr));
      });

  /// `BindOutput`
  void bindOutput(Pointer<OrtIoBinding> bindingPtr, String name,
          Pointer<OrtValue> valPtr) =>
      withArena((arena) {
        checkOrtStatus(this.BindOutput.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtIoBinding>, Pointer<Char>, Pointer<OrtValue>)>()(
            bindingPtr, name.toNativeUtf8(allocator: arena).cast(), valPtr));
      });

  /// `BindOutputToDevice`
  void bindOutputToDevice(Pointer<OrtIoBinding> bindingPtr, String name,
          Pointer<OrtMemoryInfo> memInfoPtr) =>
      withArena((arena) {
        checkOrtStatus(this.BindOutputToDevice.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtIoBinding>,
                    Pointer<Char>, Pointer<OrtMemoryInfo>)>()(bindingPtr,
            name.toNativeUtf8(allocator: arena).cast(), memInfoPtr));
      });

  /// `SynchronizeBoundInputs`
  void synchronizeBoundInputs(Pointer<OrtIoBinding> bindingPtr) =>
      checkOrtStatus(this
              .SynchronizeBoundInputs
              .asFunction<Pointer<OrtStatus> Function(Pointer<OrtIoBinding>)>()(
          bindingPtr));

  /// `SynchronizeBoundOutputs`
  void synchronizeBoundOutputs(Pointer<OrtIoBinding> bindingPtr) =>
      checkOrtStatus(this
              .SynchronizeBoundOutputs
              .asFunction<Pointer<OrtStatus> Function(Pointer<OrtIoBinding>)>()(
          bindingPtr));

  /// `ClearBoundInputs`
  void clearBoundInputs(Pointer<OrtIoBinding> bindingPtr) => this
      .ClearBoundInputs
      .asFunction<void Function(Pointer<OrtIoBinding>)>()(bindingPtr);

  /// `ClearBoundOutputs`
  void clearBoundOutputs(Pointer<OrtIoBinding> bindingPtr) => this
      .ClearBoundOutputs
      .asFunction<void Function(Pointer<OrtIoBinding>)>()(bindingPtr);

  /// `ReleaseIoBinding`
  void releaseIoBinding(Pointer<OrtIoBinding> input) => this
      .ReleaseIoBinding
      .asFunction<void Function(Pointer<OrtIoBinding>)>()(input);
}
