// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Memory calls on `OrtApi`.
extension OrtApiMemoryApi on OrtApi {
  /// `CreateMemoryInfo`
  Pointer<OrtMemoryInfo> createMemoryInfo(
          String name, int type, int id, int memType) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtMemoryInfo>>();
        checkOrtStatus(this.CreateMemoryInfo.asFunction<
                Pointer<OrtStatus> Function(Pointer<Char>, int, int, int,
                    Pointer<Pointer<OrtMemoryInfo>>)>()(
            name.toNativeUtf8(allocator: arena).cast(),
            type,
            id,
            memType,
            out0));
        return out0.value;
      });

  /// `CreateCpuMemoryInfo`
  Pointer<OrtMemoryInfo> createCpuMemoryInfo(int type, int memType) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtMemoryInfo>>();
        checkOrtStatus(this.CreateCpuMemoryInfo.asFunction<
            Pointer<OrtStatus> Function(int, int,
                Pointer<Pointer<OrtMemoryInfo>>)>()(type, memType, out0));
        return out0.value;
      });

  /// `CompareMemoryInfo`
  int compareMemoryInfo(
          Pointer<OrtMemoryInfo> info1, Pointer<OrtMemoryInfo> info2) =>
      withArena((arena) {
        final out0 = arena<Int>();
        checkOrtStatus(this.CompareMemoryInfo.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtMemoryInfo>,
                Pointer<OrtMemoryInfo>, Pointer<Int>)>()(info1, info2, out0));
        return out0.value;
      });

  /// `MemoryInfoGetName`
  String memoryInfoGetName(Pointer<OrtMemoryInfo> ptr) => withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.MemoryInfoGetName.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtMemoryInfo>, Pointer<Pointer<Char>>)>()(ptr, out0));
        return out0.value.cast<Utf8>().toDartString();
      });

  /// `MemoryInfoGetId`
  int memoryInfoGetId(Pointer<OrtMemoryInfo> ptr) => withArena((arena) {
        final out0 = arena<Int>();
        checkOrtStatus(this.MemoryInfoGetId.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtMemoryInfo>, Pointer<Int>)>()(ptr, out0));
        return out0.value;
      });

  /// `MemoryInfoGetMemType`
  int memoryInfoGetMemType(Pointer<OrtMemoryInfo> ptr) => withArena((arena) {
        final out0 = arena<Int>();
        checkOrtStatus(this.MemoryInfoGetMemType.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtMemoryInfo>, Pointer<Int>)>()(ptr, out0));
        return out0.value;
      });

  /// `MemoryInfoGetType`
  int memoryInfoGetType(Pointer<OrtMemoryInfo> ptr) => withArena((arena) {
        final out0 = arena<Int>();
        checkOrtStatus(this.MemoryInfoGetType.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtMemoryInfo>, Pointer<Int>)>()(ptr, out0));
        return out0.value;
      });

  /// `AllocatorAlloc`
  Pointer<Void> allocatorAlloc(Pointer<OrtAllocator> ortAllocator, int size) =>
      withArena((arena) {
        final out0 = arena<Pointer<Void>>();
        checkOrtStatus(this.AllocatorAlloc.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtAllocator>, int,
                Pointer<Pointer<Void>>)>()(ortAllocator, size, out0));
        return out0.value;
      });

  /// `AllocatorFree`
  void allocatorFree(Pointer<OrtAllocator> ortAllocator, Pointer<Void> p) =>
      withArena((arena) {
        checkOrtStatus(this.AllocatorFree.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtAllocator>, Pointer<Void>)>()(ortAllocator, p));
      });

  /// `AllocatorGetInfo`
  Pointer<OrtMemoryInfo> allocatorGetInfo(Pointer<OrtAllocator> ortAllocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtMemoryInfo>>();
        checkOrtStatus(this.AllocatorGetInfo.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtAllocator>,
                Pointer<Pointer<OrtMemoryInfo>>)>()(ortAllocator, out0));
        return out0.value;
      });

  /// `GetAllocatorWithDefaultOptions`
  Pointer<OrtAllocator> getAllocatorWithDefaultOptions() => withArena((arena) {
        final out0 = arena<Pointer<OrtAllocator>>();
        checkOrtStatus(this.GetAllocatorWithDefaultOptions.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<Pointer<OrtAllocator>>)>()(out0));
        return out0.value;
      });

  /// `CreateAllocator`
  Pointer<OrtAllocator> createAllocator(
          Pointer<OrtSession> session, Pointer<OrtMemoryInfo> memInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtAllocator>>();
        checkOrtStatus(this.CreateAllocator.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSession>,
                Pointer<OrtMemoryInfo>,
                Pointer<Pointer<OrtAllocator>>)>()(session, memInfo, out0));
        return out0.value;
      });

  /// `CreateAndRegisterAllocator`
  void createAndRegisterAllocator(Pointer<OrtEnv> env,
          Pointer<OrtMemoryInfo> memInfo, Pointer<OrtArenaCfg> arenaCfg) =>
      withArena((arena) {
        checkOrtStatus(this.CreateAndRegisterAllocator.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtEnv>, Pointer<OrtMemoryInfo>,
                Pointer<OrtArenaCfg>)>()(env, memInfo, arenaCfg));
      });

  /// `RegisterAllocator`
  void registerAllocator(
          Pointer<OrtEnv> env, Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        checkOrtStatus(this.RegisterAllocator.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtEnv>, Pointer<OrtAllocator>)>()(env, allocator));
      });

  /// `UnregisterAllocator`
  void unregisterAllocator(
          Pointer<OrtEnv> env, Pointer<OrtMemoryInfo> memInfo) =>
      withArena((arena) {
        checkOrtStatus(this.UnregisterAllocator.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtEnv>, Pointer<OrtMemoryInfo>)>()(env, memInfo));
      });

  /// `KernelContext_GetAllocator`
  Pointer<OrtAllocator> kernelContext_GetAllocator(
          Pointer<OrtKernelContext> context, Pointer<OrtMemoryInfo> memInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtAllocator>>();
        checkOrtStatus(this.KernelContext_GetAllocator.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtKernelContext>,
                Pointer<OrtMemoryInfo>,
                Pointer<Pointer<OrtAllocator>>)>()(context, memInfo, out0));
        return out0.value;
      });

  /// `CreateAndRegisterAllocatorV2`
  void createAndRegisterAllocatorV2(
          Pointer<OrtEnv> env,
          String providerType,
          Pointer<OrtMemoryInfo> memInfo,
          Pointer<OrtArenaCfg> arenaCfg,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      withArena((arena) {
        checkOrtStatus(this.CreateAndRegisterAllocatorV2.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtEnv>,
                    Pointer<Char>,
                    Pointer<OrtMemoryInfo>,
                    Pointer<OrtArenaCfg>,
                    Pointer<Pointer<Char>>,
                    Pointer<Pointer<Char>>,
                    int)>()(
            env,
            providerType.toNativeUtf8(allocator: arena).cast(),
            memInfo,
            arenaCfg,
            nativeStrings(providerOptionsKeys, arena),
            nativeStrings(providerOptionsValues, arena),
            numKeys));
      });

  /// `KernelInfoGetAllocator`
  Pointer<OrtAllocator> kernelInfoGetAllocator(
          Pointer<OrtKernelInfo> info, int memType) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtAllocator>>();
        checkOrtStatus(this.KernelInfoGetAllocator.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtKernelInfo>, int,
                Pointer<Pointer<OrtAllocator>>)>()(info, memType, out0));
        return out0.value;
      });

  /// `AllocatorGetStats`
  Pointer<OrtKeyValuePairs> allocatorGetStats(
          Pointer<OrtAllocator> ortAllocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtKeyValuePairs>>();
        checkOrtStatus(this.AllocatorGetStats.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtAllocator>,
                Pointer<Pointer<OrtKeyValuePairs>>)>()(ortAllocator, out0));
        return out0.value;
      });

  /// `CreateSharedAllocator`
  Pointer<OrtAllocator> createSharedAllocator(
          Pointer<OrtEnv> env,
          Pointer<OrtEpDevice> epDevice,
          int memType,
          int allocatorType,
          Pointer<OrtKeyValuePairs> allocatorOptions) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtAllocator>>();
        checkOrtStatus(this.CreateSharedAllocator.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtEnv>,
                    Pointer<OrtEpDevice>,
                    int,
                    int,
                    Pointer<OrtKeyValuePairs>,
                    Pointer<Pointer<OrtAllocator>>)>()(
            env, epDevice, memType, allocatorType, allocatorOptions, out0));
        return out0.value;
      });

  /// `GetSharedAllocator`
  Pointer<OrtAllocator> getSharedAllocator(
          Pointer<OrtEnv> env, Pointer<OrtMemoryInfo> memInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtAllocator>>();
        checkOrtStatus(this.GetSharedAllocator.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtEnv>, Pointer<OrtMemoryInfo>,
                Pointer<Pointer<OrtAllocator>>)>()(env, memInfo, out0));
        return out0.value;
      });

  /// `ReleaseSharedAllocator`
  void releaseSharedAllocator(
          Pointer<OrtEnv> env, Pointer<OrtEpDevice> epDevice, int memType) =>
      withArena((arena) {
        checkOrtStatus(this.ReleaseSharedAllocator.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtEnv>, Pointer<OrtEpDevice>,
                int)>()(env, epDevice, memType));
      });

  /// `ReleaseMemoryInfo`
  void releaseMemoryInfo(Pointer<OrtMemoryInfo> input) => this
      .ReleaseMemoryInfo
      .asFunction<void Function(Pointer<OrtMemoryInfo>)>()(input);

  /// `ReleaseAllocator`
  void releaseAllocator(Pointer<OrtAllocator> input) => this
      .ReleaseAllocator
      .asFunction<void Function(Pointer<OrtAllocator>)>()(input);
}
