// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Model calls on `OrtApi`.
extension OrtApiModelApi on OrtApi {
  /// `ModelMetadataGetProducerName`
  String modelMetadataGetProducerName(Pointer<OrtModelMetadata> modelMetadata,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.ModelMetadataGetProducerName.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtModelMetadata>,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(modelMetadata, allocator, out0));
        return takeAllocatedString(out0);
      });

  /// `ModelMetadataGetGraphName`
  String modelMetadataGetGraphName(Pointer<OrtModelMetadata> modelMetadata,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.ModelMetadataGetGraphName.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtModelMetadata>,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(modelMetadata, allocator, out0));
        return takeAllocatedString(out0);
      });

  /// `ModelMetadataGetDomain`
  String modelMetadataGetDomain(Pointer<OrtModelMetadata> modelMetadata,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.ModelMetadataGetDomain.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtModelMetadata>,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(modelMetadata, allocator, out0));
        return takeAllocatedString(out0);
      });

  /// `ModelMetadataGetDescription`
  String modelMetadataGetDescription(Pointer<OrtModelMetadata> modelMetadata,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.ModelMetadataGetDescription.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtModelMetadata>,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(modelMetadata, allocator, out0));
        return takeAllocatedString(out0);
      });

  /// `ModelMetadataLookupCustomMetadataMap`
  String modelMetadataLookupCustomMetadataMap(
          Pointer<OrtModelMetadata> modelMetadata,
          Pointer<OrtAllocator> allocator,
          String key) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.ModelMetadataLookupCustomMetadataMap.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtModelMetadata>,
                    Pointer<OrtAllocator>,
                    Pointer<Char>,
                    Pointer<Pointer<Char>>)>()(modelMetadata, allocator,
            key.toNativeUtf8(allocator: arena).cast(), out0));
        return takeAllocatedString(out0);
      });

  /// `ModelMetadataGetVersion`
  int modelMetadataGetVersion(Pointer<OrtModelMetadata> modelMetadata) =>
      withArena((arena) {
        final out0 = arena<Int64>();
        checkOrtStatus(this.ModelMetadataGetVersion.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtModelMetadata>,
                Pointer<Int64>)>()(modelMetadata, out0));
        return out0.value;
      });

  /// `ModelMetadataGetGraphDescription`
  String modelMetadataGetGraphDescription(
          Pointer<OrtModelMetadata> modelMetadata,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.ModelMetadataGetGraphDescription.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtModelMetadata>,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(modelMetadata, allocator, out0));
        return takeAllocatedString(out0);
      });

  /// `Graph_GetModelMetadata`
  Pointer<OrtModelMetadata> graph_GetModelMetadata(Pointer<OrtGraph> graph) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtModelMetadata>>();
        checkOrtStatus(this.Graph_GetModelMetadata.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtGraph>,
                Pointer<Pointer<OrtModelMetadata>>)>()(graph, out0));
        return out0.value;
      });

  /// `ReleaseModelMetadata`
  void releaseModelMetadata(Pointer<OrtModelMetadata> input) => this
      .ReleaseModelMetadata
      .asFunction<void Function(Pointer<OrtModelMetadata>)>()(input);
}
