// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Options calls on `OrtApi`.
extension OrtApiOptionsApi on OrtApi {
  /// `CreateEnv`
  Pointer<OrtEnv> createEnv(int logSeverityLevel, String logid) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtEnv>>();
        checkOrtStatus(this.CreateEnv.asFunction<
                Pointer<OrtStatus> Function(
                    int, Pointer<Char>, Pointer<Pointer<OrtEnv>>)>()(
            logSeverityLevel,
            logid.toNativeUtf8(allocator: arena).cast(),
            out0));
        return out0.value;
      });

  /// `CreateEnvWithCustomLogger`
  Pointer<OrtEnv> createEnvWithCustomLogger(OrtLoggingFunction loggingFunction,
          Pointer<Void> loggerParam, int logSeverityLevel, String logid) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtEnv>>();
        checkOrtStatus(this.CreateEnvWithCustomLogger.asFunction<
                Pointer<OrtStatus> Function(OrtLoggingFunction, Pointer<Void>,
                    int, Pointer<Char>, Pointer<Pointer<OrtEnv>>)>()(
            loggingFunction,
            loggerParam,
            logSeverityLevel,
            logid.toNativeUtf8(allocator: arena).cast(),
            out0));
        return out0.value;
      });

  /// `EnableTelemetryEvents`
  void enableTelemetryEvents(Pointer<OrtEnv> env) => checkOrtStatus(this
      .EnableTelemetryEvents
      .asFunction<Pointer<OrtStatus> Function(Pointer<OrtEnv>)>()(env));

  /// `DisableTelemetryEvents`
  void disableTelemetryEvents(Pointer<OrtEnv> env) => checkOrtStatus(this
      .DisableTelemetryEvents
      .asFunction<Pointer<OrtStatus> Function(Pointer<OrtEnv>)>()(env));

  /// `SetOptimizedModelFilePath`
  void setOptimizedModelFilePath(
          Pointer<OrtSessionOptions> options, String optimizedModelFilepath) =>
      withArena((arena) {
        checkOrtStatus(this.SetOptimizedModelFilePath.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtSessionOptions>, Pointer<Char>)>()(
            options, allocateOrtPath(optimizedModelFilepath, arena)));
      });

  /// `SetSessionExecutionMode`
  void setSessionExecutionMode(
          Pointer<OrtSessionOptions> options, int executionMode) =>
      checkOrtStatus(this.SetSessionExecutionMode.asFunction<
          Pointer<OrtStatus> Function(
              Pointer<OrtSessionOptions>, int)>()(options, executionMode));

  /// `SetSessionLogId`
  void setSessionLogId(Pointer<OrtSessionOptions> options, String logid) =>
      withArena((arena) {
        checkOrtStatus(this.SetSessionLogId.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtSessionOptions>, Pointer<Char>)>()(
            options, logid.toNativeUtf8(allocator: arena).cast()));
      });

  /// `SetSessionLogVerbosityLevel`
  void setSessionLogVerbosityLevel(
          Pointer<OrtSessionOptions> options, int sessionLogVerbosityLevel) =>
      checkOrtStatus(this.SetSessionLogVerbosityLevel.asFunction<
              Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>, int)>()(
          options, sessionLogVerbosityLevel));

  /// `SetSessionLogSeverityLevel`
  void setSessionLogSeverityLevel(
          Pointer<OrtSessionOptions> options, int sessionLogSeverityLevel) =>
      checkOrtStatus(this.SetSessionLogSeverityLevel.asFunction<
              Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>, int)>()(
          options, sessionLogSeverityLevel));

  /// `SetSessionGraphOptimizationLevel`
  void setSessionGraphOptimizationLevel(
          Pointer<OrtSessionOptions> options, int graphOptimizationLevel) =>
      checkOrtStatus(this.SetSessionGraphOptimizationLevel.asFunction<
              Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>, int)>()(
          options, graphOptimizationLevel));

  /// `SetIntraOpNumThreads`
  void setIntraOpNumThreads(
          Pointer<OrtSessionOptions> options, int intraOpNumThreads) =>
      checkOrtStatus(this.SetIntraOpNumThreads.asFunction<
          Pointer<OrtStatus> Function(
              Pointer<OrtSessionOptions>, int)>()(options, intraOpNumThreads));

  /// `SetInterOpNumThreads`
  void setInterOpNumThreads(
          Pointer<OrtSessionOptions> options, int interOpNumThreads) =>
      checkOrtStatus(this.SetInterOpNumThreads.asFunction<
          Pointer<OrtStatus> Function(
              Pointer<OrtSessionOptions>, int)>()(options, interOpNumThreads));

  /// `CreateRunOptions`
  Pointer<OrtRunOptions> createRunOptions() => withArena((arena) {
        final out0 = arena<Pointer<OrtRunOptions>>();
        checkOrtStatus(this.CreateRunOptions.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<Pointer<OrtRunOptions>>)>()(out0));
        return out0.value;
      });

  /// `RunOptionsSetRunLogVerbosityLevel`
  void runOptionsSetRunLogVerbosityLevel(
          Pointer<OrtRunOptions> options, int logVerbosityLevel) =>
      checkOrtStatus(this.RunOptionsSetRunLogVerbosityLevel.asFunction<
          Pointer<OrtStatus> Function(
              Pointer<OrtRunOptions>, int)>()(options, logVerbosityLevel));

  /// `RunOptionsSetRunLogSeverityLevel`
  void runOptionsSetRunLogSeverityLevel(
          Pointer<OrtRunOptions> options, int logSeverityLevel) =>
      checkOrtStatus(this.RunOptionsSetRunLogSeverityLevel.asFunction<
          Pointer<OrtStatus> Function(
              Pointer<OrtRunOptions>, int)>()(options, logSeverityLevel));

  /// `RunOptionsSetRunTag`
  void runOptionsSetRunTag(Pointer<OrtRunOptions> options, String runTag) =>
      withArena((arena) {
        checkOrtStatus(this.RunOptionsSetRunTag.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtRunOptions>, Pointer<Char>)>()(
            options, runTag.toNativeUtf8(allocator: arena).cast()));
      });

  /// `RunOptionsGetRunLogVerbosityLevel`
  int runOptionsGetRunLogVerbosityLevel(Pointer<OrtRunOptions> options) =>
      withArena((arena) {
        final out0 = arena<Int>();
        checkOrtStatus(this.RunOptionsGetRunLogVerbosityLevel.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtRunOptions>, Pointer<Int>)>()(options, out0));
        return out0.value;
      });

  /// `RunOptionsGetRunLogSeverityLevel`
  int runOptionsGetRunLogSeverityLevel(Pointer<OrtRunOptions> options) =>
      withArena((arena) {
        final out0 = arena<Int>();
        checkOrtStatus(this.RunOptionsGetRunLogSeverityLevel.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtRunOptions>, Pointer<Int>)>()(options, out0));
        return out0.value;
      });

  /// `RunOptionsGetRunTag`
  String runOptionsGetRunTag(Pointer<OrtRunOptions> options) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.RunOptionsGetRunTag.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtRunOptions>,
                Pointer<Pointer<Char>>)>()(options, out0));
        return out0.value.cast<Utf8>().toDartString();
      });

  /// `RunOptionsSetTerminate`
  void runOptionsSetTerminate(Pointer<OrtRunOptions> options) =>
      checkOrtStatus(this.RunOptionsSetTerminate.asFunction<
          Pointer<OrtStatus> Function(Pointer<OrtRunOptions>)>()(options));

  /// `RunOptionsUnsetTerminate`
  void runOptionsUnsetTerminate(Pointer<OrtRunOptions> options) =>
      checkOrtStatus(this.RunOptionsUnsetTerminate.asFunction<
          Pointer<OrtStatus> Function(Pointer<OrtRunOptions>)>()(options));

  /// `AddFreeDimensionOverride`
  void addFreeDimensionOverride(Pointer<OrtSessionOptions> options,
          String dimDenotation, int dimValue) =>
      withArena((arena) {
        checkOrtStatus(this.AddFreeDimensionOverride.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtSessionOptions>, Pointer<Char>, int)>()(options,
            dimDenotation.toNativeUtf8(allocator: arena).cast(), dimValue));
      });

  /// `CreateEnvWithGlobalThreadPools`
  Pointer<OrtEnv> createEnvWithGlobalThreadPools(int logSeverityLevel,
          String logid, Pointer<OrtThreadingOptions> tpOptions) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtEnv>>();
        checkOrtStatus(this.CreateEnvWithGlobalThreadPools.asFunction<
                Pointer<OrtStatus> Function(int, Pointer<Char>,
                    Pointer<OrtThreadingOptions>, Pointer<Pointer<OrtEnv>>)>()(
            logSeverityLevel,
            logid.toNativeUtf8(allocator: arena).cast(),
            tpOptions,
            out0));
        return out0.value;
      });

  /// `DisablePerSessionThreads`
  void disablePerSessionThreads(Pointer<OrtSessionOptions> options) =>
      checkOrtStatus(this.DisablePerSessionThreads.asFunction<
          Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>)>()(options));

  /// `CreateThreadingOptions`
  Pointer<OrtThreadingOptions> createThreadingOptions() => withArena((arena) {
        final out0 = arena<Pointer<OrtThreadingOptions>>();
        checkOrtStatus(this.CreateThreadingOptions.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<Pointer<OrtThreadingOptions>>)>()(out0));
        return out0.value;
      });

  /// `AddFreeDimensionOverrideByName`
  void addFreeDimensionOverrideByName(
          Pointer<OrtSessionOptions> options, String dimName, int dimValue) =>
      withArena((arena) {
        checkOrtStatus(this.AddFreeDimensionOverrideByName.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtSessionOptions>, Pointer<Char>, int)>()(
            options, dimName.toNativeUtf8(allocator: arena).cast(), dimValue));
      });

  /// `AddSessionConfigEntry`
  void addSessionConfigEntry(Pointer<OrtSessionOptions> options,
          String configKey, String configValue) =>
      withArena((arena) {
        checkOrtStatus(this.AddSessionConfigEntry.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                    Pointer<Char>, Pointer<Char>)>()(
            options,
            configKey.toNativeUtf8(allocator: arena).cast(),
            configValue.toNativeUtf8(allocator: arena).cast()));
      });

  /// `SetLanguageProjection`
  void setLanguageProjection(Pointer<OrtEnv> ortEnv, int projection) =>
      checkOrtStatus(this
              .SetLanguageProjection
              .asFunction<Pointer<OrtStatus> Function(Pointer<OrtEnv>, int)>()(
          ortEnv, projection));

  /// `SetGlobalIntraOpNumThreads`
  void setGlobalIntraOpNumThreads(
          Pointer<OrtThreadingOptions> tpOptions, int intraOpNumThreads) =>
      checkOrtStatus(this.SetGlobalIntraOpNumThreads.asFunction<
              Pointer<OrtStatus> Function(Pointer<OrtThreadingOptions>, int)>()(
          tpOptions, intraOpNumThreads));

  /// `SetGlobalInterOpNumThreads`
  void setGlobalInterOpNumThreads(
          Pointer<OrtThreadingOptions> tpOptions, int interOpNumThreads) =>
      checkOrtStatus(this.SetGlobalInterOpNumThreads.asFunction<
              Pointer<OrtStatus> Function(Pointer<OrtThreadingOptions>, int)>()(
          tpOptions, interOpNumThreads));

  /// `SetGlobalSpinControl`
  void setGlobalSpinControl(
          Pointer<OrtThreadingOptions> tpOptions, int allowSpinning) =>
      checkOrtStatus(this.SetGlobalSpinControl.asFunction<
          Pointer<OrtStatus> Function(
              Pointer<OrtThreadingOptions>, int)>()(tpOptions, allowSpinning));

  /// `CreateEnvWithCustomLoggerAndGlobalThreadPools`
  Pointer<OrtEnv> createEnvWithCustomLoggerAndGlobalThreadPools(
          OrtLoggingFunction loggingFunction,
          Pointer<Void> loggerParam,
          int logSeverityLevel,
          String logid,
          Pointer<OrtThreadingOptions> tpOptions) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtEnv>>();
        checkOrtStatus(this
                .CreateEnvWithCustomLoggerAndGlobalThreadPools
                .asFunction<
                    Pointer<OrtStatus> Function(
                        OrtLoggingFunction,
                        Pointer<Void>,
                        int,
                        Pointer<Char>,
                        Pointer<OrtThreadingOptions>,
                        Pointer<Pointer<OrtEnv>>)>()(
            loggingFunction,
            loggerParam,
            logSeverityLevel,
            logid.toNativeUtf8(allocator: arena).cast(),
            tpOptions,
            out0));
        return out0.value;
      });

  /// `SetGlobalDenormalAsZero`
  void setGlobalDenormalAsZero(Pointer<OrtThreadingOptions> tpOptions) =>
      checkOrtStatus(this.SetGlobalDenormalAsZero.asFunction<
          Pointer<OrtStatus> Function(
              Pointer<OrtThreadingOptions>)>()(tpOptions));

  /// `SetCurrentGpuDeviceId`
  void setCurrentGpuDeviceId(int deviceId) => checkOrtStatus(this
      .SetCurrentGpuDeviceId
      .asFunction<Pointer<OrtStatus> Function(int)>()(deviceId));

  /// `AddRunConfigEntry`
  void addRunConfigEntry(Pointer<OrtRunOptions> options, String configKey,
          String configValue) =>
      withArena((arena) {
        checkOrtStatus(this.AddRunConfigEntry.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtRunOptions>, Pointer<Char>, Pointer<Char>)>()(
            options,
            configKey.toNativeUtf8(allocator: arena).cast(),
            configValue.toNativeUtf8(allocator: arena).cast()));
      });

  /// `SetGlobalCustomCreateThreadFn`
  void setGlobalCustomCreateThreadFn(Pointer<OrtThreadingOptions> tpOptions,
          OrtCustomCreateThreadFn ortCustomCreateThreadFn) =>
      checkOrtStatus(this.SetGlobalCustomCreateThreadFn.asFunction<
          Pointer<OrtStatus> Function(Pointer<OrtThreadingOptions>,
              OrtCustomCreateThreadFn)>()(tpOptions, ortCustomCreateThreadFn));

  /// `SetGlobalCustomThreadCreationOptions`
  void setGlobalCustomThreadCreationOptions(
          Pointer<OrtThreadingOptions> tpOptions,
          Pointer<Void> ortCustomThreadCreationOptions) =>
      checkOrtStatus(this.SetGlobalCustomThreadCreationOptions.asFunction<
          Pointer<OrtStatus> Function(Pointer<OrtThreadingOptions>,
              Pointer<Void>)>()(tpOptions, ortCustomThreadCreationOptions));

  /// `SetGlobalCustomJoinThreadFn`
  void setGlobalCustomJoinThreadFn(Pointer<OrtThreadingOptions> tpOptions,
          OrtCustomJoinThreadFn ortCustomJoinThreadFn) =>
      checkOrtStatus(this.SetGlobalCustomJoinThreadFn.asFunction<
          Pointer<OrtStatus> Function(Pointer<OrtThreadingOptions>,
              OrtCustomJoinThreadFn)>()(tpOptions, ortCustomJoinThreadFn));

  /// `UpdateEnvWithCustomLogLevel`
  void updateEnvWithCustomLogLevel(
          Pointer<OrtEnv> ortEnv, int logSeverityLevel) =>
      checkOrtStatus(this
              .UpdateEnvWithCustomLogLevel
              .asFunction<Pointer<OrtStatus> Function(Pointer<OrtEnv>, int)>()(
          ortEnv, logSeverityLevel));

  /// `SetGlobalIntraOpThreadAffinity`
  void setGlobalIntraOpThreadAffinity(
          Pointer<OrtThreadingOptions> tpOptions, String affinityString) =>
      withArena((arena) {
        checkOrtStatus(this.SetGlobalIntraOpThreadAffinity.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtThreadingOptions>, Pointer<Char>)>()(
            tpOptions, affinityString.toNativeUtf8(allocator: arena).cast()));
      });

  /// `HasSessionConfigEntry`
  int hasSessionConfigEntry(
          Pointer<OrtSessionOptions> options, String configKey) =>
      withArena((arena) {
        final out0 = arena<Int>();
        checkOrtStatus(this.HasSessionConfigEntry.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtSessionOptions>, Pointer<Char>, Pointer<Int>)>()(
            options, configKey.toNativeUtf8(allocator: arena).cast(), out0));
        return out0.value;
      });

  /// `GetSessionConfigEntry`
  String getSessionConfigEntry(
          Pointer<OrtSessionOptions> options, String configKey) =>
      withArena((arena) {
        final size = arena<Size>()..value = 0;
        final call = this.GetSessionConfigEntry.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                Pointer<Char>, Pointer<Char>, Pointer<Size>)>();

        // Reports the size it wants and fails because there is no
        // buffer yet. Expected, so the status is released, not checked.
        final asked = call(options,
            configKey.toNativeUtf8(allocator: arena).cast(), nullptr, size);
        if (asked != nullptr) {
          ReleaseStatus.asFunction<void Function(Pointer<OrtStatus>)>()(asked);
        }

        final buffer = arena<Char>(size.value == 0 ? 1 : size.value);
        checkOrtStatus(call(options,
            configKey.toNativeUtf8(allocator: arena).cast(), buffer, size));
        return buffer.cast<Utf8>().toDartString();
      });

  /// `SetDeterministicCompute`
  void setDeterministicCompute(
          Pointer<OrtSessionOptions> options, bool value) =>
      checkOrtStatus(this.SetDeterministicCompute.asFunction<
          Pointer<OrtStatus> Function(
              Pointer<OrtSessionOptions>, bool)>()(options, value));

  /// `SetEpDynamicOptions`
  void setEpDynamicOptions(Pointer<OrtSession> sess, List<String> keys,
          List<String> values, int kvLen) =>
      withArena((arena) {
        checkOrtStatus(this.SetEpDynamicOptions.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtSession>,
                    Pointer<Pointer<Char>>, Pointer<Pointer<Char>>, int)>()(
            sess,
            nativeStrings(keys, arena),
            nativeStrings(values, arena),
            kvLen));
      });

  /// `GetSessionOptionsConfigEntries`
  Pointer<OrtKeyValuePairs> getSessionOptionsConfigEntries(
          Pointer<OrtSessionOptions> options) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtKeyValuePairs>>();
        checkOrtStatus(this.GetSessionOptionsConfigEntries.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                Pointer<Pointer<OrtKeyValuePairs>>)>()(options, out0));
        return out0.value;
      });

  /// `CreateEnvWithOptions`
  Pointer<OrtEnv> createEnvWithOptions(
          Pointer<OrtEnvCreationOptions> options) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtEnv>>();
        checkOrtStatus(this.CreateEnvWithOptions.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtEnvCreationOptions>,
                Pointer<Pointer<OrtEnv>>)>()(options, out0));
        return out0.value;
      });

  /// `SetPerSessionThreadPoolCallbacks`
  void setPerSessionThreadPoolCallbacks(
          Pointer<OrtEnv> env, Pointer<OrtThreadPoolCallbacksConfig> config) =>
      checkOrtStatus(this.SetPerSessionThreadPoolCallbacks.asFunction<
          Pointer<OrtStatus> Function(Pointer<OrtEnv>,
              Pointer<OrtThreadPoolCallbacksConfig>)>()(env, config));

  /// `GetSessionExecutionMode`
  int getSessionExecutionMode(Pointer<OrtSessionOptions> options) =>
      withArena((arena) {
        final out0 = arena<UnsignedInt>();
        checkOrtStatus(this.GetSessionExecutionMode.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                Pointer<UnsignedInt>)>()(options, out0));
        return out0.value;
      });

  /// `ReleaseEnv`
  void releaseEnv(Pointer<OrtEnv> input) =>
      this.ReleaseEnv.asFunction<void Function(Pointer<OrtEnv>)>()(input);

  /// `ReleaseRunOptions`
  void releaseRunOptions(Pointer<OrtRunOptions> input) => this
      .ReleaseRunOptions
      .asFunction<void Function(Pointer<OrtRunOptions>)>()(input);

  /// `ReleaseThreadingOptions`
  void releaseThreadingOptions(Pointer<OrtThreadingOptions> input) => this
      .ReleaseThreadingOptions
      .asFunction<void Function(Pointer<OrtThreadingOptions>)>()(input);
}
