// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Options calls on `OrtApi`.
extension OrtApiOptionsApi on OrtApi {
  /// `CreateEnv`
  Pointer<OrtEnv> createEnv(int logSeverityLevel, String logid) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtEnv>>();
        checkOrtStatus(this.CreateEnv.asFunction<
                Pointer<OrtStatus> Function(
                    int, Pointer<Char>, Pointer<Pointer<OrtEnv>>)>()(
            logSeverityLevel,
            logid.toNativeUtf8(allocator: arena).cast(),
            out0));
        return out0.value;
      });

  /// `CreateRunOptions`
  Pointer<OrtRunOptions> createRunOptions() => withArena((arena) {
        final out0 = arena<Pointer<OrtRunOptions>>();
        checkOrtStatus(this.CreateRunOptions.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<Pointer<OrtRunOptions>>)>()(out0));
        return out0.value;
      });

  /// `RunOptionsSetRunLogVerbosityLevel`
  void runOptionsSetRunLogVerbosityLevel(
          Pointer<OrtRunOptions> options, int logVerbosityLevel) =>
      withArena((arena) {
        checkOrtStatus(this.RunOptionsSetRunLogVerbosityLevel.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtRunOptions>, int)>()(options, logVerbosityLevel));
      });

  /// `RunOptionsSetRunLogSeverityLevel`
  void runOptionsSetRunLogSeverityLevel(
          Pointer<OrtRunOptions> options, int logSeverityLevel) =>
      withArena((arena) {
        checkOrtStatus(this.RunOptionsSetRunLogSeverityLevel.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtRunOptions>, int)>()(options, logSeverityLevel));
      });

  /// `RunOptionsSetRunTag`
  void runOptionsSetRunTag(Pointer<OrtRunOptions> options, String runTag) =>
      withArena((arena) {
        checkOrtStatus(this.RunOptionsSetRunTag.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtRunOptions>, Pointer<Char>)>()(
            options, runTag.toNativeUtf8(allocator: arena).cast()));
      });

  /// `RunOptionsGetRunLogVerbosityLevel`
  int runOptionsGetRunLogVerbosityLevel(Pointer<OrtRunOptions> options) =>
      withArena((arena) {
        final out0 = arena<Int>();
        checkOrtStatus(this.RunOptionsGetRunLogVerbosityLevel.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtRunOptions>, Pointer<Int>)>()(options, out0));
        return out0.value;
      });

  /// `RunOptionsGetRunLogSeverityLevel`
  int runOptionsGetRunLogSeverityLevel(Pointer<OrtRunOptions> options) =>
      withArena((arena) {
        final out0 = arena<Int>();
        checkOrtStatus(this.RunOptionsGetRunLogSeverityLevel.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtRunOptions>, Pointer<Int>)>()(options, out0));
        return out0.value;
      });

  /// `RunOptionsGetRunTag`
  String runOptionsGetRunTag(Pointer<OrtRunOptions> options) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.RunOptionsGetRunTag.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtRunOptions>,
                Pointer<Pointer<Char>>)>()(options, out0));
        return out0.value.cast<Utf8>().toDartString();
      });

  /// `RunOptionsSetTerminate`
  void runOptionsSetTerminate(Pointer<OrtRunOptions> options) =>
      withArena((arena) {
        checkOrtStatus(this.RunOptionsSetTerminate.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtRunOptions>)>()(options));
      });

  /// `RunOptionsUnsetTerminate`
  void runOptionsUnsetTerminate(Pointer<OrtRunOptions> options) =>
      withArena((arena) {
        checkOrtStatus(this.RunOptionsUnsetTerminate.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtRunOptions>)>()(options));
      });

  /// `CreateEnvWithGlobalThreadPools`
  Pointer<OrtEnv> createEnvWithGlobalThreadPools(int logSeverityLevel,
          String logid, Pointer<OrtThreadingOptions> tpOptions) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtEnv>>();
        checkOrtStatus(this.CreateEnvWithGlobalThreadPools.asFunction<
                Pointer<OrtStatus> Function(int, Pointer<Char>,
                    Pointer<OrtThreadingOptions>, Pointer<Pointer<OrtEnv>>)>()(
            logSeverityLevel,
            logid.toNativeUtf8(allocator: arena).cast(),
            tpOptions,
            out0));
        return out0.value;
      });

  /// `CreateThreadingOptions`
  Pointer<OrtThreadingOptions> createThreadingOptions() => withArena((arena) {
        final out0 = arena<Pointer<OrtThreadingOptions>>();
        checkOrtStatus(this.CreateThreadingOptions.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<Pointer<OrtThreadingOptions>>)>()(out0));
        return out0.value;
      });

  /// `SetGlobalIntraOpNumThreads`
  void setGlobalIntraOpNumThreads(
          Pointer<OrtThreadingOptions> tpOptions, int intraOpNumThreads) =>
      withArena((arena) {
        checkOrtStatus(this.SetGlobalIntraOpNumThreads.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtThreadingOptions>,
                int)>()(tpOptions, intraOpNumThreads));
      });

  /// `SetGlobalInterOpNumThreads`
  void setGlobalInterOpNumThreads(
          Pointer<OrtThreadingOptions> tpOptions, int interOpNumThreads) =>
      withArena((arena) {
        checkOrtStatus(this.SetGlobalInterOpNumThreads.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtThreadingOptions>,
                int)>()(tpOptions, interOpNumThreads));
      });

  /// `SetGlobalSpinControl`
  void setGlobalSpinControl(
          Pointer<OrtThreadingOptions> tpOptions, int allowSpinning) =>
      withArena((arena) {
        checkOrtStatus(this.SetGlobalSpinControl.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtThreadingOptions>,
                int)>()(tpOptions, allowSpinning));
      });

  /// `SetGlobalDenormalAsZero`
  void setGlobalDenormalAsZero(Pointer<OrtThreadingOptions> tpOptions) =>
      withArena((arena) {
        checkOrtStatus(this.SetGlobalDenormalAsZero.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtThreadingOptions>)>()(tpOptions));
      });

  /// `CreateArenaCfg`
  Pointer<OrtArenaCfg> createArenaCfg(int maxMem, int arenaExtendStrategy,
          int initialChunkSizeBytes, int maxDeadBytesPerChunk) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtArenaCfg>>();
        checkOrtStatus(this.CreateArenaCfg.asFunction<
                Pointer<OrtStatus> Function(
                    int, int, int, int, Pointer<Pointer<OrtArenaCfg>>)>()(
            maxMem,
            arenaExtendStrategy,
            initialChunkSizeBytes,
            maxDeadBytesPerChunk,
            out0));
        return out0.value;
      });

  /// `CreateArenaCfgV2`
  Pointer<OrtArenaCfg> createArenaCfgV2(List<String> arenaConfigKeys,
          List<int> arenaConfigValues, int numKeys) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtArenaCfg>>();
        checkOrtStatus(this.CreateArenaCfgV2.asFunction<
                Pointer<OrtStatus> Function(Pointer<Pointer<Char>>,
                    Pointer<Size>, int, Pointer<Pointer<OrtArenaCfg>>)>()(
            nativeStrings(arenaConfigKeys, arena),
            nativeSizes(arenaConfigValues, arena),
            numKeys,
            out0));
        return out0.value;
      });

  /// `SetGlobalCustomThreadCreationOptions`
  void setGlobalCustomThreadCreationOptions(
          Pointer<OrtThreadingOptions> tpOptions,
          Pointer<Void> ortCustomThreadCreationOptions) =>
      withArena((arena) {
        checkOrtStatus(this.SetGlobalCustomThreadCreationOptions.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtThreadingOptions>,
                Pointer<Void>)>()(tpOptions, ortCustomThreadCreationOptions));
      });

  /// `SetGlobalIntraOpThreadAffinity`
  void setGlobalIntraOpThreadAffinity(
          Pointer<OrtThreadingOptions> tpOptions, String affinityString) =>
      withArena((arena) {
        checkOrtStatus(this.SetGlobalIntraOpThreadAffinity.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtThreadingOptions>, Pointer<Char>)>()(
            tpOptions, affinityString.toNativeUtf8(allocator: arena).cast()));
      });

  /// `RunOptionsAddActiveLoraAdapter`
  void runOptionsAddActiveLoraAdapter(
          Pointer<OrtRunOptions> options, Pointer<OrtLoraAdapter> adapter) =>
      withArena((arena) {
        checkOrtStatus(this.RunOptionsAddActiveLoraAdapter.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtRunOptions>,
                Pointer<OrtLoraAdapter>)>()(options, adapter));
      });

  /// `GetSessionOptionsConfigEntries`
  Pointer<OrtKeyValuePairs> getSessionOptionsConfigEntries(
          Pointer<OrtSessionOptions> options) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtKeyValuePairs>>();
        checkOrtStatus(this.GetSessionOptionsConfigEntries.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                Pointer<Pointer<OrtKeyValuePairs>>)>()(options, out0));
        return out0.value;
      });

  /// `CreateEnvWithOptions`
  Pointer<OrtEnv> createEnvWithOptions(
          Pointer<OrtEnvCreationOptions> options) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtEnv>>();
        checkOrtStatus(this.CreateEnvWithOptions.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtEnvCreationOptions>,
                Pointer<Pointer<OrtEnv>>)>()(options, out0));
        return out0.value;
      });

  /// `ReleaseEnv`
  void releaseEnv(Pointer<OrtEnv> input) =>
      this.ReleaseEnv.asFunction<void Function(Pointer<OrtEnv>)>()(input);

  /// `ReleaseRunOptions`
  void releaseRunOptions(Pointer<OrtRunOptions> input) => this
      .ReleaseRunOptions
      .asFunction<void Function(Pointer<OrtRunOptions>)>()(input);

  /// `ReleaseThreadingOptions`
  void releaseThreadingOptions(Pointer<OrtThreadingOptions> input) => this
      .ReleaseThreadingOptions
      .asFunction<void Function(Pointer<OrtThreadingOptions>)>()(input);

  /// `ReleaseArenaCfg`
  void releaseArenaCfg(Pointer<OrtArenaCfg> input) => this
      .ReleaseArenaCfg
      .asFunction<void Function(Pointer<OrtArenaCfg>)>()(input);
}
