// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Model calls on `OrtCompileApi`.
extension OrtCompileApiModelApi on OrtCompileApi {
  /// `ModelCompilationOptions_SetInputModelPath`
  void modelCompilationOptions_SetInputModelPath(
          Pointer<OrtModelCompilationOptions> modelCompileOptions,
          String inputModelPath) =>
      withArena((arena) {
        checkOrtStatus(this
                .ModelCompilationOptions_SetInputModelPath
                .asFunction<
                    Pointer<OrtStatus> Function(
                        Pointer<OrtModelCompilationOptions>, Pointer<Char>)>()(
            modelCompileOptions, allocateOrtPath(inputModelPath, arena)));
      });

  /// `ModelCompilationOptions_SetInputModelFromBuffer`
  void modelCompilationOptions_SetInputModelFromBuffer(
          Pointer<OrtModelCompilationOptions> modelCompileOptions,
          Pointer<Void> inputModelData,
          int inputModelDataSize) =>
      checkOrtStatus(this
              .ModelCompilationOptions_SetInputModelFromBuffer
              .asFunction<
                  Pointer<OrtStatus> Function(
                      Pointer<OrtModelCompilationOptions>,
                      Pointer<Void>,
                      int)>()(
          modelCompileOptions, inputModelData, inputModelDataSize));

  /// `ModelCompilationOptions_SetOutputModelPath`
  void modelCompilationOptions_SetOutputModelPath(
          Pointer<OrtModelCompilationOptions> modelCompileOptions,
          String outputModelPath) =>
      withArena((arena) {
        checkOrtStatus(this
                .ModelCompilationOptions_SetOutputModelPath
                .asFunction<
                    Pointer<OrtStatus> Function(
                        Pointer<OrtModelCompilationOptions>, Pointer<Char>)>()(
            modelCompileOptions, allocateOrtPath(outputModelPath, arena)));
      });

  /// `ModelCompilationOptions_SetOutputModelBuffer`
  List<Pointer<Void>> modelCompilationOptions_SetOutputModelBuffer(
          Pointer<OrtModelCompilationOptions> modelCompileOptions,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Void>>();
        final out1 = arena<Size>();
        checkOrtStatus(this
                .ModelCompilationOptions_SetOutputModelBuffer
                .asFunction<
                    Pointer<OrtStatus> Function(
                        Pointer<OrtModelCompilationOptions>,
                        Pointer<OrtAllocator>,
                        Pointer<Pointer<Void>>,
                        Pointer<Size>)>()(
            modelCompileOptions, allocator, out0, out1));
        return List.generate(out1.value, (i) => (out0 + i).value);
      });

  /// `ModelCompilationOptions_SetEpContextEmbedMode`
  void modelCompilationOptions_SetEpContextEmbedMode(
          Pointer<OrtModelCompilationOptions> modelCompileOptions,
          bool embedEpContextInModel) =>
      checkOrtStatus(this
          .ModelCompilationOptions_SetEpContextEmbedMode
          .asFunction<
              Pointer<OrtStatus> Function(Pointer<OrtModelCompilationOptions>,
                  bool)>()(modelCompileOptions, embedEpContextInModel));

  /// `CompileModel`
  void compileModel(Pointer<OrtEnv> env,
          Pointer<OrtModelCompilationOptions> modelOptions) =>
      checkOrtStatus(this.CompileModel.asFunction<
          Pointer<OrtStatus> Function(Pointer<OrtEnv>,
              Pointer<OrtModelCompilationOptions>)>()(env, modelOptions));

  /// `ModelCompilationOptions_SetFlags`
  void modelCompilationOptions_SetFlags(
          Pointer<OrtModelCompilationOptions> modelCompileOptions, int flags) =>
      checkOrtStatus(this.ModelCompilationOptions_SetFlags.asFunction<
          Pointer<OrtStatus> Function(Pointer<OrtModelCompilationOptions>,
              int)>()(modelCompileOptions, flags));

  /// `ModelCompilationOptions_SetEpContextBinaryInformation`
  void modelCompilationOptions_SetEpContextBinaryInformation(
          Pointer<OrtModelCompilationOptions> modelCompileOptions,
          String outputDirectory,
          String modelName) =>
      withArena((arena) {
        checkOrtStatus(this
                .ModelCompilationOptions_SetEpContextBinaryInformation
                .asFunction<
                    Pointer<OrtStatus> Function(
                        Pointer<OrtModelCompilationOptions>,
                        Pointer<Char>,
                        Pointer<Char>)>()(
            modelCompileOptions,
            allocateOrtPath(outputDirectory, arena),
            allocateOrtPath(modelName, arena)));
      });

  /// `ModelCompilationOptions_SetGraphOptimizationLevel`
  void modelCompilationOptions_SetGraphOptimizationLevel(
          Pointer<OrtModelCompilationOptions> modelCompileOptions,
          int graphOptimizationLevel) =>
      checkOrtStatus(this
          .ModelCompilationOptions_SetGraphOptimizationLevel
          .asFunction<
              Pointer<OrtStatus> Function(Pointer<OrtModelCompilationOptions>,
                  int)>()(modelCompileOptions, graphOptimizationLevel));

  /// `ModelCompilationOptions_SetInputModel`
  void modelCompilationOptions_SetInputModel(
          Pointer<OrtModelCompilationOptions> modelCompileOptions,
          Pointer<OrtModel> model) =>
      checkOrtStatus(this.ModelCompilationOptions_SetInputModel.asFunction<
          Pointer<OrtStatus> Function(Pointer<OrtModelCompilationOptions>,
              Pointer<OrtModel>)>()(modelCompileOptions, model));

  /// `ModelCompilationOptions_SetWeightlessEnabled`
  void modelCompilationOptions_SetWeightlessEnabled(
          Pointer<OrtModelCompilationOptions> modelCompileOptions,
          bool useWeightless) =>
      checkOrtStatus(this
          .ModelCompilationOptions_SetWeightlessEnabled
          .asFunction<
              Pointer<OrtStatus> Function(Pointer<OrtModelCompilationOptions>,
                  bool)>()(modelCompileOptions, useWeightless));

  /// `ReleaseModelCompilationOptions`
  void releaseModelCompilationOptions(
          Pointer<OrtModelCompilationOptions> input) =>
      this
              .ReleaseModelCompilationOptions
              .asFunction<void Function(Pointer<OrtModelCompilationOptions>)>()(
          input);
}
