// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Graph calls on `OrtModelEditorApi`.
extension OrtModelEditorApiGraphApi on OrtModelEditorApi {
  /// `CreateValueInfo`
  Pointer<OrtValueInfo> createValueInfo(
          String name, Pointer<OrtTypeInfo> typeInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtValueInfo>>();
        checkOrtStatus(this.CreateValueInfo.asFunction<
                Pointer<OrtStatus> Function(Pointer<Char>, Pointer<OrtTypeInfo>,
                    Pointer<Pointer<OrtValueInfo>>)>()(
            name.toNativeUtf8(allocator: arena).cast(), typeInfo, out0));
        return out0.value;
      });

  /// `AddInitializerToGraph`
  void addInitializerToGraph(Pointer<OrtGraph> graph, String name,
          Pointer<OrtValue> tensor, bool dataIsExternal) =>
      withArena((arena) {
        checkOrtStatus(this.AddInitializerToGraph.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtGraph>, Pointer<Char>,
                    Pointer<OrtValue>, bool)>()(
            graph,
            name.toNativeUtf8(allocator: arena).cast(),
            tensor,
            dataIsExternal));
      });
}
