// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Core calls on `OrtInteropApi`.
extension OrtInteropApiCoreApi on OrtInteropApi {
  /// `CreateExternalResourceImporterForDevice`
  Pointer<OrtExternalResourceImporter> createExternalResourceImporterForDevice(
          Pointer<OrtEpDevice> epDevice) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtExternalResourceImporter>>();
        checkOrtStatus(this.CreateExternalResourceImporterForDevice.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtEpDevice>,
                    Pointer<Pointer<OrtExternalResourceImporter>>)>()(
            epDevice, out0));
        return out0.value;
      });

  /// `ImportMemory`
  Pointer<OrtExternalMemoryHandle> importMemory(
          Pointer<OrtExternalResourceImporter> importer,
          Pointer<OrtExternalMemoryDescriptor> desc) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtExternalMemoryHandle>>();
        checkOrtStatus(this.ImportMemory.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtExternalResourceImporter>,
                    Pointer<OrtExternalMemoryDescriptor>,
                    Pointer<Pointer<OrtExternalMemoryHandle>>)>()(
            importer, desc, out0));
        return out0.value;
      });

  /// `ImportSemaphore`
  Pointer<OrtExternalSemaphoreHandle> importSemaphore(
          Pointer<OrtExternalResourceImporter> importer,
          Pointer<OrtExternalSemaphoreDescriptor> desc) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtExternalSemaphoreHandle>>();
        checkOrtStatus(this.ImportSemaphore.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtExternalResourceImporter>,
                    Pointer<OrtExternalSemaphoreDescriptor>,
                    Pointer<Pointer<OrtExternalSemaphoreHandle>>)>()(
            importer, desc, out0));
        return out0.value;
      });

  /// `WaitSemaphore`
  void waitSemaphore(
          Pointer<OrtExternalResourceImporter> importer,
          Pointer<OrtExternalSemaphoreHandle> semaphoreHandle,
          Pointer<OrtSyncStream> stream,
          int value) =>
      withArena((arena) {
        checkOrtStatus(this.WaitSemaphore.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtExternalResourceImporter>,
                Pointer<OrtExternalSemaphoreHandle>,
                Pointer<OrtSyncStream>,
                int)>()(importer, semaphoreHandle, stream, value));
      });

  /// `SignalSemaphore`
  void signalSemaphore(
          Pointer<OrtExternalResourceImporter> importer,
          Pointer<OrtExternalSemaphoreHandle> semaphoreHandle,
          Pointer<OrtSyncStream> stream,
          int value) =>
      withArena((arena) {
        checkOrtStatus(this.SignalSemaphore.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtExternalResourceImporter>,
                Pointer<OrtExternalSemaphoreHandle>,
                Pointer<OrtSyncStream>,
                int)>()(importer, semaphoreHandle, stream, value));
      });

  /// `ReleaseExternalResourceImporter`
  void releaseExternalResourceImporter(
          Pointer<OrtExternalResourceImporter> input) =>
      this.ReleaseExternalResourceImporter.asFunction<
          void Function(Pointer<OrtExternalResourceImporter>)>()(input);

  /// `ReleaseExternalMemoryHandle`
  void releaseExternalMemoryHandle(Pointer<OrtExternalMemoryHandle> input) =>
      this
          .ReleaseExternalMemoryHandle
          .asFunction<void Function(Pointer<OrtExternalMemoryHandle>)>()(input);

  /// `ReleaseExternalSemaphoreHandle`
  void releaseExternalSemaphoreHandle(
          Pointer<OrtExternalSemaphoreHandle> input) =>
      this
              .ReleaseExternalSemaphoreHandle
              .asFunction<void Function(Pointer<OrtExternalSemaphoreHandle>)>()(
          input);
}
