// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Graph calls on `OrtCompileApi`.
extension OrtCompileApiGraphApi on OrtCompileApi {
  /// `ModelCompilationOptions_SetOutputModelExternalInitializersFile`
  void modelCompilationOptions_SetOutputModelExternalInitializersFile(
          Pointer<OrtModelCompilationOptions> modelCompileOptions,
          String externalInitializersFilePath,
          int externalInitializersSizeThreshold) =>
      withArena((arena) {
        checkOrtStatus(this
                .ModelCompilationOptions_SetOutputModelExternalInitializersFile
                .asFunction<
                    Pointer<OrtStatus> Function(
                        Pointer<OrtModelCompilationOptions>,
                        Pointer<Char>,
                        int)>()(
            modelCompileOptions,
            allocateOrtPath(externalInitializersFilePath, arena),
            externalInitializersSizeThreshold));
      });
}
