// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Tensor calls on `OrtModelEditorApi`.
extension OrtModelEditorApiTensorApi on OrtModelEditorApi {
  /// `CreateTensorTypeInfo`
  Pointer<OrtTypeInfo> createTensorTypeInfo(
          Pointer<OrtTensorTypeAndShapeInfo> tensorInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTypeInfo>>();
        checkOrtStatus(this.CreateTensorTypeInfo.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtTensorTypeAndShapeInfo>,
                Pointer<Pointer<OrtTypeInfo>>)>()(tensorInfo, out0));
        return out0.value;
      });

  /// `CreateSparseTensorTypeInfo`
  Pointer<OrtTypeInfo> createSparseTensorTypeInfo(
          Pointer<OrtTensorTypeAndShapeInfo> tensorInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTypeInfo>>();
        checkOrtStatus(this.CreateSparseTensorTypeInfo.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtTensorTypeAndShapeInfo>,
                Pointer<Pointer<OrtTypeInfo>>)>()(tensorInfo, out0));
        return out0.value;
      });

  /// `CreateMapTypeInfo`
  Pointer<OrtTypeInfo> createMapTypeInfo(
          int mapKeyType, Pointer<OrtTypeInfo> mapValueType) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTypeInfo>>();
        checkOrtStatus(this.CreateMapTypeInfo.asFunction<
                Pointer<OrtStatus> Function(int, Pointer<OrtTypeInfo>,
                    Pointer<Pointer<OrtTypeInfo>>)>()(
            mapKeyType, mapValueType, out0));
        return out0.value;
      });

  /// `CreateSequenceTypeInfo`
  Pointer<OrtTypeInfo> createSequenceTypeInfo(
          Pointer<OrtTypeInfo> sequenceType) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTypeInfo>>();
        checkOrtStatus(this.CreateSequenceTypeInfo.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtTypeInfo>,
                Pointer<Pointer<OrtTypeInfo>>)>()(sequenceType, out0));
        return out0.value;
      });

  /// `CreateOptionalTypeInfo`
  Pointer<OrtTypeInfo> createOptionalTypeInfo(
          Pointer<OrtTypeInfo> containedType) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTypeInfo>>();
        checkOrtStatus(this.CreateOptionalTypeInfo.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtTypeInfo>,
                Pointer<Pointer<OrtTypeInfo>>)>()(containedType, out0));
        return out0.value;
      });

  /// `CreateValueInfo`
  Pointer<OrtValueInfo> createValueInfo(
          String name, Pointer<OrtTypeInfo> typeInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtValueInfo>>();
        checkOrtStatus(this.CreateValueInfo.asFunction<
                Pointer<OrtStatus> Function(Pointer<Char>, Pointer<OrtTypeInfo>,
                    Pointer<Pointer<OrtValueInfo>>)>()(
            name.toNativeUtf8(allocator: arena).cast(), typeInfo, out0));
        return out0.value;
      });
}
