// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Core calls on `OrtModelEditorApi`.
extension OrtModelEditorApiCoreApi on OrtModelEditorApi {
  /// `CreateNode`
  Pointer<OrtNode> createNode(
          String operatorName,
          String domainName,
          String nodeName,
          List<String> inputNames,
          int inputNamesLen,
          List<String> outputNames,
          int outputNamesLen,
          List<Pointer<OrtOpAttr>> attributes,
          int attribsLen) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtNode>>();
        checkOrtStatus(this.CreateNode.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<Char>,
                    Pointer<Char>,
                    Pointer<Char>,
                    Pointer<Pointer<Char>>,
                    int,
                    Pointer<Pointer<Char>>,
                    int,
                    Pointer<Pointer<OrtOpAttr>>,
                    int,
                    Pointer<Pointer<OrtNode>>)>()(
            operatorName.toNativeUtf8(allocator: arena).cast(),
            domainName.toNativeUtf8(allocator: arena).cast(),
            nodeName.toNativeUtf8(allocator: arena).cast(),
            nativeStrings(inputNames, arena),
            inputNamesLen,
            nativeStrings(outputNames, arena),
            outputNamesLen,
            nativePointers(attributes, arena),
            attribsLen,
            out0));
        return out0.value;
      });

  /// `CreateGraph`
  Pointer<OrtGraph> createGraph() => withArena((arena) {
        final out0 = arena<Pointer<OrtGraph>>();
        checkOrtStatus(this.CreateGraph.asFunction<
            Pointer<OrtStatus> Function(Pointer<Pointer<OrtGraph>>)>()(out0));
        return out0.value;
      });

  /// `SetGraphInputs`
  void setGraphInputs(Pointer<OrtGraph> graph,
          List<Pointer<OrtValueInfo>> inputs, int inputsLen) =>
      withArena((arena) {
        checkOrtStatus(this.SetGraphInputs.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtGraph>,
                Pointer<Pointer<OrtValueInfo>>,
                int)>()(graph, nativePointers(inputs, arena), inputsLen));
      });

  /// `SetGraphOutputs`
  void setGraphOutputs(Pointer<OrtGraph> graph,
          List<Pointer<OrtValueInfo>> outputs, int outputsLen) =>
      withArena((arena) {
        checkOrtStatus(this.SetGraphOutputs.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtGraph>,
                Pointer<Pointer<OrtValueInfo>>,
                int)>()(graph, nativePointers(outputs, arena), outputsLen));
      });

  /// `AddNodeToGraph`
  void addNodeToGraph(Pointer<OrtGraph> graph, Pointer<OrtNode> node) =>
      withArena((arena) {
        checkOrtStatus(this.AddNodeToGraph.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtGraph>, Pointer<OrtNode>)>()(graph, node));
      });

  /// `AddGraphToModel`
  void addGraphToModel(Pointer<OrtModel> model, Pointer<OrtGraph> graph) =>
      withArena((arena) {
        checkOrtStatus(this.AddGraphToModel.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtModel>, Pointer<OrtGraph>)>()(model, graph));
      });

  /// `CreateModelEditorSession`
  Pointer<OrtSession> createModelEditorSession(Pointer<OrtEnv> env,
          String modelPath, Pointer<OrtSessionOptions> options) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtSession>>();
        checkOrtStatus(this.CreateModelEditorSession.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtEnv>,
                    Pointer<Char>,
                    Pointer<OrtSessionOptions>,
                    Pointer<Pointer<OrtSession>>)>()(
            env, allocateOrtPath(modelPath, arena), options, out0));
        return out0.value;
      });

  /// `CreateModelEditorSessionFromArray`
  Pointer<OrtSession> createModelEditorSessionFromArray(
          Pointer<OrtEnv> env,
          Pointer<Void> modelData,
          int modelDataLength,
          Pointer<OrtSessionOptions> options) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtSession>>();
        checkOrtStatus(this.CreateModelEditorSessionFromArray.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtEnv>,
                    Pointer<Void>,
                    int,
                    Pointer<OrtSessionOptions>,
                    Pointer<Pointer<OrtSession>>)>()(
            env, modelData, modelDataLength, options, out0));
        return out0.value;
      });

  /// `ApplyModelToModelEditorSession`
  void applyModelToModelEditorSession(
          Pointer<OrtSession> session, Pointer<OrtModel> model) =>
      withArena((arena) {
        checkOrtStatus(this.ApplyModelToModelEditorSession.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSession>, Pointer<OrtModel>)>()(session, model));
      });

  /// `FinalizeModelEditorSession`
  void finalizeModelEditorSession(
          Pointer<OrtSession> session,
          Pointer<OrtSessionOptions> options,
          Pointer<OrtPrepackedWeightsContainer> prepackedWeightsContainer) =>
      withArena((arena) {
        checkOrtStatus(this.FinalizeModelEditorSession.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtSession>,
                    Pointer<OrtSessionOptions>,
                    Pointer<OrtPrepackedWeightsContainer>)>()(
            session, options, prepackedWeightsContainer));
      });
}
