// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Training calls on `OrtTrainingApi`.
extension OrtTrainingApiTrainingApi on OrtTrainingApi {
  /// `CreateTrainingSession`
  Pointer<OrtTrainingSession> createTrainingSession(
          Pointer<OrtEnv> env,
          Pointer<OrtSessionOptions> options,
          Pointer<OrtCheckpointState> checkpointState,
          String trainModelPath,
          String evalModelPath,
          String optimizerModelPath) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTrainingSession>>();
        checkOrtStatus(this.CreateTrainingSession.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtEnv>,
                    Pointer<OrtSessionOptions>,
                    Pointer<OrtCheckpointState>,
                    Pointer<Char>,
                    Pointer<Char>,
                    Pointer<Char>,
                    Pointer<Pointer<OrtTrainingSession>>)>()(
            env,
            options,
            checkpointState,
            allocateOrtPath(trainModelPath, arena),
            allocateOrtPath(evalModelPath, arena),
            allocateOrtPath(optimizerModelPath, arena),
            out0));
        return out0.value;
      });

  /// `CreateTrainingSessionFromBuffer`
  Pointer<OrtTrainingSession> createTrainingSessionFromBuffer(
          Pointer<OrtEnv> env,
          Pointer<OrtSessionOptions> options,
          Pointer<OrtCheckpointState> checkpointState,
          Pointer<Void> trainModelData,
          int trainDataLength,
          Pointer<Void> evalModelData,
          int evalDataLength,
          Pointer<Void> optimModelData,
          int optimDataLength) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTrainingSession>>();
        checkOrtStatus(this.CreateTrainingSessionFromBuffer.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtEnv>,
                    Pointer<OrtSessionOptions>,
                    Pointer<OrtCheckpointState>,
                    Pointer<Void>,
                    int,
                    Pointer<Void>,
                    int,
                    Pointer<Void>,
                    int,
                    Pointer<Pointer<OrtTrainingSession>>)>()(
            env,
            options,
            checkpointState,
            trainModelData,
            trainDataLength,
            evalModelData,
            evalDataLength,
            optimModelData,
            optimDataLength,
            out0));
        return out0.value;
      });

  /// `TrainingSessionGetTrainingModelOutputCount`
  int trainingSessionGetTrainingModelOutputCount(
          Pointer<OrtTrainingSession> sess) =>
      withArena((arena) {
        final out0 = arena<Size>();
        checkOrtStatus(this
            .TrainingSessionGetTrainingModelOutputCount
            .asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtTrainingSession>, Pointer<Size>)>()(sess, out0));
        return out0.value;
      });

  /// `TrainingSessionGetEvalModelOutputCount`
  int trainingSessionGetEvalModelOutputCount(
          Pointer<OrtTrainingSession> sess) =>
      withArena((arena) {
        final out0 = arena<Size>();
        checkOrtStatus(this.TrainingSessionGetEvalModelOutputCount.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtTrainingSession>, Pointer<Size>)>()(sess, out0));
        return out0.value;
      });

  /// `TrainingSessionGetTrainingModelOutputName`
  String trainingSessionGetTrainingModelOutputName(
          Pointer<OrtTrainingSession> sess,
          int index,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this
            .TrainingSessionGetTrainingModelOutputName
            .asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtTrainingSession>,
                    int,
                    Pointer<OrtAllocator>,
                    Pointer<Pointer<Char>>)>()(sess, index, allocator, out0));
        return takeAllocatedString(out0, allocator);
      });

  /// `TrainingSessionGetEvalModelOutputName`
  String trainingSessionGetEvalModelOutputName(Pointer<OrtTrainingSession> sess,
          int index, Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.TrainingSessionGetEvalModelOutputName.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtTrainingSession>,
                int,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(sess, index, allocator, out0));
        return takeAllocatedString(out0, allocator);
      });

  /// `TrainingSessionGetTrainingModelInputCount`
  int trainingSessionGetTrainingModelInputCount(
          Pointer<OrtTrainingSession> sess) =>
      withArena((arena) {
        final out0 = arena<Size>();
        checkOrtStatus(this
            .TrainingSessionGetTrainingModelInputCount
            .asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtTrainingSession>, Pointer<Size>)>()(sess, out0));
        return out0.value;
      });

  /// `TrainingSessionGetEvalModelInputCount`
  int trainingSessionGetEvalModelInputCount(Pointer<OrtTrainingSession> sess) =>
      withArena((arena) {
        final out0 = arena<Size>();
        checkOrtStatus(this.TrainingSessionGetEvalModelInputCount.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtTrainingSession>, Pointer<Size>)>()(sess, out0));
        return out0.value;
      });

  /// `TrainingSessionGetTrainingModelInputName`
  String trainingSessionGetTrainingModelInputName(
          Pointer<OrtTrainingSession> sess,
          int index,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.TrainingSessionGetTrainingModelInputName.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtTrainingSession>,
                int,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(sess, index, allocator, out0));
        return takeAllocatedString(out0, allocator);
      });

  /// `TrainingSessionGetEvalModelInputName`
  String trainingSessionGetEvalModelInputName(Pointer<OrtTrainingSession> sess,
          int index, Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.TrainingSessionGetEvalModelInputName.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtTrainingSession>,
                int,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(sess, index, allocator, out0));
        return takeAllocatedString(out0, allocator);
      });

  /// `ReleaseTrainingSession`
  void releaseTrainingSession(Pointer<OrtTrainingSession> input) => this
      .ReleaseTrainingSession
      .asFunction<void Function(Pointer<OrtTrainingSession>)>()(input);
}
