// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Options calls on `OrtCompileApi`.
extension OrtCompileApiOptionsApi on OrtCompileApi {
  /// `CreateModelCompilationOptionsFromSessionOptions`
  Pointer<OrtModelCompilationOptions>
      createModelCompilationOptionsFromSessionOptions(
              Pointer<OrtEnv> env, Pointer<OrtSessionOptions> sessionOptions) =>
          withArena((arena) {
            final out0 = arena<Pointer<OrtModelCompilationOptions>>();
            checkOrtStatus(this
                    .CreateModelCompilationOptionsFromSessionOptions
                    .asFunction<
                        Pointer<OrtStatus> Function(
                            Pointer<OrtEnv>,
                            Pointer<OrtSessionOptions>,
                            Pointer<Pointer<OrtModelCompilationOptions>>)>()(
                env, sessionOptions, out0));
            return out0.value;
          });
}
