// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Provider calls on `OrtApi`.
extension OrtApiProviderApi on OrtApi {
  /// `CreateCUDAProviderOptions`
  Pointer<OrtCUDAProviderOptionsV2> createCUDAProviderOptions() =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtCUDAProviderOptionsV2>>();
        checkOrtStatus(this.CreateCUDAProviderOptions.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<Pointer<OrtCUDAProviderOptionsV2>>)>()(out0));
        return out0.value;
      });

  /// `UpdateCUDAProviderOptions`
  void updateCUDAProviderOptions(
          Pointer<OrtCUDAProviderOptionsV2> cudaOptions,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      withArena((arena) {
        checkOrtStatus(this.UpdateCUDAProviderOptions.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtCUDAProviderOptionsV2>,
                    Pointer<Pointer<Char>>, Pointer<Pointer<Char>>, int)>()(
            cudaOptions,
            nativeStrings(providerOptionsKeys, arena),
            nativeStrings(providerOptionsValues, arena),
            numKeys));
      });

  /// `GetCUDAProviderOptionsAsString`
  String getCUDAProviderOptionsAsString(
          Pointer<OrtCUDAProviderOptionsV2> cudaOptions,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.GetCUDAProviderOptionsAsString.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtCUDAProviderOptionsV2>,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(cudaOptions, allocator, out0));
        return takeAllocatedString(out0);
      });

  /// `CreateCANNProviderOptions`
  Pointer<OrtCANNProviderOptions> createCANNProviderOptions() =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtCANNProviderOptions>>();
        checkOrtStatus(this.CreateCANNProviderOptions.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<Pointer<OrtCANNProviderOptions>>)>()(out0));
        return out0.value;
      });

  /// `UpdateCANNProviderOptions`
  void updateCANNProviderOptions(
          Pointer<OrtCANNProviderOptions> cannOptions,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      withArena((arena) {
        checkOrtStatus(this.UpdateCANNProviderOptions.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtCANNProviderOptions>,
                    Pointer<Pointer<Char>>, Pointer<Pointer<Char>>, int)>()(
            cannOptions,
            nativeStrings(providerOptionsKeys, arena),
            nativeStrings(providerOptionsValues, arena),
            numKeys));
      });

  /// `GetCANNProviderOptionsAsString`
  String getCANNProviderOptionsAsString(
          Pointer<OrtCANNProviderOptions> cannOptions,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.GetCANNProviderOptionsAsString.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtCANNProviderOptions>,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(cannOptions, allocator, out0));
        return takeAllocatedString(out0);
      });

  /// `CreateDnnlProviderOptions`
  Pointer<OrtDnnlProviderOptions> createDnnlProviderOptions() =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtDnnlProviderOptions>>();
        checkOrtStatus(this.CreateDnnlProviderOptions.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<Pointer<OrtDnnlProviderOptions>>)>()(out0));
        return out0.value;
      });

  /// `UpdateDnnlProviderOptions`
  void updateDnnlProviderOptions(
          Pointer<OrtDnnlProviderOptions> dnnlOptions,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      withArena((arena) {
        checkOrtStatus(this.UpdateDnnlProviderOptions.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtDnnlProviderOptions>,
                    Pointer<Pointer<Char>>, Pointer<Pointer<Char>>, int)>()(
            dnnlOptions,
            nativeStrings(providerOptionsKeys, arena),
            nativeStrings(providerOptionsValues, arena),
            numKeys));
      });

  /// `GetDnnlProviderOptionsAsString`
  String getDnnlProviderOptionsAsString(
          Pointer<OrtDnnlProviderOptions> dnnlOptions,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.GetDnnlProviderOptionsAsString.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtDnnlProviderOptions>,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(dnnlOptions, allocator, out0));
        return takeAllocatedString(out0);
      });

  /// `CreateROCMProviderOptions`
  Pointer<OrtROCMProviderOptions> createROCMProviderOptions() =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtROCMProviderOptions>>();
        checkOrtStatus(this.CreateROCMProviderOptions.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<Pointer<OrtROCMProviderOptions>>)>()(out0));
        return out0.value;
      });

  /// `UpdateROCMProviderOptions`
  void updateROCMProviderOptions(
          Pointer<OrtROCMProviderOptions> rocmOptions,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      withArena((arena) {
        checkOrtStatus(this.UpdateROCMProviderOptions.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtROCMProviderOptions>,
                    Pointer<Pointer<Char>>, Pointer<Pointer<Char>>, int)>()(
            rocmOptions,
            nativeStrings(providerOptionsKeys, arena),
            nativeStrings(providerOptionsValues, arena),
            numKeys));
      });

  /// `GetROCMProviderOptionsAsString`
  String getROCMProviderOptionsAsString(
          Pointer<OrtROCMProviderOptions> rocmOptions,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.GetROCMProviderOptionsAsString.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtROCMProviderOptions>,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(rocmOptions, allocator, out0));
        return takeAllocatedString(out0);
      });

  /// `GetCUDAProviderOptionsByName`
  Pointer<Void> getCUDAProviderOptionsByName(
          Pointer<OrtCUDAProviderOptionsV2> cudaOptions, String key) =>
      withArena((arena) {
        final out0 = arena<Pointer<Void>>();
        checkOrtStatus(this.GetCUDAProviderOptionsByName.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtCUDAProviderOptionsV2>,
                    Pointer<Char>, Pointer<Pointer<Void>>)>()(
            cudaOptions, key.toNativeUtf8(allocator: arena).cast(), out0));
        return out0.value;
      });

  /// `RegisterExecutionProviderLibrary`
  void registerExecutionProviderLibrary(
          Pointer<OrtEnv> env, String registrationName, String path) =>
      withArena((arena) {
        checkOrtStatus(this.RegisterExecutionProviderLibrary.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtEnv>, Pointer<Char>, Pointer<Char>)>()(
            env,
            registrationName.toNativeUtf8(allocator: arena).cast(),
            allocateOrtPath(path, arena)));
      });

  /// `UnregisterExecutionProviderLibrary`
  void unregisterExecutionProviderLibrary(
          Pointer<OrtEnv> env, String registrationName) =>
      withArena((arena) {
        checkOrtStatus(this.UnregisterExecutionProviderLibrary.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtEnv>, Pointer<Char>)>()(
            env, registrationName.toNativeUtf8(allocator: arena).cast()));
      });

  /// `CreateSyncStreamForEpDevice`
  Pointer<OrtSyncStream> createSyncStreamForEpDevice(
          Pointer<OrtEpDevice> epDevice,
          Pointer<OrtKeyValuePairs> streamOptions) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtSyncStream>>();
        checkOrtStatus(this.CreateSyncStreamForEpDevice.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtEpDevice>,
                    Pointer<OrtKeyValuePairs>,
                    Pointer<Pointer<OrtSyncStream>>)>()(
            epDevice, streamOptions, out0));
        return out0.value;
      });
}
