// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Session calls on `OrtApi`.
extension OrtApiSessionApi on OrtApi {
  /// `CreateSession`
  Pointer<OrtSession> createSession(Pointer<OrtEnv> env, String modelPath,
          Pointer<OrtSessionOptions> options) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtSession>>();
        checkOrtStatus(this.CreateSession.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtEnv>,
                    Pointer<Char>,
                    Pointer<OrtSessionOptions>,
                    Pointer<Pointer<OrtSession>>)>()(
            env, allocateOrtPath(modelPath, arena), options, out0));
        return out0.value;
      });

  /// `CreateSessionFromArray`
  Pointer<OrtSession> createSessionFromArray(
          Pointer<OrtEnv> env,
          Pointer<Void> modelData,
          int modelDataLength,
          Pointer<OrtSessionOptions> options) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtSession>>();
        checkOrtStatus(this.CreateSessionFromArray.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtEnv>,
                    Pointer<Void>,
                    int,
                    Pointer<OrtSessionOptions>,
                    Pointer<Pointer<OrtSession>>)>()(
            env, modelData, modelDataLength, options, out0));
        return out0.value;
      });

  /// `Run`
  void run(
          Pointer<OrtSession> session,
          Pointer<OrtRunOptions> runOptions,
          List<String> inputNames,
          List<Pointer<OrtValue>> inputs,
          int inputLen,
          List<String> outputNames,
          int outputNamesLen,
          List<Pointer<OrtValue>> outputs) =>
      withArena((arena) {
        checkOrtStatus(this.Run.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtSession>,
                    Pointer<OrtRunOptions>,
                    Pointer<Pointer<Char>>,
                    Pointer<Pointer<OrtValue>>,
                    int,
                    Pointer<Pointer<Char>>,
                    int,
                    Pointer<Pointer<OrtValue>>)>()(
            session,
            runOptions,
            nativeStrings(inputNames, arena),
            nativePointers(inputs, arena),
            inputLen,
            nativeStrings(outputNames, arena),
            outputNamesLen,
            nativePointers(outputs, arena)));
      });

  /// `CreateSessionOptions`
  Pointer<OrtSessionOptions> createSessionOptions() => withArena((arena) {
        final out0 = arena<Pointer<OrtSessionOptions>>();
        checkOrtStatus(this.CreateSessionOptions.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<Pointer<OrtSessionOptions>>)>()(out0));
        return out0.value;
      });

  /// `CloneSessionOptions`
  Pointer<OrtSessionOptions> cloneSessionOptions(
          Pointer<OrtSessionOptions> inOptions) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtSessionOptions>>();
        checkOrtStatus(this.CloneSessionOptions.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                Pointer<Pointer<OrtSessionOptions>>)>()(inOptions, out0));
        return out0.value;
      });

  /// `EnableProfiling`
  void enableProfiling(
          Pointer<OrtSessionOptions> options, String profileFilePrefix) =>
      withArena((arena) {
        checkOrtStatus(this.EnableProfiling.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtSessionOptions>, Pointer<Char>)>()(
            options, allocateOrtPath(profileFilePrefix, arena)));
      });

  /// `DisableProfiling`
  void disableProfiling(Pointer<OrtSessionOptions> options) =>
      withArena((arena) {
        checkOrtStatus(this.DisableProfiling.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSessionOptions>)>()(options));
      });

  /// `SessionGetInputCount`
  int sessionGetInputCount(Pointer<OrtSession> session) => withArena((arena) {
        final out0 = arena<Size>();
        checkOrtStatus(this.SessionGetInputCount.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSession>, Pointer<Size>)>()(session, out0));
        return out0.value;
      });

  /// `SessionGetOutputCount`
  int sessionGetOutputCount(Pointer<OrtSession> session) => withArena((arena) {
        final out0 = arena<Size>();
        checkOrtStatus(this.SessionGetOutputCount.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSession>, Pointer<Size>)>()(session, out0));
        return out0.value;
      });

  /// `SessionGetInputTypeInfo`
  Pointer<OrtTypeInfo> sessionGetInputTypeInfo(
          Pointer<OrtSession> session, int index) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTypeInfo>>();
        checkOrtStatus(this.SessionGetInputTypeInfo.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtSession>, int,
                Pointer<Pointer<OrtTypeInfo>>)>()(session, index, out0));
        return out0.value;
      });

  /// `SessionGetOutputTypeInfo`
  Pointer<OrtTypeInfo> sessionGetOutputTypeInfo(
          Pointer<OrtSession> session, int index) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTypeInfo>>();
        checkOrtStatus(this.SessionGetOutputTypeInfo.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtSession>, int,
                Pointer<Pointer<OrtTypeInfo>>)>()(session, index, out0));
        return out0.value;
      });

  /// `SessionGetInputName`
  String sessionGetInputName(Pointer<OrtSession> session, int index,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.SessionGetInputName.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSession>,
                int,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(session, index, allocator, out0));
        return takeAllocatedString(out0);
      });

  /// `SessionGetOutputName`
  String sessionGetOutputName(Pointer<OrtSession> session, int index,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.SessionGetOutputName.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSession>,
                int,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(session, index, allocator, out0));
        return takeAllocatedString(out0);
      });

  /// `SessionEndProfiling`
  String sessionEndProfiling(
          Pointer<OrtSession> session, Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.SessionEndProfiling.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSession>,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(session, allocator, out0));
        return takeAllocatedString(out0);
      });

  /// `SessionGetModelMetadata`
  Pointer<OrtModelMetadata> sessionGetModelMetadata(
          Pointer<OrtSession> session) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtModelMetadata>>();
        checkOrtStatus(this.SessionGetModelMetadata.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtSession>,
                Pointer<Pointer<OrtModelMetadata>>)>()(session, out0));
        return out0.value;
      });

  /// `RunWithBinding`
  void runWithBinding(
          Pointer<OrtSession> session,
          Pointer<OrtRunOptions> runOptions,
          Pointer<OrtIoBinding> bindingPtr) =>
      withArena((arena) {
        checkOrtStatus(this.RunWithBinding.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSession>,
                Pointer<OrtRunOptions>,
                Pointer<OrtIoBinding>)>()(session, runOptions, bindingPtr));
      });

  /// `SessionGetProfilingStartTimeNs`
  int sessionGetProfilingStartTimeNs(Pointer<OrtSession> session) =>
      withArena((arena) {
        final out0 = arena<Uint64>();
        checkOrtStatus(this.SessionGetProfilingStartTimeNs.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSession>, Pointer<Uint64>)>()(session, out0));
        return out0.value;
      });

  /// `SessionOptionsAppendExecutionProvider_CUDA`
  void sessionOptionsAppendExecutionProvider_CUDA(
          Pointer<OrtSessionOptions> options,
          Pointer<OrtCUDAProviderOptions> cudaOptions) =>
      withArena((arena) {
        checkOrtStatus(this
            .SessionOptionsAppendExecutionProvider_CUDA
            .asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                    Pointer<OrtCUDAProviderOptions>)>()(options, cudaOptions));
      });

  /// `SessionOptionsAppendExecutionProvider_ROCM`
  void sessionOptionsAppendExecutionProvider_ROCM(
          Pointer<OrtSessionOptions> options,
          Pointer<OrtROCMProviderOptions> rocmOptions) =>
      withArena((arena) {
        checkOrtStatus(this
            .SessionOptionsAppendExecutionProvider_ROCM
            .asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                    Pointer<OrtROCMProviderOptions>)>()(options, rocmOptions));
      });

  /// `SessionOptionsAppendExecutionProvider_OpenVINO`
  void sessionOptionsAppendExecutionProvider_OpenVINO(
          Pointer<OrtSessionOptions> options,
          Pointer<OrtOpenVINOProviderOptions> providerOptions) =>
      withArena((arena) {
        checkOrtStatus(this
                .SessionOptionsAppendExecutionProvider_OpenVINO
                .asFunction<
                    Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                        Pointer<OrtOpenVINOProviderOptions>)>()(
            options, providerOptions));
      });

  /// `SessionOptionsAppendExecutionProvider_TensorRT`
  void sessionOptionsAppendExecutionProvider_TensorRT(
          Pointer<OrtSessionOptions> options,
          Pointer<OrtTensorRTProviderOptions> tensorrtOptions) =>
      withArena((arena) {
        checkOrtStatus(this
                .SessionOptionsAppendExecutionProvider_TensorRT
                .asFunction<
                    Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                        Pointer<OrtTensorRTProviderOptions>)>()(
            options, tensorrtOptions));
      });

  /// `SessionOptionsAppendExecutionProvider_TensorRT_V2`
  void sessionOptionsAppendExecutionProvider_TensorRT_V2(
          Pointer<OrtSessionOptions> options,
          Pointer<OrtTensorRTProviderOptionsV2> tensorrtOptions) =>
      withArena((arena) {
        checkOrtStatus(this
                .SessionOptionsAppendExecutionProvider_TensorRT_V2
                .asFunction<
                    Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                        Pointer<OrtTensorRTProviderOptionsV2>)>()(
            options, tensorrtOptions));
      });

  /// `SessionOptionsSetCustomThreadCreationOptions`
  void sessionOptionsSetCustomThreadCreationOptions(
          Pointer<OrtSessionOptions> options,
          Pointer<Void> ortCustomThreadCreationOptions) =>
      withArena((arena) {
        checkOrtStatus(this
            .SessionOptionsSetCustomThreadCreationOptions
            .asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                    Pointer<Void>)>()(options, ortCustomThreadCreationOptions));
      });

  /// `SessionOptionsAppendExecutionProvider_CUDA_V2`
  void sessionOptionsAppendExecutionProvider_CUDA_V2(
          Pointer<OrtSessionOptions> options,
          Pointer<OrtCUDAProviderOptionsV2> cudaOptions) =>
      withArena((arena) {
        checkOrtStatus(this
                .SessionOptionsAppendExecutionProvider_CUDA_V2
                .asFunction<
                    Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                        Pointer<OrtCUDAProviderOptionsV2>)>()(
            options, cudaOptions));
      });

  /// `SessionOptionsAppendExecutionProvider_MIGraphX`
  void sessionOptionsAppendExecutionProvider_MIGraphX(
          Pointer<OrtSessionOptions> options,
          Pointer<OrtMIGraphXProviderOptions> migraphxOptions) =>
      withArena((arena) {
        checkOrtStatus(this
                .SessionOptionsAppendExecutionProvider_MIGraphX
                .asFunction<
                    Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                        Pointer<OrtMIGraphXProviderOptions>)>()(
            options, migraphxOptions));
      });

  /// `SessionOptionsAppendExecutionProvider`
  void sessionOptionsAppendExecutionProvider(
          Pointer<OrtSessionOptions> options,
          String providerName,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      withArena((arena) {
        checkOrtStatus(this.SessionOptionsAppendExecutionProvider.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtSessionOptions>,
                    Pointer<Char>,
                    Pointer<Pointer<Char>>,
                    Pointer<Pointer<Char>>,
                    int)>()(
            options,
            providerName.toNativeUtf8(allocator: arena).cast(),
            nativeStrings(providerOptionsKeys, arena),
            nativeStrings(providerOptionsValues, arena),
            numKeys));
      });

  /// `SessionOptionsAppendExecutionProvider_CANN`
  void sessionOptionsAppendExecutionProvider_CANN(
          Pointer<OrtSessionOptions> options,
          Pointer<OrtCANNProviderOptions> cannOptions) =>
      withArena((arena) {
        checkOrtStatus(this
            .SessionOptionsAppendExecutionProvider_CANN
            .asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                    Pointer<OrtCANNProviderOptions>)>()(options, cannOptions));
      });

  /// `SessionOptionsAppendExecutionProvider_Dnnl`
  void sessionOptionsAppendExecutionProvider_Dnnl(
          Pointer<OrtSessionOptions> options,
          Pointer<OrtDnnlProviderOptions> dnnlOptions) =>
      withArena((arena) {
        checkOrtStatus(this
            .SessionOptionsAppendExecutionProvider_Dnnl
            .asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                    Pointer<OrtDnnlProviderOptions>)>()(options, dnnlOptions));
      });

  /// `SessionOptionsAppendExecutionProvider_OpenVINO_V2`
  void sessionOptionsAppendExecutionProvider_OpenVINO_V2(
          Pointer<OrtSessionOptions> options,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      withArena((arena) {
        checkOrtStatus(this
                .SessionOptionsAppendExecutionProvider_OpenVINO_V2
                .asFunction<
                    Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                        Pointer<Pointer<Char>>, Pointer<Pointer<Char>>, int)>()(
            options,
            nativeStrings(providerOptionsKeys, arena),
            nativeStrings(providerOptionsValues, arena),
            numKeys));
      });

  /// `SessionOptionsAppendExecutionProvider_VitisAI`
  void sessionOptionsAppendExecutionProvider_VitisAI(
          Pointer<OrtSessionOptions> options,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      withArena((arena) {
        checkOrtStatus(this
                .SessionOptionsAppendExecutionProvider_VitisAI
                .asFunction<
                    Pointer<OrtStatus> Function(Pointer<OrtSessionOptions>,
                        Pointer<Pointer<Char>>, Pointer<Pointer<Char>>, int)>()(
            options,
            nativeStrings(providerOptionsKeys, arena),
            nativeStrings(providerOptionsValues, arena),
            numKeys));
      });

  /// `SessionOptionsSetLoadCancellationFlag`
  void sessionOptionsSetLoadCancellationFlag(
          Pointer<OrtSessionOptions> options, bool cancel) =>
      withArena((arena) {
        checkOrtStatus(this.SessionOptionsSetLoadCancellationFlag.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSessionOptions>, bool)>()(options, cancel));
      });

  /// `SessionOptionsAppendExecutionProvider_V2`
  void sessionOptionsAppendExecutionProvider_V2(
          Pointer<OrtSessionOptions> sessionOptions,
          Pointer<OrtEnv> env,
          List<Pointer<OrtEpDevice>> epDevices,
          int numEpDevices,
          List<String> epOptionKeys,
          List<String> epOptionVals,
          int numEpOptions) =>
      withArena((arena) {
        checkOrtStatus(this.SessionOptionsAppendExecutionProvider_V2.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtSessionOptions>,
                    Pointer<OrtEnv>,
                    Pointer<Pointer<OrtEpDevice>>,
                    int,
                    Pointer<Pointer<Char>>,
                    Pointer<Pointer<Char>>,
                    int)>()(
            sessionOptions,
            env,
            nativePointers(epDevices, arena),
            numEpDevices,
            nativeStrings(epOptionKeys, arena),
            nativeStrings(epOptionVals, arena),
            numEpOptions));
      });

  /// `SessionOptionsSetEpSelectionPolicy`
  void sessionOptionsSetEpSelectionPolicy(
          Pointer<OrtSessionOptions> sessionOptions, int policy) =>
      withArena((arena) {
        checkOrtStatus(this.SessionOptionsSetEpSelectionPolicy.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSessionOptions>, int)>()(sessionOptions, policy));
      });

  /// `RunOptionsEnableProfiling`
  void runOptionsEnableProfiling(
          Pointer<OrtRunOptions> options, String profileFilePrefix) =>
      withArena((arena) {
        checkOrtStatus(this.RunOptionsEnableProfiling.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtRunOptions>, Pointer<Char>)>()(
            options, allocateOrtPath(profileFilePrefix, arena)));
      });

  /// `RunOptionsDisableProfiling`
  void runOptionsDisableProfiling(Pointer<OrtRunOptions> options) =>
      withArena((arena) {
        checkOrtStatus(this.RunOptionsDisableProfiling.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtRunOptions>)>()(options));
      });

  /// `SessionReleaseCapturedGraph`
  void sessionReleaseCapturedGraph(
          Pointer<OrtSession> session, int graphAnnotationId) =>
      withArena((arena) {
        checkOrtStatus(this.SessionReleaseCapturedGraph.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSession>, int)>()(session, graphAnnotationId));
      });

  /// `SessionOptionsSetWeightlessSourceModelBuffer`
  void sessionOptionsSetWeightlessSourceModelBuffer(
          Pointer<OrtSessionOptions> options,
          Pointer<Void> sourceModelData,
          int sourceModelDataLength) =>
      withArena((arena) {
        checkOrtStatus(this
            .SessionOptionsSetWeightlessSourceModelBuffer
            .asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtSessionOptions>,
                    Pointer<Void>,
                    int)>()(options, sourceModelData, sourceModelDataLength));
      });

  /// `ReleaseSession`
  void releaseSession(Pointer<OrtSession> input) => this
      .ReleaseSession
      .asFunction<void Function(Pointer<OrtSession>)>()(input);

  /// `ReleaseSessionOptions`
  void releaseSessionOptions(Pointer<OrtSessionOptions> input) => this
      .ReleaseSessionOptions
      .asFunction<void Function(Pointer<OrtSessionOptions>)>()(input);
}
