// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Tensor calls on `OrtApi`.
extension OrtApiTensorApi on OrtApi {
  /// `CreateTensorAsOrtValue`
  Pointer<OrtValue> createTensorAsOrtValue(Pointer<OrtAllocator> allocator,
          List<int> shape, int shapeLen, int type) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtValue>>();
        checkOrtStatus(this.CreateTensorAsOrtValue.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtAllocator>,
                    Pointer<Int64>, int, int, Pointer<Pointer<OrtValue>>)>()(
            allocator, nativeInt64s(shape, arena), shapeLen, type, out0));
        return out0.value;
      });

  /// `CreateTensorWithDataAsOrtValue`
  ///
  /// Borrows, does not copy: the tensor is a view over `pData` and does not
  /// copy it, so that allocation must outlive the tensor.
  Pointer<OrtValue> createTensorWithDataAsOrtValue(
          Pointer<OrtMemoryInfo> info,
          Pointer<Void> pData,
          int pDataLen,
          List<int> shape,
          int shapeLen,
          int type) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtValue>>();
        checkOrtStatus(this.CreateTensorWithDataAsOrtValue.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtMemoryInfo>,
                    Pointer<Void>,
                    int,
                    Pointer<Int64>,
                    int,
                    int,
                    Pointer<Pointer<OrtValue>>)>()(info, pData, pDataLen,
            nativeInt64s(shape, arena), shapeLen, type, out0));
        return out0.value;
      });

  /// `IsTensor`
  int isTensor(Pointer<OrtValue> value) => withArena((arena) {
        final out0 = arena<Int>();
        checkOrtStatus(this.IsTensor.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtValue>, Pointer<Int>)>()(value, out0));
        return out0.value;
      });

  /// `GetTensorMutableData`
  Pointer<Void> getTensorMutableData(Pointer<OrtValue> value) =>
      withArena((arena) {
        final out0 = arena<Pointer<Void>>();
        checkOrtStatus(this.GetTensorMutableData.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtValue>, Pointer<Pointer<Void>>)>()(value, out0));
        return out0.value;
      });

  /// `FillStringTensor`
  void fillStringTensor(Pointer<OrtValue> value, List<String> s, int sLen) =>
      withArena((arena) {
        checkOrtStatus(this.FillStringTensor.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtValue>,
                Pointer<Pointer<Char>>,
                int)>()(value, nativeStrings(s, arena), sLen));
      });

  /// `GetStringTensorDataLength`
  int getStringTensorDataLength(Pointer<OrtValue> value) => withArena((arena) {
        final out0 = arena<Size>();
        checkOrtStatus(this.GetStringTensorDataLength.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtValue>, Pointer<Size>)>()(value, out0));
        return out0.value;
      });

  /// `CastTypeInfoToTensorInfo`
  Pointer<OrtTensorTypeAndShapeInfo> castTypeInfoToTensorInfo(
          Pointer<OrtTypeInfo> typeInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTensorTypeAndShapeInfo>>();
        checkOrtStatus(this.CastTypeInfoToTensorInfo.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtTypeInfo>,
                    Pointer<Pointer<OrtTensorTypeAndShapeInfo>>)>()(
            typeInfo, out0));
        return out0.value;
      });

  /// `GetOnnxTypeFromTypeInfo`
  int getOnnxTypeFromTypeInfo(Pointer<OrtTypeInfo> typeInfo) =>
      withArena((arena) {
        final out0 = arena<UnsignedInt>();
        checkOrtStatus(this.GetOnnxTypeFromTypeInfo.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtTypeInfo>, Pointer<UnsignedInt>)>()(typeInfo, out0));
        return out0.value;
      });

  /// `CreateTensorTypeAndShapeInfo`
  Pointer<OrtTensorTypeAndShapeInfo> createTensorTypeAndShapeInfo() =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTensorTypeAndShapeInfo>>();
        checkOrtStatus(this.CreateTensorTypeAndShapeInfo.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<Pointer<OrtTensorTypeAndShapeInfo>>)>()(out0));
        return out0.value;
      });

  /// `SetTensorElementType`
  void setTensorElementType(
          Pointer<OrtTensorTypeAndShapeInfo> info, int type) =>
      checkOrtStatus(this.SetTensorElementType.asFunction<
          Pointer<OrtStatus> Function(
              Pointer<OrtTensorTypeAndShapeInfo>, int)>()(info, type));

  /// `SetDimensions`
  void setDimensions(Pointer<OrtTensorTypeAndShapeInfo> info,
          List<int> dimValues, int dimCount) =>
      withArena((arena) {
        checkOrtStatus(this.SetDimensions.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtTensorTypeAndShapeInfo>,
                Pointer<Int64>,
                int)>()(info, nativeInt64s(dimValues, arena), dimCount));
      });

  /// `GetTensorElementType`
  int getTensorElementType(Pointer<OrtTensorTypeAndShapeInfo> info) =>
      withArena((arena) {
        final out0 = arena<UnsignedInt>();
        checkOrtStatus(this.GetTensorElementType.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtTensorTypeAndShapeInfo>,
                Pointer<UnsignedInt>)>()(info, out0));
        return out0.value;
      });

  /// `GetDimensionsCount`
  int getDimensionsCount(Pointer<OrtTensorTypeAndShapeInfo> info) =>
      withArena((arena) {
        final out0 = arena<Size>();
        checkOrtStatus(this.GetDimensionsCount.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtTensorTypeAndShapeInfo>,
                Pointer<Size>)>()(info, out0));
        return out0.value;
      });

  /// `GetDimensions`
  List<int> getDimensions(
          Pointer<OrtTensorTypeAndShapeInfo> info, int dimValuesLength) =>
      withArena((arena) {
        final out0 = arena<Int64>(dimValuesLength);
        checkOrtStatus(this.GetDimensions.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtTensorTypeAndShapeInfo>,
                Pointer<Int64>, int)>()(info, out0, dimValuesLength));
        return List.generate(dimValuesLength, (i) => (out0 + i).value);
      });

  /// `GetTensorShapeElementCount`
  int getTensorShapeElementCount(Pointer<OrtTensorTypeAndShapeInfo> info) =>
      withArena((arena) {
        final out0 = arena<Size>();
        checkOrtStatus(this.GetTensorShapeElementCount.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtTensorTypeAndShapeInfo>,
                Pointer<Size>)>()(info, out0));
        return out0.value;
      });

  /// `GetTensorTypeAndShape`
  Pointer<OrtTensorTypeAndShapeInfo> getTensorTypeAndShape(
          Pointer<OrtValue> value) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTensorTypeAndShapeInfo>>();
        checkOrtStatus(this.GetTensorTypeAndShape.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtValue>,
                Pointer<Pointer<OrtTensorTypeAndShapeInfo>>)>()(value, out0));
        return out0.value;
      });

  /// `GetTypeInfo`
  Pointer<OrtTypeInfo> getTypeInfo(Pointer<OrtValue> value) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTypeInfo>>();
        checkOrtStatus(this.GetTypeInfo.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtValue>,
                Pointer<Pointer<OrtTypeInfo>>)>()(value, out0));
        return out0.value;
      });

  /// `GetValueType`
  int getValueType(Pointer<OrtValue> value) => withArena((arena) {
        final out0 = arena<UnsignedInt>();
        checkOrtStatus(this.GetValueType.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtValue>, Pointer<UnsignedInt>)>()(value, out0));
        return out0.value;
      });

  /// `GetValue`
  Pointer<OrtValue> getValue(Pointer<OrtValue> value, int index,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtValue>>();
        checkOrtStatus(this.GetValue.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtValue>,
                int,
                Pointer<OrtAllocator>,
                Pointer<Pointer<OrtValue>>)>()(value, index, allocator, out0));
        return out0.value;
      });

  /// `GetValueCount`
  int getValueCount(Pointer<OrtValue> value) => withArena((arena) {
        final out0 = arena<Size>();
        checkOrtStatus(this.GetValueCount.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtValue>, Pointer<Size>)>()(value, out0));
        return out0.value;
      });

  /// `CreateValue`
  Pointer<OrtValue> createValue(
          List<Pointer<OrtValue>> in_, int numValues, int valueType) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtValue>>();
        checkOrtStatus(this.CreateValue.asFunction<
                Pointer<OrtStatus> Function(Pointer<Pointer<OrtValue>> in$, int,
                    int, Pointer<Pointer<OrtValue>>)>()(
            nativePointers(in_, arena), numValues, valueType, out0));
        return out0.value;
      });

  /// `CreateOpaqueValue`
  Pointer<OrtValue> createOpaqueValue(String domainName, String typeName,
          Pointer<Void> dataContainer, int dataContainerSize) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtValue>>();
        checkOrtStatus(this.CreateOpaqueValue.asFunction<
                Pointer<OrtStatus> Function(Pointer<Char>, Pointer<Char>,
                    Pointer<Void>, int, Pointer<Pointer<OrtValue>>)>()(
            domainName.toNativeUtf8(allocator: arena).cast(),
            typeName.toNativeUtf8(allocator: arena).cast(),
            dataContainer,
            dataContainerSize,
            out0));
        return out0.value;
      });

  /// `GetDenotationFromTypeInfo`
  (String denotation, int len) getDenotationFromTypeInfo(
          Pointer<OrtTypeInfo> typeInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        final out1 = arena<Size>();
        checkOrtStatus(this.GetDenotationFromTypeInfo.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtTypeInfo>,
                Pointer<Pointer<Char>>,
                Pointer<Size>)>()(typeInfo, out0, out1));
        return (out0.value.cast<Utf8>().toDartString(), out1.value);
      });

  /// `CastTypeInfoToMapTypeInfo`
  Pointer<OrtMapTypeInfo> castTypeInfoToMapTypeInfo(
          Pointer<OrtTypeInfo> typeInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtMapTypeInfo>>();
        checkOrtStatus(this.CastTypeInfoToMapTypeInfo.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtTypeInfo>,
                Pointer<Pointer<OrtMapTypeInfo>>)>()(typeInfo, out0));
        return out0.value;
      });

  /// `CastTypeInfoToSequenceTypeInfo`
  Pointer<OrtSequenceTypeInfo> castTypeInfoToSequenceTypeInfo(
          Pointer<OrtTypeInfo> typeInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtSequenceTypeInfo>>();
        checkOrtStatus(this.CastTypeInfoToSequenceTypeInfo.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtTypeInfo>,
                Pointer<Pointer<OrtSequenceTypeInfo>>)>()(typeInfo, out0));
        return out0.value;
      });

  /// `GetMapKeyType`
  int getMapKeyType(Pointer<OrtMapTypeInfo> mapTypeInfo) => withArena((arena) {
        final out0 = arena<UnsignedInt>();
        checkOrtStatus(this.GetMapKeyType.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtMapTypeInfo>,
                Pointer<UnsignedInt>)>()(mapTypeInfo, out0));
        return out0.value;
      });

  /// `GetMapValueType`
  Pointer<OrtTypeInfo> getMapValueType(Pointer<OrtMapTypeInfo> mapTypeInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTypeInfo>>();
        checkOrtStatus(this.GetMapValueType.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtMapTypeInfo>,
                Pointer<Pointer<OrtTypeInfo>>)>()(mapTypeInfo, out0));
        return out0.value;
      });

  /// `GetSequenceElementType`
  Pointer<OrtTypeInfo> getSequenceElementType(
          Pointer<OrtSequenceTypeInfo> sequenceTypeInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTypeInfo>>();
        checkOrtStatus(this.GetSequenceElementType.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtSequenceTypeInfo>,
                Pointer<Pointer<OrtTypeInfo>>)>()(sequenceTypeInfo, out0));
        return out0.value;
      });

  /// `GetStringTensorElementLength`
  int getStringTensorElementLength(Pointer<OrtValue> value, int index) =>
      withArena((arena) {
        final out0 = arena<Size>();
        checkOrtStatus(this.GetStringTensorElementLength.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtValue>, int, Pointer<Size>)>()(value, index, out0));
        return out0.value;
      });

  /// `FillStringTensorElement`
  void fillStringTensorElement(Pointer<OrtValue> value, String s, int index) =>
      withArena((arena) {
        checkOrtStatus(this.FillStringTensorElement.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtValue>, Pointer<Char>,
                int)>()(value, s.toNativeUtf8(allocator: arena).cast(), index));
      });

  /// `TensorAt`
  Pointer<Void> tensorAt(Pointer<OrtValue> value, List<int> locationValues,
          int locationValuesCount) =>
      withArena((arena) {
        final out0 = arena<Pointer<Void>>();
        checkOrtStatus(this.TensorAt.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtValue>, Pointer<Int64>,
                    int, Pointer<Pointer<Void>>)>()(value,
            nativeInt64s(locationValues, arena), locationValuesCount, out0));
        return out0.value;
      });

  /// `CreateTensorRTProviderOptions`
  Pointer<OrtTensorRTProviderOptionsV2> createTensorRTProviderOptions() =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTensorRTProviderOptionsV2>>();
        checkOrtStatus(this.CreateTensorRTProviderOptions.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<Pointer<OrtTensorRTProviderOptionsV2>>)>()(out0));
        return out0.value;
      });

  /// `UpdateTensorRTProviderOptions`
  void updateTensorRTProviderOptions(
          Pointer<OrtTensorRTProviderOptionsV2> tensorrtOptions,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      withArena((arena) {
        checkOrtStatus(this.UpdateTensorRTProviderOptions.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtTensorRTProviderOptionsV2>,
                    Pointer<Pointer<Char>>,
                    Pointer<Pointer<Char>>,
                    int)>()(
            tensorrtOptions,
            nativeStrings(providerOptionsKeys, arena),
            nativeStrings(providerOptionsValues, arena),
            numKeys));
      });

  /// `GetTensorRTProviderOptionsAsString`
  String getTensorRTProviderOptionsAsString(
          Pointer<OrtTensorRTProviderOptionsV2> tensorrtOptions,
          Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.GetTensorRTProviderOptionsAsString.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtTensorRTProviderOptionsV2>,
                Pointer<OrtAllocator>,
                Pointer<Pointer<Char>>)>()(tensorrtOptions, allocator, out0));
        return takeAllocatedString(out0);
      });

  /// `HasValue`
  int hasValue(Pointer<OrtValue> value) => withArena((arena) {
        final out0 = arena<Int>();
        checkOrtStatus(this.HasValue.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtValue>, Pointer<Int>)>()(value, out0));
        return out0.value;
      });

  /// `CastTypeInfoToOptionalTypeInfo`
  Pointer<OrtOptionalTypeInfo> castTypeInfoToOptionalTypeInfo(
          Pointer<OrtTypeInfo> typeInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtOptionalTypeInfo>>();
        checkOrtStatus(this.CastTypeInfoToOptionalTypeInfo.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtTypeInfo>,
                Pointer<Pointer<OrtOptionalTypeInfo>>)>()(typeInfo, out0));
        return out0.value;
      });

  /// `GetOptionalContainedTypeInfo`
  Pointer<OrtTypeInfo> getOptionalContainedTypeInfo(
          Pointer<OrtOptionalTypeInfo> optionalTypeInfo) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtTypeInfo>>();
        checkOrtStatus(this.GetOptionalContainedTypeInfo.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtOptionalTypeInfo>,
                Pointer<Pointer<OrtTypeInfo>>)>()(optionalTypeInfo, out0));
        return out0.value;
      });

  /// `UpdateTensorRTProviderOptionsWithValue`
  void updateTensorRTProviderOptionsWithValue(
          Pointer<OrtTensorRTProviderOptionsV2> tensorrtOptions,
          String key,
          Pointer<Void> value) =>
      withArena((arena) {
        checkOrtStatus(this.UpdateTensorRTProviderOptionsWithValue.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtTensorRTProviderOptionsV2>,
                    Pointer<Char>,
                    Pointer<Void>)>()(
            tensorrtOptions, key.toNativeUtf8(allocator: arena).cast(), value));
      });

  /// `GetTensorRTProviderOptionsByName`
  Pointer<Void> getTensorRTProviderOptionsByName(
          Pointer<OrtTensorRTProviderOptionsV2> tensorrtOptions, String key) =>
      withArena((arena) {
        final out0 = arena<Pointer<Void>>();
        checkOrtStatus(this.GetTensorRTProviderOptionsByName.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtTensorRTProviderOptionsV2>,
                    Pointer<Char>,
                    Pointer<Pointer<Void>>)>()(
            tensorrtOptions, key.toNativeUtf8(allocator: arena).cast(), out0));
        return out0.value;
      });

  /// `UpdateCUDAProviderOptionsWithValue`
  void updateCUDAProviderOptionsWithValue(
          Pointer<OrtCUDAProviderOptionsV2> cudaOptions,
          String key,
          Pointer<Void> value) =>
      withArena((arena) {
        checkOrtStatus(this.UpdateCUDAProviderOptionsWithValue.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtCUDAProviderOptionsV2>,
                    Pointer<Char>, Pointer<Void>)>()(
            cudaOptions, key.toNativeUtf8(allocator: arena).cast(), value));
      });

  /// `CreateTensorWithDataAndDeleterAsOrtValue`
  Pointer<OrtValue> createTensorWithDataAndDeleterAsOrtValue(
          Pointer<OrtAllocator> deleter,
          Pointer<Void> pData,
          int pDataLen,
          List<int> shape,
          int shapeLen,
          int type) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtValue>>();
        checkOrtStatus(this.CreateTensorWithDataAndDeleterAsOrtValue.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtAllocator>,
                    Pointer<Void>,
                    int,
                    Pointer<Int64>,
                    int,
                    int,
                    Pointer<Pointer<OrtValue>>)>()(deleter, pData, pDataLen,
            nativeInt64s(shape, arena), shapeLen, type, out0));
        return out0.value;
      });

  /// `GetTensorSizeInBytes`
  int getTensorSizeInBytes(Pointer<OrtValue> ortValue) => withArena((arena) {
        final out0 = arena<Size>();
        checkOrtStatus(this.GetTensorSizeInBytes.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtValue>, Pointer<Size>)>()(ortValue, out0));
        return out0.value;
      });

  /// `GetTensorData`
  Pointer<Void> getTensorData(Pointer<OrtValue> value) => withArena((arena) {
        final out0 = arena<Pointer<Void>>();
        checkOrtStatus(this.GetTensorData.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtValue>, Pointer<Pointer<Void>>)>()(value, out0));
        return out0.value;
      });

  /// `CopyTensors`
  void copyTensors(
          Pointer<OrtEnv> env,
          List<Pointer<OrtValue>> srcTensors,
          List<Pointer<OrtValue>> dstTensors,
          Pointer<OrtSyncStream> stream,
          int numTensors) =>
      withArena((arena) {
        checkOrtStatus(this.CopyTensors.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtEnv>,
                    Pointer<Pointer<OrtValue>>,
                    Pointer<Pointer<OrtValue>>,
                    Pointer<OrtSyncStream>,
                    int)>()(env, nativePointers(srcTensors, arena),
            nativePointers(dstTensors, arena), stream, numTensors));
      });

  /// `ReleaseTensorRTProviderOptions`
  void releaseTensorRTProviderOptions(
          Pointer<OrtTensorRTProviderOptionsV2> input) =>
      this.ReleaseTensorRTProviderOptions.asFunction<
          void Function(Pointer<OrtTensorRTProviderOptionsV2>)>()(input);

  /// `CreateKeyValuePairs`
  Pointer<OrtKeyValuePairs> createKeyValuePairs() => withArena((arena) {
        final out0 = arena<Pointer<OrtKeyValuePairs>>();
        this.CreateKeyValuePairs.asFunction<
            void Function(Pointer<Pointer<OrtKeyValuePairs>>)>()(out0);
        return out0.value;
      });

  /// `AddKeyValuePair`
  void addKeyValuePair(
          Pointer<OrtKeyValuePairs> kvps, String key, String value) =>
      withArena((arena) {
        this.AddKeyValuePair.asFunction<
                void Function(
                    Pointer<OrtKeyValuePairs>, Pointer<Char>, Pointer<Char>)>()(
            kvps,
            key.toNativeUtf8(allocator: arena).cast(),
            value.toNativeUtf8(allocator: arena).cast());
      });

  /// `RemoveKeyValuePair`
  void removeKeyValuePair(Pointer<OrtKeyValuePairs> kvps, String key) =>
      withArena((arena) {
        this.RemoveKeyValuePair.asFunction<
                void Function(Pointer<OrtKeyValuePairs>, Pointer<Char>)>()(
            kvps, key.toNativeUtf8(allocator: arena).cast());
      });

  /// `ReleaseValue`
  void releaseValue(Pointer<OrtValue> input) =>
      this.ReleaseValue.asFunction<void Function(Pointer<OrtValue>)>()(input);

  /// `ReleaseTypeInfo`
  void releaseTypeInfo(Pointer<OrtTypeInfo> input) => this
      .ReleaseTypeInfo
      .asFunction<void Function(Pointer<OrtTypeInfo>)>()(input);

  /// `ReleaseTensorTypeAndShapeInfo`
  void releaseTensorTypeAndShapeInfo(
          Pointer<OrtTensorTypeAndShapeInfo> input) =>
      this
              .ReleaseTensorTypeAndShapeInfo
              .asFunction<void Function(Pointer<OrtTensorTypeAndShapeInfo>)>()(
          input);

  /// `ReleaseMapTypeInfo`
  void releaseMapTypeInfo(Pointer<OrtMapTypeInfo> input) => this
      .ReleaseMapTypeInfo
      .asFunction<void Function(Pointer<OrtMapTypeInfo>)>()(input);

  /// `ReleaseSequenceTypeInfo`
  void releaseSequenceTypeInfo(Pointer<OrtSequenceTypeInfo> input) => this
      .ReleaseSequenceTypeInfo
      .asFunction<void Function(Pointer<OrtSequenceTypeInfo>)>()(input);

  /// `ReleaseKeyValuePairs`
  void releaseKeyValuePairs(Pointer<OrtKeyValuePairs> input) => this
      .ReleaseKeyValuePairs
      .asFunction<void Function(Pointer<OrtKeyValuePairs>)>()(input);
}
