// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Training calls on `OrtApi`.
extension OrtApiTrainingApi on OrtApi {
  /// `CreateLoraAdapter`
  Pointer<OrtLoraAdapter> createLoraAdapter(
          String adapterFilePath, Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtLoraAdapter>>();
        checkOrtStatus(this.CreateLoraAdapter.asFunction<
                Pointer<OrtStatus> Function(Pointer<Char>,
                    Pointer<OrtAllocator>, Pointer<Pointer<OrtLoraAdapter>>)>()(
            allocateOrtPath(adapterFilePath, arena), allocator, out0));
        return out0.value;
      });

  /// `CreateLoraAdapterFromArray`
  Pointer<OrtLoraAdapter> createLoraAdapterFromArray(
          Pointer<Void> bytes, int numBytes, Pointer<OrtAllocator> allocator) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtLoraAdapter>>();
        checkOrtStatus(this.CreateLoraAdapterFromArray.asFunction<
                Pointer<OrtStatus> Function(Pointer<Void>, int,
                    Pointer<OrtAllocator>, Pointer<Pointer<OrtLoraAdapter>>)>()(
            bytes, numBytes, allocator, out0));
        return out0.value;
      });

  /// `RunOptionsAddActiveLoraAdapter`
  void runOptionsAddActiveLoraAdapter(
          Pointer<OrtRunOptions> options, Pointer<OrtLoraAdapter> adapter) =>
      checkOrtStatus(this.RunOptionsAddActiveLoraAdapter.asFunction<
          Pointer<OrtStatus> Function(Pointer<OrtRunOptions>,
              Pointer<OrtLoraAdapter>)>()(options, adapter));

  /// `ReleaseLoraAdapter`
  void releaseLoraAdapter(Pointer<OrtLoraAdapter> input) => this
      .ReleaseLoraAdapter
      .asFunction<void Function(Pointer<OrtLoraAdapter>)>()(input);
}
