// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_config_keys.dart from the headers
// in third_party/onnxruntime. Regenerate after moving the
// submodule.

/// Configuration keys understood by ONNX Runtime.
///
/// Most options are set through these rather than through typed
/// calls, and on the web they are the only mechanism.
library;

/// Keys from `onnxruntime_session_options_config_keys.h`.
abstract final class SessionConfig {
  static const disablePrepacking = 'session.disable_prepacking';
  static const useEnvAllocators = 'session.use_env_allocators';
  static const loadModelFormat = 'session.load_model_format';
  static const saveModelFormat = 'session.save_model_format';
  static const setDenormalAsZero = 'session.set_denormal_as_zero';
  static const disableQuantQDQ = 'session.disable_quant_qdq';
  static const disableQDQConstantFolding =
      'session.disable_qdq_constant_folding';
  static const disableDoubleQDQRemover = 'session.disable_double_qdq_remover';
  static const enableQuantQDQCleanup = 'session.enable_quant_qdq_cleanup';
  static const enableGeluApproximation =
      'optimization.enable_gelu_approximation';
  static const enableCastChainElimination =
      'optimization.enable_cast_chain_elimination';
  static const disableAheadOfTimeFunctionInlining =
      'session.disable_aot_function_inlining';
  static const memoryOptimizerApplyConfig =
      'optimization.memory_optimizer_config';
  static const memoryOptimizerProbeConfig =
      'optimization.enable_memory_probe_recompute_config';
  static const disableSpecifiedOptimizers =
      'optimization.disable_specified_optimizers';
  static const constantFoldingMaxOutputSizeInBytes =
      'optimization.constant_folding_max_output_size_in_bytes';
  static const graphOptimizationsLoopLevel =
      'session.graph_optimizations_loop_level';
  static const useDeviceAllocatorForInitializers =
      'session.use_device_allocator_for_initializers';
  static const allowInterOpSpinning = 'session.inter_op.allow_spinning';
  static const allowIntraOpSpinning = 'session.intra_op.allow_spinning';
  static const intraOpSpinDurationUs = 'session.intra_op.spin_duration_us';
  static const interOpSpinDurationUs = 'session.inter_op.spin_duration_us';
  static const intraOpSpinBackoffMax = 'session.intra_op.spin_backoff_max';
  static const interOpSpinBackoffMax = 'session.inter_op.spin_backoff_max';
  static const useORTModelBytesDirectly =
      'session.use_ort_model_bytes_directly';
  static const useORTModelBytesForInitializers =
      'session.use_ort_model_bytes_for_initializers';
  static const useMemoryMappedOrtModel = 'session.use_memory_mapped_ort_model';
  static const qdqIsInt8Allowed = 'session.qdqisint8allowed';
  static const avx2PrecisionMode = 'session.x64quantprecision';
  static const minimalBuildOptimizations =
      'optimization.minimal_build_optimizations';
  static const nnapiEpPartitioningStopOps = 'ep.nnapi.partitioning_stop_ops';
  static const dynamicBlockBase = 'session.dynamic_block_base';
  static const forceSpinningStop = 'session.force_spinning_stop';
  static const strictShapeTypeInference = 'session.strict_shape_type_inference';
  static const strictAllowReleasedOpsetsOnly =
      'session.allow_released_opsets_only';
  static const nodePartitionConfigFile = 'session.node_partition_config_file';
  static const intraOpThreadAffinities = 'session.intra_op_thread_affinities';
  static const debugLayoutTransformation =
      'session.debug_layout_transformation';
  static const disableCPUEPFallback = 'session.disable_cpu_ep_fallback';
  static const optimizedModelExternalInitializersFileName =
      'session.optimized_model_external_initializers_file_name';
  static const optimizedModelExternalInitializersMinSizeInBytes =
      'session.optimized_model_external_initializers_min_size_in_bytes';
  static const modelExternalInitializersFileFolderPath =
      'session.model_external_initializers_file_folder_path';
  static const savePrePackedConstantInitializers =
      'session.save_external_prepacked_constant_initializers';
  static const collectNodeMemoryStatsToFile =
      'session.collect_node_memory_stats_to_file';
  static const resourceCudaPartitioningSettings =
      'session.resource_cuda_partitioning_settings';
  static const layerAssignmentSettings = 'session.layer_assignment_settings';
  static const nameBasedLayerAssignment = 'session.name_based_layer_assignment';
  static const maxShapeOverride = 'session.max_shape_override';
  static const epContextEnable = 'ep.context_enable';
  static const epContextFilePath = 'ep.context_file_path';
  static const epContextEmbedMode = 'ep.context_embed_mode';
  static const epContextNodeNamePrefix = 'ep.context_node_name_prefix';
  static const shareEpContexts = 'ep.share_ep_contexts';
  static const stopShareEpContexts = 'ep.stop_share_ep_contexts';
  static const epContextModelExternalInitializersFileName =
      'ep.context_model_external_initializers_file_name';
  static const compileOnly = 'session.compile_only';
  static const mlasGemmFastMathArm64Bfloat16 =
      'mlas.enable_gemm_fastmath_arm64_bfloat16';
  static const mlasLutGemm = 'mlas.use_lut_gemm';
  static const mlasDisableKleidiAi = 'mlas.disable_kleidiai';
  static const mlasKleidiAiConvIgemmMaxWork =
      'mlas.kleidiai.conv_igemm_max_work';
  static const qdqMatMulNBitsAccuracyLevel =
      'session.qdq_matmulnbits_accuracy_level';
  static const qdqMatMulNBitsBlockSize = 'session.qdq_matmulnbits_block_size';
  static const enableDQMatMulNBitsFusion =
      'session.enable_dq_matmulnbits_fusion';
  static const workloadType = 'ep.dynamic.workload_type';
  static const disableModelCompile = 'session.disable_model_compile';
  static const failOnSuboptimalCompiledModel =
      'session.fail_on_suboptimal_compiled_model';
  static const qnnHtpPerformanceMode = 'ep.dynamic.qnn_htp_performance_mode';
  static const recordEpGraphAssignmentInfo =
      'session.record_ep_graph_assignment_info';
  static const epEnableWeightlessEpContextNodes =
      'ep.enable_weightless_ep_context_nodes';
  static const epEnableWeightless = 'ep.enable_weightless';
  static const epContextSourceModelPath = 'ep.context_source_model_path';
  static const intraOpNumThreads = 'session.intra_op_num_threads';
  static const interOpNumThreads = 'session.inter_op_num_threads';
  static const enableCpuMemArena = 'session.enable_cpu_mem_arena';
  static const enableMemPattern = 'session.enable_mem_pattern';
  static const logId = 'session.log_id';
  static const logSeverityLevel = 'session.log_severity_level';
  static const logVerbosityLevel = 'session.log_verbosity_level';
  static const enableProfiling = 'session.enable_profiling';
  static const graphOptimizationLevel = 'session.graph_optimization_level';
  static const optimizedModelFilePath = 'session.optimized_model_filepath';
  static const executionMode = 'session.execution_mode';
  static const usePerSessionThreads = 'session.use_per_session_threads';
  static const useDeterministicCompute = 'session.use_deterministic_compute';

  /// Every key in this group, for tests and diagnostics.
  static const all = <String>[
    disablePrepacking,
    useEnvAllocators,
    loadModelFormat,
    saveModelFormat,
    setDenormalAsZero,
    disableQuantQDQ,
    disableQDQConstantFolding,
    disableDoubleQDQRemover,
    enableQuantQDQCleanup,
    enableGeluApproximation,
    enableCastChainElimination,
    disableAheadOfTimeFunctionInlining,
    memoryOptimizerApplyConfig,
    memoryOptimizerProbeConfig,
    disableSpecifiedOptimizers,
    constantFoldingMaxOutputSizeInBytes,
    graphOptimizationsLoopLevel,
    useDeviceAllocatorForInitializers,
    allowInterOpSpinning,
    allowIntraOpSpinning,
    intraOpSpinDurationUs,
    interOpSpinDurationUs,
    intraOpSpinBackoffMax,
    interOpSpinBackoffMax,
    useORTModelBytesDirectly,
    useORTModelBytesForInitializers,
    useMemoryMappedOrtModel,
    qdqIsInt8Allowed,
    avx2PrecisionMode,
    minimalBuildOptimizations,
    nnapiEpPartitioningStopOps,
    dynamicBlockBase,
    forceSpinningStop,
    strictShapeTypeInference,
    strictAllowReleasedOpsetsOnly,
    nodePartitionConfigFile,
    intraOpThreadAffinities,
    debugLayoutTransformation,
    disableCPUEPFallback,
    optimizedModelExternalInitializersFileName,
    optimizedModelExternalInitializersMinSizeInBytes,
    modelExternalInitializersFileFolderPath,
    savePrePackedConstantInitializers,
    collectNodeMemoryStatsToFile,
    resourceCudaPartitioningSettings,
    layerAssignmentSettings,
    nameBasedLayerAssignment,
    maxShapeOverride,
    epContextEnable,
    epContextFilePath,
    epContextEmbedMode,
    epContextNodeNamePrefix,
    shareEpContexts,
    stopShareEpContexts,
    epContextModelExternalInitializersFileName,
    compileOnly,
    mlasGemmFastMathArm64Bfloat16,
    mlasLutGemm,
    mlasDisableKleidiAi,
    mlasKleidiAiConvIgemmMaxWork,
    qdqMatMulNBitsAccuracyLevel,
    qdqMatMulNBitsBlockSize,
    enableDQMatMulNBitsFusion,
    workloadType,
    disableModelCompile,
    failOnSuboptimalCompiledModel,
    qnnHtpPerformanceMode,
    recordEpGraphAssignmentInfo,
    epEnableWeightlessEpContextNodes,
    epEnableWeightless,
    epContextSourceModelPath,
    intraOpNumThreads,
    interOpNumThreads,
    enableCpuMemArena,
    enableMemPattern,
    logId,
    logSeverityLevel,
    logVerbosityLevel,
    enableProfiling,
    graphOptimizationLevel,
    optimizedModelFilePath,
    executionMode,
    usePerSessionThreads,
    useDeterministicCompute,
  ];
}

/// Keys from `onnxruntime_run_options_config_keys.h`.
abstract final class RunConfig {
  static const enableMemoryArenaShrinkage =
      'memory.enable_memory_arena_shrinkage';
  static const disableSynchronizeExecutionProviders =
      'disable_synchronize_execution_providers';
  static const qnnPerfMode = 'qnn.htp_perf_mode';
  static const qnnPerfModePostRun = 'qnn.htp_perf_mode_post_run';
  static const qnnRpcControlLatency = 'qnn.rpc_control_latency';
  static const qnnLoraConfig = 'qnn.lora_config';
  static const cudaGraphAnnotation = 'gpu_graph_id';

  /// Every key in this group, for tests and diagnostics.
  static const all = <String>[
    enableMemoryArenaShrinkage,
    disableSynchronizeExecutionProviders,
    qnnPerfMode,
    qnnPerfModePostRun,
    qnnRpcControlLatency,
    qnnLoraConfig,
    cudaGraphAnnotation,
  ];
}

/// Keys from `onnxruntime_env_config_keys.h`.
abstract final class EnvConfig {
  static const allowVirtualDevices = 'allow_virtual_devices';

  /// Every key in this group, for tests and diagnostics.
  static const all = <String>[
    allowVirtualDevices,
  ];
}
