// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Ep calls on `OrtApi`.
extension OrtApiEpApi on OrtApi {
  /// `RegisterExecutionProviderLibrary`
  void registerExecutionProviderLibrary(
          Pointer<OrtEnv> env, String registrationName, String path) =>
      withArena((arena) {
        checkOrtStatus(this.RegisterExecutionProviderLibrary.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtEnv>, Pointer<Char>, Pointer<Char>)>()(
            env,
            registrationName.toNativeUtf8(allocator: arena).cast(),
            allocateOrtPath(path, arena)));
      });

  /// `UnregisterExecutionProviderLibrary`
  void unregisterExecutionProviderLibrary(
          Pointer<OrtEnv> env, String registrationName) =>
      withArena((arena) {
        checkOrtStatus(this.UnregisterExecutionProviderLibrary.asFunction<
                Pointer<OrtStatus> Function(Pointer<OrtEnv>, Pointer<Char>)>()(
            env, registrationName.toNativeUtf8(allocator: arena).cast()));
      });

  /// `GetEpDevices`
  List<Pointer<OrtEpDevice>> getEpDevices(Pointer<OrtEnv> env) =>
      withArena((arena) {
        final out0 = arena<Pointer<Pointer<OrtEpDevice>>>();
        final out1 = arena<Size>();
        checkOrtStatus(this.GetEpDevices.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtEnv>,
                Pointer<Pointer<Pointer<OrtEpDevice>>>,
                Pointer<Size>)>()(env, out0, out1));
        return List.generate(out1.value, (i) => out0.value[i]);
      });

  /// `SessionGetEpDeviceForInputs`
  List<Pointer<OrtEpDevice>> sessionGetEpDeviceForInputs(
          Pointer<OrtSession> session, int numInputs) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtEpDevice>>(numInputs);
        checkOrtStatus(this.SessionGetEpDeviceForInputs.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSession>,
                Pointer<Pointer<OrtEpDevice>>,
                int)>()(session, out0, numInputs));
        return List.generate(numInputs, (i) => (out0 + i).value);
      });

  /// `CreateSyncStreamForEpDevice`
  Pointer<OrtSyncStream> createSyncStreamForEpDevice(
          Pointer<OrtEpDevice> epDevice,
          Pointer<OrtKeyValuePairs> streamOptions) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtSyncStream>>();
        checkOrtStatus(this.CreateSyncStreamForEpDevice.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtEpDevice>,
                    Pointer<OrtKeyValuePairs>,
                    Pointer<Pointer<OrtSyncStream>>)>()(
            epDevice, streamOptions, out0));
        return out0.value;
      });

  /// `GetModelCompatibilityForEpDevices`
  int getModelCompatibilityForEpDevices(List<Pointer<OrtEpDevice>> epDevices,
          int numEpDevices, String compatibilityInfo) =>
      withArena((arena) {
        final out0 = arena<UnsignedInt>();
        checkOrtStatus(this.GetModelCompatibilityForEpDevices.asFunction<
                Pointer<OrtStatus> Function(Pointer<Pointer<OrtEpDevice>>, int,
                    Pointer<Char>, Pointer<UnsignedInt>)>()(
            nativePointers(epDevices, arena),
            numEpDevices,
            compatibilityInfo.toNativeUtf8(allocator: arena).cast(),
            out0));
        return out0.value;
      });

  /// `SessionGetEpDeviceForOutputs`
  List<Pointer<OrtEpDevice>> sessionGetEpDeviceForOutputs(
          Pointer<OrtSession> session, int numOutputs) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtEpDevice>>(numOutputs);
        checkOrtStatus(this.SessionGetEpDeviceForOutputs.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSession>,
                Pointer<Pointer<OrtEpDevice>>,
                int)>()(session, out0, numOutputs));
        return List.generate(numOutputs, (i) => (out0 + i).value);
      });

  /// `GetNumHardwareDevices`
  int getNumHardwareDevices(Pointer<OrtEnv> env) => withArena((arena) {
        final out0 = arena<Size>();
        checkOrtStatus(this.GetNumHardwareDevices.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtEnv>, Pointer<Size>)>()(env, out0));
        return out0.value;
      });

  /// `GetHardwareDevices`
  List<Pointer<OrtHardwareDevice>> getHardwareDevices(
          Pointer<OrtEnv> env, int numDevices) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtHardwareDevice>>(numDevices);
        checkOrtStatus(this.GetHardwareDevices.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtEnv>,
                Pointer<Pointer<OrtHardwareDevice>>,
                int)>()(env, out0, numDevices));
        return List.generate(numDevices, (i) => (out0 + i).value);
      });

  /// `GetHardwareDeviceEpIncompatibilityDetails`
  Pointer<OrtDeviceEpIncompatibilityDetails>
      getHardwareDeviceEpIncompatibilityDetails(Pointer<OrtEnv> env,
              String epName, Pointer<OrtHardwareDevice> hw) =>
          withArena((arena) {
            final out0 = arena<Pointer<OrtDeviceEpIncompatibilityDetails>>();
            checkOrtStatus(this
                    .GetHardwareDeviceEpIncompatibilityDetails
                    .asFunction<
                        Pointer<OrtStatus> Function(
                            Pointer<OrtEnv>,
                            Pointer<Char>,
                            Pointer<OrtHardwareDevice>,
                            Pointer<
                                Pointer<OrtDeviceEpIncompatibilityDetails>>)>()(
                env, epName.toNativeUtf8(allocator: arena).cast(), hw, out0));
            return out0.value;
          });

  /// `DeviceEpIncompatibilityDetails_GetReasonsBitmask`
  int deviceEpIncompatibilityDetails_GetReasonsBitmask(
          Pointer<OrtDeviceEpIncompatibilityDetails> details) =>
      withArena((arena) {
        final out0 = arena<Uint32>();
        checkOrtStatus(this
            .DeviceEpIncompatibilityDetails_GetReasonsBitmask
            .asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtDeviceEpIncompatibilityDetails>,
                    Pointer<Uint32>)>()(details, out0));
        return out0.value;
      });

  /// `DeviceEpIncompatibilityDetails_GetNotes`
  String deviceEpIncompatibilityDetails_GetNotes(
          Pointer<OrtDeviceEpIncompatibilityDetails> details) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.DeviceEpIncompatibilityDetails_GetNotes.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtDeviceEpIncompatibilityDetails>,
                Pointer<Pointer<Char>>)>()(details, out0));
        return out0.value.cast<Utf8>().toDartString();
      });

  /// `DeviceEpIncompatibilityDetails_GetErrorCode`
  int deviceEpIncompatibilityDetails_GetErrorCode(
          Pointer<OrtDeviceEpIncompatibilityDetails> details) =>
      withArena((arena) {
        final out0 = arena<Int32>();
        checkOrtStatus(this
            .DeviceEpIncompatibilityDetails_GetErrorCode
            .asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtDeviceEpIncompatibilityDetails>,
                    Pointer<Int32>)>()(details, out0));
        return out0.value;
      });

  /// `Session_GetEpGraphAssignmentInfo`
  List<Pointer<OrtEpAssignedSubgraph>> session_GetEpGraphAssignmentInfo(
          Pointer<OrtSession> session) =>
      withArena((arena) {
        final out0 = arena<Pointer<Pointer<OrtEpAssignedSubgraph>>>();
        final out1 = arena<Size>();
        checkOrtStatus(this.Session_GetEpGraphAssignmentInfo.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtSession>,
                Pointer<Pointer<Pointer<OrtEpAssignedSubgraph>>>,
                Pointer<Size>)>()(session, out0, out1));
        return List.generate(out1.value, (i) => out0.value[i]);
      });

  /// `EpAssignedSubgraph_GetEpName`
  String epAssignedSubgraph_GetEpName(
          Pointer<OrtEpAssignedSubgraph> epSubgraph) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.EpAssignedSubgraph_GetEpName.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtEpAssignedSubgraph>,
                Pointer<Pointer<Char>>)>()(epSubgraph, out0));
        return out0.value.cast<Utf8>().toDartString();
      });

  /// `EpAssignedSubgraph_GetNodes`
  List<Pointer<OrtEpAssignedNode>> epAssignedSubgraph_GetNodes(
          Pointer<OrtEpAssignedSubgraph> epSubgraph) =>
      withArena((arena) {
        final out0 = arena<Pointer<Pointer<OrtEpAssignedNode>>>();
        final out1 = arena<Size>();
        checkOrtStatus(this.EpAssignedSubgraph_GetNodes.asFunction<
            Pointer<OrtStatus> Function(
                Pointer<OrtEpAssignedSubgraph>,
                Pointer<Pointer<Pointer<OrtEpAssignedNode>>>,
                Pointer<Size>)>()(epSubgraph, out0, out1));
        return List.generate(out1.value, (i) => out0.value[i]);
      });

  /// `EpAssignedNode_GetName`
  String epAssignedNode_GetName(Pointer<OrtEpAssignedNode> epNode) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.EpAssignedNode_GetName.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtEpAssignedNode>,
                Pointer<Pointer<Char>>)>()(epNode, out0));
        return out0.value.cast<Utf8>().toDartString();
      });

  /// `EpAssignedNode_GetDomain`
  String epAssignedNode_GetDomain(Pointer<OrtEpAssignedNode> epNode) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.EpAssignedNode_GetDomain.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtEpAssignedNode>,
                Pointer<Pointer<Char>>)>()(epNode, out0));
        return out0.value.cast<Utf8>().toDartString();
      });

  /// `EpAssignedNode_GetOperatorType`
  String epAssignedNode_GetOperatorType(Pointer<OrtEpAssignedNode> epNode) =>
      withArena((arena) {
        final out0 = arena<Pointer<Char>>();
        checkOrtStatus(this.EpAssignedNode_GetOperatorType.asFunction<
            Pointer<OrtStatus> Function(Pointer<OrtEpAssignedNode>,
                Pointer<Pointer<Char>>)>()(epNode, out0));
        return out0.value.cast<Utf8>().toDartString();
      });

  /// `ReleaseSyncStream`
  void releaseSyncStream(Pointer<OrtSyncStream> input) => this
      .ReleaseSyncStream
      .asFunction<void Function(Pointer<OrtSyncStream>)>()(input);

  /// `ReleaseDeviceEpIncompatibilityDetails`
  void releaseDeviceEpIncompatibilityDetails(
          Pointer<OrtDeviceEpIncompatibilityDetails> input) =>
      this.ReleaseDeviceEpIncompatibilityDetails.asFunction<
          void Function(Pointer<OrtDeviceEpIncompatibilityDetails>)>()(input);
}
