// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../ort_bindings.g.dart';
import 'support.dart';

/// Tensor calls on `OrtInteropApi`.
extension OrtInteropApiTensorApi on OrtInteropApi {
  /// `CreateTensorFromMemory`
  ///
  /// Borrows, does not copy: the tensor is a view over the imported memory,
  /// which must outlive it.
  Pointer<OrtValue> createTensorFromMemory(
          Pointer<OrtExternalResourceImporter> importer,
          Pointer<OrtExternalMemoryHandle> memHandle,
          Pointer<OrtExternalTensorDescriptor> tensorDesc) =>
      withArena((arena) {
        final out0 = arena<Pointer<OrtValue>>();
        checkOrtStatus(this.CreateTensorFromMemory.asFunction<
                Pointer<OrtStatus> Function(
                    Pointer<OrtExternalResourceImporter>,
                    Pointer<OrtExternalMemoryHandle>,
                    Pointer<OrtExternalTensorDescriptor>,
                    Pointer<Pointer<OrtValue>>)>()(
            importer, memHandle, tensorDesc, out0));
        return out0.value;
      });
}
