// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by tool/generate_bindings.dart from the pinned headers.

/// The generated half of the WebAssembly backend.
///
/// Every call here is one the web build does not export. Refusing by name is
/// the whole point: the application compiles, and the limit is reported where
/// it is reached rather than at the import.
///
/// It names nothing native, which is what lets it be the web half of the
/// conditional export in calls.dart.
library;

import '../annotations.dart';
import 'handles.g.dart';
import 'raw_interface.g.dart';
import 'types.dart';

const _why = 'the WebAssembly build exports forty functions of its own rather '
    'than the OrtApi struct, and this is not one of them';

/// Every native-only call, refused.
base mixin GeneratedWasmRawCalls implements OrtRawCalls {
  @override
  @NativeOnly(_why)
  void addCustomOpDomain(
          OrtSessionOptionsPtr options, OrtCustomOpDomainPtr customOpDomain) =>
      unsupportedOnWeb('AddCustomOpDomain', _why);

  @override
  @NativeOnly(_why)
  void addExternalInitializers(
          OrtSessionOptionsPtr options,
          List<String> initializerNames,
          List<OrtValuePtr> initializers,
          int numInitializers) =>
      unsupportedOnWeb('AddExternalInitializers', _why);

  @override
  @NativeOnly(_why)
  void addExternalInitializersFromFilesInMemory(
          OrtSessionOptionsPtr options,
          List<String> externalInitializerFileNames,
          List<String> externalInitializerFileBufferArray,
          List<int> externalInitializerFileLengths,
          int numExternalInitializerFiles) =>
      unsupportedOnWeb('AddExternalInitializersFromFilesInMemory', _why);

  @override
  @NativeOnly(_why)
  void addFreeDimensionOverrideByName(
          OrtSessionOptionsPtr options, String dimName, int dimValue) =>
      unsupportedOnWeb('AddFreeDimensionOverrideByName', _why);

  @override
  @NativeOnly(_why)
  void addGraphToModel(OrtModelPtr model, OrtGraphPtr graph) =>
      unsupportedOnWeb('AddGraphToModel', _why);

  @override
  @NativeOnly(_why)
  void addInitializer(
          OrtSessionOptionsPtr options, String name, OrtValuePtr val) =>
      unsupportedOnWeb('AddInitializer', _why);

  @override
  @NativeOnly(_why)
  void addInitializerToGraph(OrtGraphPtr graph, String name, OrtValuePtr tensor,
          bool dataIsExternal) =>
      unsupportedOnWeb('AddInitializerToGraph', _why);

  @override
  @NativeOnly(_why)
  void addKeyValuePair(OrtKeyValuePairsPtr kvps, String key, String value) =>
      unsupportedOnWeb('AddKeyValuePair', _why);

  @override
  @NativeOnly(_why)
  void addNodeToGraph(OrtGraphPtr graph, OrtNodePtr node) =>
      unsupportedOnWeb('AddNodeToGraph', _why);

  @override
  @NativeOnly(_why)
  void addProperty(OrtCheckpointStatePtr checkpointState, String propertyName,
          int propertyType, OrtPtr propertyValue) =>
      unsupportedOnWeb('AddProperty', _why);

  @override
  @NativeOnly(_why)
  OrtPtr allocatorAlloc(OrtAllocatorPtr ortAllocator, int size) =>
      unsupportedOnWeb('AllocatorAlloc', _why);

  @override
  @NativeOnly(_why)
  void allocatorFree(OrtAllocatorPtr ortAllocator, OrtPtr p) =>
      unsupportedOnWeb('AllocatorFree', _why);

  @override
  @NativeOnly(_why)
  OrtMemoryInfoPtr allocatorGetInfo(OrtAllocatorPtr ortAllocator) =>
      unsupportedOnWeb('AllocatorGetInfo', _why);

  @override
  @NativeOnly(_why)
  OrtKeyValuePairsPtr allocatorGetStats(OrtAllocatorPtr ortAllocator) =>
      unsupportedOnWeb('AllocatorGetStats', _why);

  @override
  @NativeOnly(_why)
  void applyModelToModelEditorSession(
          OrtSessionPtr session, OrtModelPtr model) =>
      unsupportedOnWeb('ApplyModelToModelEditorSession', _why);

  @override
  @NativeOnly(_why)
  void bindOutputToDevice(OrtIoBindingPtr bindingPtr, String name,
          OrtMemoryInfoPtr memInfoPtr) =>
      unsupportedOnWeb('BindOutputToDevice', _why);

  @override
  @NativeOnly(_why)
  bool canImportMemory(
          OrtExternalResourceImporterPtr importer, int handleType) =>
      unsupportedOnWeb('CanImportMemory', _why);

  @override
  @NativeOnly(_why)
  bool canImportSemaphore(OrtExternalResourceImporterPtr importer, int type) =>
      unsupportedOnWeb('CanImportSemaphore', _why);

  @override
  @NativeOnly(_why)
  OrtMapTypeInfoPtr castTypeInfoToMapTypeInfo(OrtTypeInfoPtr typeInfo) =>
      unsupportedOnWeb('CastTypeInfoToMapTypeInfo', _why);

  @override
  @NativeOnly(_why)
  OrtOptionalTypeInfoPtr castTypeInfoToOptionalTypeInfo(
          OrtTypeInfoPtr typeInfo) =>
      unsupportedOnWeb('CastTypeInfoToOptionalTypeInfo', _why);

  @override
  @NativeOnly(_why)
  OrtSequenceTypeInfoPtr castTypeInfoToSequenceTypeInfo(
          OrtTypeInfoPtr typeInfo) =>
      unsupportedOnWeb('CastTypeInfoToSequenceTypeInfo', _why);

  @override
  @NativeOnly(_why)
  OrtTensorTypeAndShapeInfoPtr castTypeInfoToTensorInfo(
          OrtTypeInfoPtr typeInfo) =>
      unsupportedOnWeb('CastTypeInfoToTensorInfo', _why);

  @override
  @NativeOnly(_why)
  OrtSessionOptionsPtr cloneSessionOptions(OrtSessionOptionsPtr inOptions) =>
      unsupportedOnWeb('CloneSessionOptions', _why);

  @override
  @NativeOnly(_why)
  int compareMemoryInfo(OrtMemoryInfoPtr info1, OrtMemoryInfoPtr info2) =>
      unsupportedOnWeb('CompareMemoryInfo', _why);

  @override
  @NativeOnly(_why)
  void compileModel(
          OrtEnvPtr env, OrtModelCompilationOptionsPtr modelOptions) =>
      unsupportedOnWeb('CompileModel', _why);

  @override
  @NativeOnly(_why)
  void copyBufferToParameters(OrtTrainingSessionPtr sess,
          OrtValuePtr parametersBuffer, bool trainableOnly) =>
      unsupportedOnWeb('CopyBufferToParameters', _why);

  @override
  @NativeOnly(_why)
  OrtKernelInfoPtr copyKernelInfo(OrtKernelInfoPtr info) =>
      unsupportedOnWeb('CopyKernelInfo', _why);

  @override
  @NativeOnly(_why)
  void copyParametersToBuffer(OrtTrainingSessionPtr sess,
          OrtValuePtr parametersBuffer, bool trainableOnly) =>
      unsupportedOnWeb('CopyParametersToBuffer', _why);

  @override
  @NativeOnly(_why)
  void copyTensors(
          OrtEnvPtr env,
          List<OrtValuePtr> srcTensors,
          List<OrtValuePtr> dstTensors,
          OrtSyncStreamPtr stream,
          int numTensors) =>
      unsupportedOnWeb('CopyTensors', _why);

  @override
  @NativeOnly(_why)
  OrtAllocatorPtr createAllocator(
          OrtSessionPtr session, OrtMemoryInfoPtr memInfo) =>
      unsupportedOnWeb('CreateAllocator', _why);

  @override
  @NativeOnly(_why)
  void createAndRegisterAllocator(
          OrtEnvPtr env, OrtMemoryInfoPtr memInfo, OrtArenaCfgPtr arenaCfg) =>
      unsupportedOnWeb('CreateAndRegisterAllocator', _why);

  @override
  @NativeOnly(_why)
  void createAndRegisterAllocatorV2(
          OrtEnvPtr env,
          String providerType,
          OrtMemoryInfoPtr memInfo,
          OrtArenaCfgPtr arenaCfg,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      unsupportedOnWeb('CreateAndRegisterAllocatorV2', _why);

  @override
  @NativeOnly(_why)
  OrtArenaCfgPtr createArenaCfg(int maxMem, int arenaExtendStrategy,
          int initialChunkSizeBytes, int maxDeadBytesPerChunk) =>
      unsupportedOnWeb('CreateArenaCfg', _why);

  @override
  @NativeOnly(_why)
  OrtArenaCfgPtr createArenaCfgV2(List<String> arenaConfigKeys,
          List<int> arenaConfigValues, int numKeys) =>
      unsupportedOnWeb('CreateArenaCfgV2', _why);

  @override
  @NativeOnly(_why)
  OrtCANNProviderOptionsPtr createCANNProviderOptions() =>
      unsupportedOnWeb('CreateCANNProviderOptions', _why);

  @override
  @NativeOnly(_why)
  OrtCUDAProviderOptionsV2Ptr createCUDAProviderOptions() =>
      unsupportedOnWeb('CreateCUDAProviderOptions', _why);

  @override
  @NativeOnly(_why)
  OrtMemoryInfoPtr createCpuMemoryInfo(int type, int memType) =>
      unsupportedOnWeb('CreateCpuMemoryInfo', _why);

  @override
  @NativeOnly(_why)
  OrtCustomOpDomainPtr createCustomOpDomain(String domain) =>
      unsupportedOnWeb('CreateCustomOpDomain', _why);

  @override
  @NativeOnly(_why)
  OrtDnnlProviderOptionsPtr createDnnlProviderOptions() =>
      unsupportedOnWeb('CreateDnnlProviderOptions', _why);

  @override
  @NativeOnly(_why)
  OrtEnvPtr createEnv(int logSeverityLevel, String logid) =>
      unsupportedOnWeb('CreateEnv', _why);

  @override
  @NativeOnly(_why)
  OrtEnvPtr createEnvWithCustomLogger(OrtPtr loggingFunction,
          OrtPtr loggerParam, int logSeverityLevel, String logid) =>
      unsupportedOnWeb('CreateEnvWithCustomLogger', _why);

  @override
  @NativeOnly(_why)
  OrtEnvPtr createEnvWithCustomLoggerAndGlobalThreadPools(
          OrtPtr loggingFunction,
          OrtPtr loggerParam,
          int logSeverityLevel,
          String logid,
          OrtThreadingOptionsPtr tpOptions) =>
      unsupportedOnWeb('CreateEnvWithCustomLoggerAndGlobalThreadPools', _why);

  @override
  @NativeOnly(_why)
  OrtEnvPtr createEnvWithGlobalThreadPools(int logSeverityLevel, String logid,
          OrtThreadingOptionsPtr tpOptions) =>
      unsupportedOnWeb('CreateEnvWithGlobalThreadPools', _why);

  @override
  @NativeOnly(_why)
  OrtEnvPtr createEnvWithOptions(OrtEnvCreationOptionsPtr options) =>
      unsupportedOnWeb('CreateEnvWithOptions', _why);

  @override
  @NativeOnly(_why)
  OrtExternalInitializerInfoPtr createExternalInitializerInfo(
          String filepath, int fileOffset, int byteSize) =>
      unsupportedOnWeb('CreateExternalInitializerInfo', _why);

  @override
  @NativeOnly(_why)
  OrtExternalResourceImporterPtr createExternalResourceImporterForDevice(
          OrtEpDevicePtr epDevice) =>
      unsupportedOnWeb('CreateExternalResourceImporterForDevice', _why);

  @override
  @NativeOnly(_why)
  OrtGraphPtr createGraph() => unsupportedOnWeb('CreateGraph', _why);

  @override
  @NativeOnly(_why)
  OrtIoBindingPtr createIoBinding(OrtSessionPtr session) =>
      unsupportedOnWeb('CreateIoBinding', _why);

  @override
  @NativeOnly(_why)
  OrtKeyValuePairsPtr createKeyValuePairs() =>
      unsupportedOnWeb('CreateKeyValuePairs', _why);

  @override
  @NativeOnly(_why)
  OrtLoraAdapterPtr createLoraAdapter(
          String adapterFilePath, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('CreateLoraAdapter', _why);

  @override
  @NativeOnly(_why)
  OrtLoraAdapterPtr createLoraAdapterFromArray(
          OrtPtr bytes, int numBytes, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('CreateLoraAdapterFromArray', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr createMapTypeInfo(
          int mapKeyType, OrtTypeInfoPtr mapValueType) =>
      unsupportedOnWeb('CreateMapTypeInfo', _why);

  @override
  @NativeOnly(_why)
  OrtMemoryInfoPtr createMemoryInfo(
          String name, int type, int id, int memType) =>
      unsupportedOnWeb('CreateMemoryInfo', _why);

  @override
  @NativeOnly(_why)
  OrtMemoryInfoPtr createMemoryInfo_V2(
          String name,
          int deviceType,
          int vendorId,
          int deviceId,
          int memType,
          int alignment,
          int allocatorType) =>
      unsupportedOnWeb('CreateMemoryInfo_V2', _why);

  @override
  @NativeOnly(_why)
  OrtModelPtr createModel(List<String> domainNames, List<int> opsetVersions,
          int opsetEntriesLen) =>
      unsupportedOnWeb('CreateModel', _why);

  @override
  @NativeOnly(_why)
  OrtModelCompilationOptionsPtr createModelCompilationOptionsFromSessionOptions(
          OrtEnvPtr env, OrtSessionOptionsPtr sessionOptions) =>
      unsupportedOnWeb('CreateModelCompilationOptionsFromSessionOptions', _why);

  @override
  @NativeOnly(_why)
  OrtSessionPtr createModelEditorSession(
          OrtEnvPtr env, String modelPath, OrtSessionOptionsPtr options) =>
      unsupportedOnWeb('CreateModelEditorSession', _why);

  @override
  @NativeOnly(_why)
  OrtSessionPtr createModelEditorSessionFromArray(
          OrtEnvPtr env,
          OrtPtr modelData,
          int modelDataLength,
          OrtSessionOptionsPtr options) =>
      unsupportedOnWeb('CreateModelEditorSessionFromArray', _why);

  @override
  @NativeOnly(_why)
  OrtNodePtr createNode(
          String operatorName,
          String domainName,
          String nodeName,
          List<String> inputNames,
          int inputNamesLen,
          List<String> outputNames,
          int outputNamesLen,
          List<OrtOpAttrPtr> attributes,
          int attribsLen) =>
      unsupportedOnWeb('CreateNode', _why);

  @override
  @NativeOnly(_why)
  OrtOpPtr createOp(
          OrtKernelInfoPtr info,
          String opName,
          String domain,
          int version,
          List<String> typeConstraintNames,
          OrtPtr typeConstraintValues,
          int typeConstraintCount,
          List<OrtOpAttrPtr> attrValues,
          int attrCount,
          int inputCount,
          int outputCount) =>
      unsupportedOnWeb('CreateOp', _why);

  @override
  @NativeOnly(_why)
  OrtOpAttrPtr createOpAttr(String name, OrtPtr data, int len, int type) =>
      unsupportedOnWeb('CreateOpAttr', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr createOpaqueValue(String domainName, String typeName,
          OrtPtr dataContainer, int dataContainerSize) =>
      unsupportedOnWeb('CreateOpaqueValue', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr createOptionalTypeInfo(OrtTypeInfoPtr containedType) =>
      unsupportedOnWeb('CreateOptionalTypeInfo', _why);

  @override
  @NativeOnly(_why)
  OrtPrepackedWeightsContainerPtr createPrepackedWeightsContainer() =>
      unsupportedOnWeb('CreatePrepackedWeightsContainer', _why);

  @override
  @NativeOnly(_why)
  OrtROCMProviderOptionsPtr createROCMProviderOptions() =>
      unsupportedOnWeb('CreateROCMProviderOptions', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr createSequenceTypeInfo(OrtTypeInfoPtr sequenceType) =>
      unsupportedOnWeb('CreateSequenceTypeInfo', _why);

  @override
  @NativeOnly(_why)
  OrtSessionPtr createSessionFromArray(OrtEnvPtr env, OrtPtr modelData,
          int modelDataLength, OrtSessionOptionsPtr options) =>
      unsupportedOnWeb('CreateSessionFromArray', _why);

  @override
  @NativeOnly(_why)
  OrtSessionPtr createSessionFromArrayWithPrepackedWeightsContainer(
          OrtEnvPtr env,
          OrtPtr modelData,
          int modelDataLength,
          OrtSessionOptionsPtr options,
          OrtPrepackedWeightsContainerPtr prepackedWeightsContainer) =>
      unsupportedOnWeb(
          'CreateSessionFromArrayWithPrepackedWeightsContainer', _why);

  @override
  @NativeOnly(_why)
  OrtSessionPtr createSessionFromModel(
          OrtEnvPtr env, OrtModelPtr model, OrtSessionOptionsPtr options) =>
      unsupportedOnWeb('CreateSessionFromModel', _why);

  @override
  @NativeOnly(_why)
  OrtSessionPtr createSessionWithPrepackedWeightsContainer(
          OrtEnvPtr env,
          String modelPath,
          OrtSessionOptionsPtr options,
          OrtPrepackedWeightsContainerPtr prepackedWeightsContainer) =>
      unsupportedOnWeb('CreateSessionWithPrepackedWeightsContainer', _why);

  @override
  @NativeOnly(_why)
  OrtAllocatorPtr createSharedAllocator(
          OrtEnvPtr env,
          OrtEpDevicePtr epDevice,
          int memType,
          int allocatorType,
          OrtKeyValuePairsPtr allocatorOptions) =>
      unsupportedOnWeb('CreateSharedAllocator', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr createSparseTensorAsOrtValue(OrtAllocatorPtr allocator,
          List<int> denseShape, int denseShapeLen, int type) =>
      unsupportedOnWeb('CreateSparseTensorAsOrtValue', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr createSparseTensorTypeInfo(
          OrtTensorTypeAndShapeInfoPtr tensorInfo) =>
      unsupportedOnWeb('CreateSparseTensorTypeInfo', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr createSparseTensorWithValuesAsOrtValue(
          OrtMemoryInfoPtr info,
          OrtPtr pData,
          List<int> denseShape,
          int denseShapeLen,
          List<int> valuesShape,
          int valuesShapeLen,
          int type) =>
      unsupportedOnWeb('CreateSparseTensorWithValuesAsOrtValue', _why);

  @override
  @NativeOnly(_why)
  OrtSyncStreamPtr createSyncStreamForEpDevice(
          OrtEpDevicePtr epDevice, OrtKeyValuePairsPtr streamOptions) =>
      unsupportedOnWeb('CreateSyncStreamForEpDevice', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr createTensorAsOrtValue(
          OrtAllocatorPtr allocator, List<int> shape, int shapeLen, int type) =>
      unsupportedOnWeb('CreateTensorAsOrtValue', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr createTensorFromMemory(
          OrtExternalResourceImporterPtr importer,
          OrtExternalMemoryHandlePtr memHandle,
          OrtExternalTensorDescriptorPtr tensorDesc) =>
      unsupportedOnWeb('CreateTensorFromMemory', _why);

  @override
  @NativeOnly(_why)
  OrtTensorRTProviderOptionsV2Ptr createTensorRTProviderOptions() =>
      unsupportedOnWeb('CreateTensorRTProviderOptions', _why);

  @override
  @NativeOnly(_why)
  OrtTensorTypeAndShapeInfoPtr createTensorTypeAndShapeInfo() =>
      unsupportedOnWeb('CreateTensorTypeAndShapeInfo', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr createTensorTypeInfo(
          OrtTensorTypeAndShapeInfoPtr tensorInfo) =>
      unsupportedOnWeb('CreateTensorTypeInfo', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr createTensorWithDataAndDeleterAsOrtValue(
          OrtAllocatorPtr deleter,
          OrtPtr pData,
          int pDataLen,
          List<int> shape,
          int shapeLen,
          int type) =>
      unsupportedOnWeb('CreateTensorWithDataAndDeleterAsOrtValue', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr createTensorWithDataAsOrtValue(
          OrtMemoryInfoPtr info,
          OrtPtr pData,
          int pDataLen,
          List<int> shape,
          int shapeLen,
          int type) =>
      unsupportedOnWeb('CreateTensorWithDataAsOrtValue', _why);

  @override
  @NativeOnly(_why)
  OrtThreadingOptionsPtr createThreadingOptions() =>
      unsupportedOnWeb('CreateThreadingOptions', _why);

  @override
  @NativeOnly(_why)
  OrtTrainingSessionPtr createTrainingSession(
          OrtEnvPtr env,
          OrtSessionOptionsPtr options,
          OrtCheckpointStatePtr checkpointState,
          String trainModelPath,
          String evalModelPath,
          String optimizerModelPath) =>
      unsupportedOnWeb('CreateTrainingSession', _why);

  @override
  @NativeOnly(_why)
  OrtTrainingSessionPtr createTrainingSessionFromBuffer(
          OrtEnvPtr env,
          OrtSessionOptionsPtr options,
          OrtCheckpointStatePtr checkpointState,
          OrtPtr trainModelData,
          int trainDataLength,
          OrtPtr evalModelData,
          int evalDataLength,
          OrtPtr optimModelData,
          int optimDataLength) =>
      unsupportedOnWeb('CreateTrainingSessionFromBuffer', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr createValue(
          List<OrtValuePtr> in_, int numValues, int valueType) =>
      unsupportedOnWeb('CreateValue', _why);

  @override
  @NativeOnly(_why)
  OrtValueInfoPtr createValueInfo(String name, OrtTypeInfoPtr typeInfo) =>
      unsupportedOnWeb('CreateValueInfo', _why);

  @override
  @NativeOnly(_why)
  void customOpDomain_Add(
          OrtCustomOpDomainPtr customOpDomain, OrtCustomOpPtr op) =>
      unsupportedOnWeb('CustomOpDomain_Add', _why);

  @override
  @NativeOnly(_why)
  void deinitGraphicsInteropForEpDevice(OrtEpDevicePtr epDevice) =>
      unsupportedOnWeb('DeinitGraphicsInteropForEpDevice', _why);

  @override
  @NativeOnly(_why)
  int deviceEpIncompatibilityDetails_GetErrorCode(
          OrtDeviceEpIncompatibilityDetailsPtr details) =>
      unsupportedOnWeb('DeviceEpIncompatibilityDetails_GetErrorCode', _why);

  @override
  @NativeOnly(_why)
  String deviceEpIncompatibilityDetails_GetNotes(
          OrtDeviceEpIncompatibilityDetailsPtr details) =>
      unsupportedOnWeb('DeviceEpIncompatibilityDetails_GetNotes', _why);

  @override
  @NativeOnly(_why)
  int deviceEpIncompatibilityDetails_GetReasonsBitmask(
          OrtDeviceEpIncompatibilityDetailsPtr details) =>
      unsupportedOnWeb(
          'DeviceEpIncompatibilityDetails_GetReasonsBitmask', _why);

  @override
  @NativeOnly(_why)
  void disableCpuMemArena(OrtSessionOptionsPtr options) =>
      unsupportedOnWeb('DisableCpuMemArena', _why);

  @override
  @NativeOnly(_why)
  void disableMemPattern(OrtSessionOptionsPtr options) =>
      unsupportedOnWeb('DisableMemPattern', _why);

  @override
  @NativeOnly(_why)
  void disablePerSessionThreads(OrtSessionOptionsPtr options) =>
      unsupportedOnWeb('DisablePerSessionThreads', _why);

  @override
  @NativeOnly(_why)
  void disableProfiling(OrtSessionOptionsPtr options) =>
      unsupportedOnWeb('DisableProfiling', _why);

  @override
  @NativeOnly(_why)
  void disableTelemetryEvents(OrtEnvPtr env) =>
      unsupportedOnWeb('DisableTelemetryEvents', _why);

  @override
  @NativeOnly(_why)
  void enableCpuMemArena(OrtSessionOptionsPtr options) =>
      unsupportedOnWeb('EnableCpuMemArena', _why);

  @override
  @NativeOnly(_why)
  void enableMemPattern(OrtSessionOptionsPtr options) =>
      unsupportedOnWeb('EnableMemPattern', _why);

  @override
  @NativeOnly(_why)
  void enableOrtCustomOps(OrtSessionOptionsPtr options) =>
      unsupportedOnWeb('EnableOrtCustomOps', _why);

  @override
  @NativeOnly(_why)
  void enableTelemetryEvents(OrtEnvPtr env) =>
      unsupportedOnWeb('EnableTelemetryEvents', _why);

  @override
  @NativeOnly(_why)
  String epAssignedNode_GetDomain(OrtEpAssignedNodePtr epNode) =>
      unsupportedOnWeb('EpAssignedNode_GetDomain', _why);

  @override
  @NativeOnly(_why)
  String epAssignedNode_GetName(OrtEpAssignedNodePtr epNode) =>
      unsupportedOnWeb('EpAssignedNode_GetName', _why);

  @override
  @NativeOnly(_why)
  String epAssignedNode_GetOperatorType(OrtEpAssignedNodePtr epNode) =>
      unsupportedOnWeb('EpAssignedNode_GetOperatorType', _why);

  @override
  @NativeOnly(_why)
  String epAssignedSubgraph_GetEpName(OrtEpAssignedSubgraphPtr epSubgraph) =>
      unsupportedOnWeb('EpAssignedSubgraph_GetEpName', _why);

  @override
  @NativeOnly(_why)
  List<OrtEpAssignedNodePtr> epAssignedSubgraph_GetNodes(
          OrtEpAssignedSubgraphPtr epSubgraph) =>
      unsupportedOnWeb('EpAssignedSubgraph_GetNodes', _why);

  @override
  @NativeOnly(_why)
  void evalStep(
          OrtTrainingSessionPtr sess,
          OrtRunOptionsPtr runOptions,
          int inputsLen,
          List<OrtValuePtr> inputs,
          int outputsLen,
          List<OrtValuePtr> outputs) =>
      unsupportedOnWeb('EvalStep', _why);

  @override
  @NativeOnly(_why)
  void exportModelForInferencing(
          OrtTrainingSessionPtr sess,
          String inferenceModelPath,
          int graphOutputsLen,
          List<String> graphOutputNames) =>
      unsupportedOnWeb('ExportModelForInferencing', _why);

  @override
  @NativeOnly(_why)
  void fillSparseTensorBlockSparse(
          OrtValuePtr ortValue,
          OrtMemoryInfoPtr dataMemInfo,
          List<int> valuesShape,
          int valuesShapeLen,
          OrtPtr values,
          List<int> indicesShapeData,
          int indicesShapeLen,
          List<int> indicesData) =>
      unsupportedOnWeb('FillSparseTensorBlockSparse', _why);

  @override
  @NativeOnly(_why)
  void fillSparseTensorCoo(
          OrtValuePtr ortValue,
          OrtMemoryInfoPtr dataMemInfo,
          List<int> valuesShape,
          int valuesShapeLen,
          OrtPtr values,
          List<int> indicesData,
          int indicesNum) =>
      unsupportedOnWeb('FillSparseTensorCoo', _why);

  @override
  @NativeOnly(_why)
  void fillSparseTensorCsr(
          OrtValuePtr ortValue,
          OrtMemoryInfoPtr dataMemInfo,
          List<int> valuesShape,
          int valuesShapeLen,
          OrtPtr values,
          List<int> innerIndicesData,
          int innerIndicesNum,
          List<int> outerIndicesData,
          int outerIndicesNum) =>
      unsupportedOnWeb('FillSparseTensorCsr', _why);

  @override
  @NativeOnly(_why)
  void fillStringTensor(OrtValuePtr value, List<String> s, int sLen) =>
      unsupportedOnWeb('FillStringTensor', _why);

  @override
  @NativeOnly(_why)
  void fillStringTensorElement(OrtValuePtr value, String s, int index) =>
      unsupportedOnWeb('FillStringTensorElement', _why);

  @override
  @NativeOnly(_why)
  void finalizeModelEditorSession(
          OrtSessionPtr session,
          OrtSessionOptionsPtr options,
          OrtPrepackedWeightsContainerPtr prepackedWeightsContainer) =>
      unsupportedOnWeb('FinalizeModelEditorSession', _why);

  @override
  @NativeOnly(_why)
  OrtAllocatorPtr getAllocatorWithDefaultOptions() =>
      unsupportedOnWeb('GetAllocatorWithDefaultOptions', _why);

  @override
  @NativeOnly(_why)
  String getCANNProviderOptionsAsString(
          OrtCANNProviderOptionsPtr cannOptions, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('GetCANNProviderOptionsAsString', _why);

  @override
  @NativeOnly(_why)
  String getCUDAProviderOptionsAsString(
          OrtCUDAProviderOptionsV2Ptr cudaOptions, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('GetCUDAProviderOptionsAsString', _why);

  @override
  @NativeOnly(_why)
  OrtPtr getCUDAProviderOptionsByName(
          OrtCUDAProviderOptionsV2Ptr cudaOptions, String key) =>
      unsupportedOnWeb('GetCUDAProviderOptionsByName', _why);

  @override
  @NativeOnly(_why)
  String getCompatibilityInfoFromModel(
          String modelPath, String epType, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('GetCompatibilityInfoFromModel', _why);

  @override
  @NativeOnly(_why)
  String getCompatibilityInfoFromModelBytes(OrtPtr modelData,
          int modelDataLength, String epType, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('GetCompatibilityInfoFromModelBytes', _why);

  @override
  @NativeOnly(_why)
  int getCurrentGpuDeviceId() =>
      unsupportedOnWeb('GetCurrentGpuDeviceId', _why);

  @override
  @NativeOnly(_why)
  (String denotation, int len) getDenotationFromTypeInfo(
          OrtTypeInfoPtr typeInfo) =>
      unsupportedOnWeb('GetDenotationFromTypeInfo', _why);

  @override
  @NativeOnly(_why)
  List<int> getDimensions(
          OrtTensorTypeAndShapeInfoPtr info, int dimValuesLength) =>
      unsupportedOnWeb('GetDimensions', _why);

  @override
  @NativeOnly(_why)
  int getDimensionsCount(OrtTensorTypeAndShapeInfoPtr info) =>
      unsupportedOnWeb('GetDimensionsCount', _why);

  @override
  @NativeOnly(_why)
  String getDnnlProviderOptionsAsString(
          OrtDnnlProviderOptionsPtr dnnlOptions, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('GetDnnlProviderOptionsAsString', _why);

  @override
  @NativeOnly(_why)
  List<OrtEpDevicePtr> getEpDevices(OrtEnvPtr env) =>
      unsupportedOnWeb('GetEpDevices', _why);

  @override
  @NativeOnly(_why)
  OrtPtr getExecutionProviderApi(String providerName, int version) =>
      unsupportedOnWeb('GetExecutionProviderApi', _why);

  @override
  @NativeOnly(_why)
  OrtDeviceEpIncompatibilityDetailsPtr
      getHardwareDeviceEpIncompatibilityDetails(
              OrtEnvPtr env, String epName, OrtHardwareDevicePtr hw) =>
          unsupportedOnWeb('GetHardwareDeviceEpIncompatibilityDetails', _why);

  @override
  @NativeOnly(_why)
  List<OrtHardwareDevicePtr> getHardwareDevices(
          OrtEnvPtr env, int numDevices) =>
      unsupportedOnWeb('GetHardwareDevices', _why);

  @override
  @NativeOnly(_why)
  (List<String> keys, List<String> values) getKeyValuePairs(
          OrtKeyValuePairsPtr kvps) =>
      unsupportedOnWeb('GetKeyValuePairs', _why);

  @override
  @NativeOnly(_why)
  double getLearningRate(OrtTrainingSessionPtr sess) =>
      unsupportedOnWeb('GetLearningRate', _why);

  @override
  @NativeOnly(_why)
  int getMapKeyType(OrtMapTypeInfoPtr mapTypeInfo) =>
      unsupportedOnWeb('GetMapKeyType', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr getMapValueType(OrtMapTypeInfoPtr mapTypeInfo) =>
      unsupportedOnWeb('GetMapValueType', _why);

  @override
  @NativeOnly(_why)
  int getMemPatternEnabled(OrtSessionOptionsPtr options) =>
      unsupportedOnWeb('GetMemPatternEnabled', _why);

  @override
  @NativeOnly(_why)
  int getModelCompatibilityForEpDevices(List<OrtEpDevicePtr> epDevices,
          int numEpDevices, String compatibilityInfo) =>
      unsupportedOnWeb('GetModelCompatibilityForEpDevices', _why);

  @override
  @NativeOnly(_why)
  int getNumHardwareDevices(OrtEnvPtr env) =>
      unsupportedOnWeb('GetNumHardwareDevices', _why);

  @override
  @NativeOnly(_why)
  int getOnnxTypeFromTypeInfo(OrtTypeInfoPtr typeInfo) =>
      unsupportedOnWeb('GetOnnxTypeFromTypeInfo', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr getOptionalContainedTypeInfo(
          OrtOptionalTypeInfoPtr optionalTypeInfo) =>
      unsupportedOnWeb('GetOptionalContainedTypeInfo', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr getParameter(OrtCheckpointStatePtr checkpointState,
          String parameterName, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('GetParameter', _why);

  @override
  @NativeOnly(_why)
  OrtTensorTypeAndShapeInfoPtr getParameterTypeAndShape(
          OrtCheckpointStatePtr checkpointState, String parameterName) =>
      unsupportedOnWeb('GetParameterTypeAndShape', _why);

  @override
  @NativeOnly(_why)
  int getParametersSize(OrtTrainingSessionPtr sess, bool trainableOnly) =>
      unsupportedOnWeb('GetParametersSize', _why);

  @override
  @NativeOnly(_why)
  (int propertyType, OrtPtr propertyValue) getProperty(
          OrtCheckpointStatePtr checkpointState,
          String propertyName,
          OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('GetProperty', _why);

  @override
  @NativeOnly(_why)
  String getROCMProviderOptionsAsString(
          OrtROCMProviderOptionsPtr rocmOptions, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('GetROCMProviderOptionsAsString', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr getSequenceElementType(
          OrtSequenceTypeInfoPtr sequenceTypeInfo) =>
      unsupportedOnWeb('GetSequenceElementType', _why);

  @override
  @NativeOnly(_why)
  String getSessionConfigEntry(
          OrtSessionOptionsPtr options, String configKey) =>
      unsupportedOnWeb('GetSessionConfigEntry', _why);

  @override
  @NativeOnly(_why)
  int getSessionExecutionMode(OrtSessionOptionsPtr options) =>
      unsupportedOnWeb('GetSessionExecutionMode', _why);

  @override
  @NativeOnly(_why)
  OrtKeyValuePairsPtr getSessionOptionsConfigEntries(
          OrtSessionOptionsPtr options) =>
      unsupportedOnWeb('GetSessionOptionsConfigEntries', _why);

  @override
  @NativeOnly(_why)
  OrtAllocatorPtr getSharedAllocator(OrtEnvPtr env, OrtMemoryInfoPtr memInfo) =>
      unsupportedOnWeb('GetSharedAllocator', _why);

  @override
  @NativeOnly(_why)
  int getSparseTensorFormat(OrtValuePtr ortValue) =>
      unsupportedOnWeb('GetSparseTensorFormat', _why);

  @override
  @NativeOnly(_why)
  (int numIndices, OrtPtr indices) getSparseTensorIndices(
          OrtValuePtr ortValue, int indicesFormat) =>
      unsupportedOnWeb('GetSparseTensorIndices', _why);

  @override
  @NativeOnly(_why)
  OrtTensorTypeAndShapeInfoPtr getSparseTensorIndicesTypeShape(
          OrtValuePtr ortValue, int indicesFormat) =>
      unsupportedOnWeb('GetSparseTensorIndicesTypeShape', _why);

  @override
  @NativeOnly(_why)
  OrtPtr getSparseTensorValues(OrtValuePtr ortValue) =>
      unsupportedOnWeb('GetSparseTensorValues', _why);

  @override
  @NativeOnly(_why)
  OrtTensorTypeAndShapeInfoPtr getSparseTensorValuesTypeAndShape(
          OrtValuePtr ortValue) =>
      unsupportedOnWeb('GetSparseTensorValuesTypeAndShape', _why);

  @override
  @NativeOnly(_why)
  int getStringTensorDataLength(OrtValuePtr value) =>
      unsupportedOnWeb('GetStringTensorDataLength', _why);

  @override
  @NativeOnly(_why)
  int getStringTensorElementLength(OrtValuePtr value, int index) =>
      unsupportedOnWeb('GetStringTensorElementLength', _why);

  @override
  @NativeOnly(_why)
  OrtPtr getTensorData(OrtValuePtr value) =>
      unsupportedOnWeb('GetTensorData', _why);

  @override
  @NativeOnly(_why)
  int getTensorElementType(OrtTensorTypeAndShapeInfoPtr info) =>
      unsupportedOnWeb('GetTensorElementType', _why);

  @override
  @NativeOnly(_why)
  (int elemType, List<int> shapeData) getTensorElementTypeAndShapeDataReference(
          OrtValuePtr value) =>
      unsupportedOnWeb('GetTensorElementTypeAndShapeDataReference', _why);

  @override
  @NativeOnly(_why)
  OrtMemoryInfoPtr getTensorMemoryInfo(OrtValuePtr value) =>
      unsupportedOnWeb('GetTensorMemoryInfo', _why);

  @override
  @NativeOnly(_why)
  OrtPtr getTensorMutableData(OrtValuePtr value) =>
      unsupportedOnWeb('GetTensorMutableData', _why);

  @override
  @NativeOnly(_why)
  String getTensorRTProviderOptionsAsString(
          OrtTensorRTProviderOptionsV2Ptr tensorrtOptions,
          OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('GetTensorRTProviderOptionsAsString', _why);

  @override
  @NativeOnly(_why)
  OrtPtr getTensorRTProviderOptionsByName(
          OrtTensorRTProviderOptionsV2Ptr tensorrtOptions, String key) =>
      unsupportedOnWeb('GetTensorRTProviderOptionsByName', _why);

  @override
  @NativeOnly(_why)
  int getTensorShapeElementCount(OrtTensorTypeAndShapeInfoPtr info) =>
      unsupportedOnWeb('GetTensorShapeElementCount', _why);

  @override
  @NativeOnly(_why)
  int getTensorSizeInBytes(OrtValuePtr ortValue) =>
      unsupportedOnWeb('GetTensorSizeInBytes', _why);

  @override
  @NativeOnly(_why)
  OrtTensorTypeAndShapeInfoPtr getTensorTypeAndShape(OrtValuePtr value) =>
      unsupportedOnWeb('GetTensorTypeAndShape', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr getTypeInfo(OrtValuePtr value) =>
      unsupportedOnWeb('GetTypeInfo', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr getValue(
          OrtValuePtr value, int index, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('GetValue', _why);

  @override
  @NativeOnly(_why)
  int getValueCount(OrtValuePtr value) =>
      unsupportedOnWeb('GetValueCount', _why);

  @override
  @NativeOnly(_why)
  String getValueInfoName(OrtValueInfoPtr valueInfo) =>
      unsupportedOnWeb('GetValueInfoName', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr getValueInfoTypeInfo(OrtValueInfoPtr valueInfo) =>
      unsupportedOnWeb('GetValueInfoTypeInfo', _why);

  @override
  @NativeOnly(_why)
  int getValueType(OrtValuePtr value) => unsupportedOnWeb('GetValueType', _why);

  @override
  @NativeOnly(_why)
  OrtGraphPtr graph_GetGraphView(
          OrtGraphPtr srcGraph, List<OrtNodePtr> nodes, int numNodes) =>
      unsupportedOnWeb('Graph_GetGraphView', _why);

  @override
  @NativeOnly(_why)
  List<OrtValueInfoPtr> graph_GetInitializers(
          OrtGraphPtr graph, int numInitializers) =>
      unsupportedOnWeb('Graph_GetInitializers', _why);

  @override
  @NativeOnly(_why)
  List<OrtValueInfoPtr> graph_GetInputs(OrtGraphPtr graph, int numInputs) =>
      unsupportedOnWeb('Graph_GetInputs', _why);

  @override
  @NativeOnly(_why)
  OrtModelMetadataPtr graph_GetModelMetadata(OrtGraphPtr graph) =>
      unsupportedOnWeb('Graph_GetModelMetadata', _why);

  @override
  @NativeOnly(_why)
  String graph_GetModelPath(OrtGraphPtr graph) =>
      unsupportedOnWeb('Graph_GetModelPath', _why);

  @override
  @NativeOnly(_why)
  String graph_GetName(OrtGraphPtr graph) =>
      unsupportedOnWeb('Graph_GetName', _why);

  @override
  @NativeOnly(_why)
  List<OrtNodePtr> graph_GetNodes(OrtGraphPtr graph, int numNodes) =>
      unsupportedOnWeb('Graph_GetNodes', _why);

  @override
  @NativeOnly(_why)
  int graph_GetNumInitializers(OrtGraphPtr graph) =>
      unsupportedOnWeb('Graph_GetNumInitializers', _why);

  @override
  @NativeOnly(_why)
  int graph_GetNumInputs(OrtGraphPtr graph) =>
      unsupportedOnWeb('Graph_GetNumInputs', _why);

  @override
  @NativeOnly(_why)
  int graph_GetNumNodes(OrtGraphPtr graph) =>
      unsupportedOnWeb('Graph_GetNumNodes', _why);

  @override
  @NativeOnly(_why)
  int graph_GetNumOperatorSets(OrtGraphPtr graph) =>
      unsupportedOnWeb('Graph_GetNumOperatorSets', _why);

  @override
  @NativeOnly(_why)
  int graph_GetNumOutputs(OrtGraphPtr graph) =>
      unsupportedOnWeb('Graph_GetNumOutputs', _why);

  @override
  @NativeOnly(_why)
  int graph_GetOnnxIRVersion(OrtGraphPtr graph) =>
      unsupportedOnWeb('Graph_GetOnnxIRVersion', _why);

  @override
  @NativeOnly(_why)
  (List<String> domains, List<int> opsetVersions) graph_GetOperatorSets(
          OrtGraphPtr graph, int numOperatorSets) =>
      unsupportedOnWeb('Graph_GetOperatorSets', _why);

  @override
  @NativeOnly(_why)
  List<OrtValueInfoPtr> graph_GetOutputs(OrtGraphPtr graph, int numOutputs) =>
      unsupportedOnWeb('Graph_GetOutputs', _why);

  @override
  @NativeOnly(_why)
  OrtNodePtr graph_GetParentNode(OrtGraphPtr graph) =>
      unsupportedOnWeb('Graph_GetParentNode', _why);

  @override
  @NativeOnly(_why)
  int hasSessionConfigEntry(OrtSessionOptionsPtr options, String configKey) =>
      unsupportedOnWeb('HasSessionConfigEntry', _why);

  @override
  @NativeOnly(_why)
  int hasValue(OrtValuePtr value) => unsupportedOnWeb('HasValue', _why);

  @override
  @NativeOnly(_why)
  OrtExternalMemoryHandlePtr importMemory(
          OrtExternalResourceImporterPtr importer,
          OrtExternalMemoryDescriptorPtr desc) =>
      unsupportedOnWeb('ImportMemory', _why);

  @override
  @NativeOnly(_why)
  OrtExternalSemaphoreHandlePtr importSemaphore(
          OrtExternalResourceImporterPtr importer,
          OrtExternalSemaphoreDescriptorPtr desc) =>
      unsupportedOnWeb('ImportSemaphore', _why);

  @override
  @NativeOnly(_why)
  void initGraphicsInteropForEpDevice(
          OrtEpDevicePtr epDevice, OrtGraphicsInteropConfigPtr config) =>
      unsupportedOnWeb('InitGraphicsInteropForEpDevice', _why);

  @override
  @NativeOnly(_why)
  void invokeOp(
          OrtKernelContextPtr context,
          OrtOpPtr ortOp,
          List<OrtValuePtr> inputValues,
          int inputCount,
          List<OrtValuePtr> outputValues,
          int outputCount) =>
      unsupportedOnWeb('InvokeOp', _why);

  @override
  @NativeOnly(_why)
  int isSparseTensor(OrtValuePtr value) =>
      unsupportedOnWeb('IsSparseTensor', _why);

  @override
  @NativeOnly(_why)
  int isTensor(OrtValuePtr value) => unsupportedOnWeb('IsTensor', _why);

  @override
  @NativeOnly(_why)
  OrtAllocatorPtr kernelContext_GetAllocator(
          OrtKernelContextPtr context, OrtMemoryInfoPtr memInfo) =>
      unsupportedOnWeb('KernelContext_GetAllocator', _why);

  @override
  @NativeOnly(_why)
  OrtPtr kernelContext_GetGPUComputeStream(OrtKernelContextPtr context) =>
      unsupportedOnWeb('KernelContext_GetGPUComputeStream', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr kernelContext_GetInput(OrtKernelContextPtr context, int index) =>
      unsupportedOnWeb('KernelContext_GetInput', _why);

  @override
  @NativeOnly(_why)
  int kernelContext_GetInputCount(OrtKernelContextPtr context) =>
      unsupportedOnWeb('KernelContext_GetInputCount', _why);

  @override
  @NativeOnly(_why)
  OrtLoggerPtr kernelContext_GetLogger(OrtKernelContextPtr context) =>
      unsupportedOnWeb('KernelContext_GetLogger', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr kernelContext_GetOutput(OrtKernelContextPtr context, int index,
          List<int> dimValues, int dimCount) =>
      unsupportedOnWeb('KernelContext_GetOutput', _why);

  @override
  @NativeOnly(_why)
  int kernelContext_GetOutputCount(OrtKernelContextPtr context) =>
      unsupportedOnWeb('KernelContext_GetOutputCount', _why);

  @override
  @NativeOnly(_why)
  OrtPtr kernelContext_GetResource(
          OrtKernelContextPtr context, int resourceVersion, int resourceId) =>
      unsupportedOnWeb('KernelContext_GetResource', _why);

  @override
  @NativeOnly(_why)
  OrtPtr kernelContext_GetScratchBuffer(OrtKernelContextPtr context,
          OrtMemoryInfoPtr memInfo, int countOrBytes) =>
      unsupportedOnWeb('KernelContext_GetScratchBuffer', _why);

  @override
  @NativeOnly(_why)
  OrtSyncStreamPtr kernelContext_GetSyncStream(OrtKernelContextPtr context) =>
      unsupportedOnWeb('KernelContext_GetSyncStream', _why);

  @override
  @NativeOnly(_why)
  OrtAllocatorPtr kernelInfoGetAllocator(OrtKernelInfoPtr info, int memType) =>
      unsupportedOnWeb('KernelInfoGetAllocator', _why);

  @override
  @NativeOnly(_why)
  List<double> kernelInfoGetAttributeArray_float(
          OrtKernelInfoPtr info, String name) =>
      unsupportedOnWeb('KernelInfoGetAttributeArray_float', _why);

  @override
  @NativeOnly(_why)
  List<int> kernelInfoGetAttributeArray_int64(
          OrtKernelInfoPtr info, String name) =>
      unsupportedOnWeb('KernelInfoGetAttributeArray_int64', _why);

  @override
  @NativeOnly(_why)
  List<String> kernelInfoGetAttributeArray_string(
          OrtKernelInfoPtr info, String name, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('KernelInfoGetAttributeArray_string', _why);

  @override
  @NativeOnly(_why)
  double kernelInfoGetAttribute_float(OrtKernelInfoPtr info, String name) =>
      unsupportedOnWeb('KernelInfoGetAttribute_float', _why);

  @override
  @NativeOnly(_why)
  int kernelInfoGetAttribute_int64(OrtKernelInfoPtr info, String name) =>
      unsupportedOnWeb('KernelInfoGetAttribute_int64', _why);

  @override
  @NativeOnly(_why)
  String kernelInfoGetAttribute_string(OrtKernelInfoPtr info, String name) =>
      unsupportedOnWeb('KernelInfoGetAttribute_string', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr kernelInfoGetAttribute_tensor(
          OrtKernelInfoPtr info, String name, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('KernelInfoGetAttribute_tensor', _why);

  @override
  @NativeOnly(_why)
  (int isConstant, OrtValuePtr out_) kernelInfoGetConstantInput_tensor(
          OrtKernelInfoPtr info, int index) =>
      unsupportedOnWeb('KernelInfoGetConstantInput_tensor', _why);

  @override
  @NativeOnly(_why)
  OrtKeyValuePairsPtr kernelInfo_GetConfigEntries(OrtKernelInfoPtr info) =>
      unsupportedOnWeb('KernelInfo_GetConfigEntries', _why);

  @override
  @NativeOnly(_why)
  int kernelInfo_GetInputCount(OrtKernelInfoPtr info) =>
      unsupportedOnWeb('KernelInfo_GetInputCount', _why);

  @override
  @NativeOnly(_why)
  String kernelInfo_GetInputName(OrtKernelInfoPtr info, int index) =>
      unsupportedOnWeb('KernelInfo_GetInputName', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr kernelInfo_GetInputTypeInfo(
          OrtKernelInfoPtr info, int index) =>
      unsupportedOnWeb('KernelInfo_GetInputTypeInfo', _why);

  @override
  @NativeOnly(_why)
  OrtLoggerPtr kernelInfo_GetLogger(OrtKernelInfoPtr info) =>
      unsupportedOnWeb('KernelInfo_GetLogger', _why);

  @override
  @NativeOnly(_why)
  String kernelInfo_GetNodeName(OrtKernelInfoPtr info) =>
      unsupportedOnWeb('KernelInfo_GetNodeName', _why);

  @override
  @NativeOnly(_why)
  String kernelInfo_GetOperatorDomain(OrtKernelInfoPtr info) =>
      unsupportedOnWeb('KernelInfo_GetOperatorDomain', _why);

  @override
  @NativeOnly(_why)
  int kernelInfo_GetOperatorSinceVersion(OrtKernelInfoPtr info) =>
      unsupportedOnWeb('KernelInfo_GetOperatorSinceVersion', _why);

  @override
  @NativeOnly(_why)
  String kernelInfo_GetOperatorType(OrtKernelInfoPtr info) =>
      unsupportedOnWeb('KernelInfo_GetOperatorType', _why);

  @override
  @NativeOnly(_why)
  int kernelInfo_GetOutputCount(OrtKernelInfoPtr info) =>
      unsupportedOnWeb('KernelInfo_GetOutputCount', _why);

  @override
  @NativeOnly(_why)
  String kernelInfo_GetOutputName(OrtKernelInfoPtr info, int index) =>
      unsupportedOnWeb('KernelInfo_GetOutputName', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr kernelInfo_GetOutputTypeInfo(
          OrtKernelInfoPtr info, int index) =>
      unsupportedOnWeb('KernelInfo_GetOutputTypeInfo', _why);

  @override
  @NativeOnly(_why)
  void lazyResetGrad(OrtTrainingSessionPtr session) =>
      unsupportedOnWeb('LazyResetGrad', _why);

  @override
  @NativeOnly(_why)
  OrtCheckpointStatePtr loadCheckpoint(String checkpointPath) =>
      unsupportedOnWeb('LoadCheckpoint', _why);

  @override
  @NativeOnly(_why)
  OrtCheckpointStatePtr loadCheckpointFromBuffer(
          OrtPtr checkpointBuffer, int numBytes) =>
      unsupportedOnWeb('LoadCheckpointFromBuffer', _why);

  @override
  @NativeOnly(_why)
  int logger_GetLoggingSeverityLevel(OrtLoggerPtr logger) =>
      unsupportedOnWeb('Logger_GetLoggingSeverityLevel', _why);

  @override
  @NativeOnly(_why)
  void logger_LogMessage(OrtLoggerPtr logger, int logSeverityLevel,
          String message, String filePath, int lineNumber, String funcName) =>
      unsupportedOnWeb('Logger_LogMessage', _why);

  @override
  @NativeOnly(_why)
  int memoryInfoGetDeviceType(OrtMemoryInfoPtr ptr) =>
      unsupportedOnWeb('MemoryInfoGetDeviceType', _why);

  @override
  @NativeOnly(_why)
  int memoryInfoGetId(OrtMemoryInfoPtr ptr) =>
      unsupportedOnWeb('MemoryInfoGetId', _why);

  @override
  @NativeOnly(_why)
  int memoryInfoGetMemType(OrtMemoryInfoPtr ptr) =>
      unsupportedOnWeb('MemoryInfoGetMemType', _why);

  @override
  @NativeOnly(_why)
  String memoryInfoGetName(OrtMemoryInfoPtr ptr) =>
      unsupportedOnWeb('MemoryInfoGetName', _why);

  @override
  @NativeOnly(_why)
  int memoryInfoGetType(OrtMemoryInfoPtr ptr) =>
      unsupportedOnWeb('MemoryInfoGetType', _why);

  @override
  @NativeOnly(_why)
  void modelCompilationOptions_SetEpContextBinaryInformation(
          OrtModelCompilationOptionsPtr modelCompileOptions,
          String outputDirectory,
          String modelName) =>
      unsupportedOnWeb(
          'ModelCompilationOptions_SetEpContextBinaryInformation', _why);

  @override
  @NativeOnly(_why)
  void modelCompilationOptions_SetEpContextEmbedMode(
          OrtModelCompilationOptionsPtr modelCompileOptions,
          bool embedEpContextInModel) =>
      unsupportedOnWeb('ModelCompilationOptions_SetEpContextEmbedMode', _why);

  @override
  @NativeOnly(_why)
  void modelCompilationOptions_SetFlags(
          OrtModelCompilationOptionsPtr modelCompileOptions, int flags) =>
      unsupportedOnWeb('ModelCompilationOptions_SetFlags', _why);

  @override
  @NativeOnly(_why)
  void modelCompilationOptions_SetGraphOptimizationLevel(
          OrtModelCompilationOptionsPtr modelCompileOptions,
          int graphOptimizationLevel) =>
      unsupportedOnWeb(
          'ModelCompilationOptions_SetGraphOptimizationLevel', _why);

  @override
  @NativeOnly(_why)
  void modelCompilationOptions_SetInputModel(
          OrtModelCompilationOptionsPtr modelCompileOptions,
          OrtModelPtr model) =>
      unsupportedOnWeb('ModelCompilationOptions_SetInputModel', _why);

  @override
  @NativeOnly(_why)
  void modelCompilationOptions_SetInputModelFromBuffer(
          OrtModelCompilationOptionsPtr modelCompileOptions,
          OrtPtr inputModelData,
          int inputModelDataSize) =>
      unsupportedOnWeb('ModelCompilationOptions_SetInputModelFromBuffer', _why);

  @override
  @NativeOnly(_why)
  void modelCompilationOptions_SetInputModelPath(
          OrtModelCompilationOptionsPtr modelCompileOptions,
          String inputModelPath) =>
      unsupportedOnWeb('ModelCompilationOptions_SetInputModelPath', _why);

  @override
  @NativeOnly(_why)
  List<OrtPtr> modelCompilationOptions_SetOutputModelBuffer(
          OrtModelCompilationOptionsPtr modelCompileOptions,
          OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('ModelCompilationOptions_SetOutputModelBuffer', _why);

  @override
  @NativeOnly(_why)
  void modelCompilationOptions_SetOutputModelExternalInitializersFile(
          OrtModelCompilationOptionsPtr modelCompileOptions,
          String externalInitializersFilePath,
          int externalInitializersSizeThreshold) =>
      unsupportedOnWeb(
          'ModelCompilationOptions_SetOutputModelExternalInitializersFile',
          _why);

  @override
  @NativeOnly(_why)
  void modelCompilationOptions_SetOutputModelGetInitializerLocationFunc(
          OrtModelCompilationOptionsPtr modelCompileOptions,
          OrtPtr getInitializerLocationFunc,
          OrtPtr state) =>
      unsupportedOnWeb(
          'ModelCompilationOptions_SetOutputModelGetInitializerLocationFunc',
          _why);

  @override
  @NativeOnly(_why)
  void modelCompilationOptions_SetOutputModelPath(
          OrtModelCompilationOptionsPtr modelCompileOptions,
          String outputModelPath) =>
      unsupportedOnWeb('ModelCompilationOptions_SetOutputModelPath', _why);

  @override
  @NativeOnly(_why)
  void modelCompilationOptions_SetOutputModelWriteFunc(
          OrtModelCompilationOptionsPtr modelCompileOptions,
          OrtPtr writeFunc,
          OrtPtr state) =>
      unsupportedOnWeb('ModelCompilationOptions_SetOutputModelWriteFunc', _why);

  @override
  @NativeOnly(_why)
  void modelCompilationOptions_SetWeightlessEnabled(
          OrtModelCompilationOptionsPtr modelCompileOptions,
          bool useWeightless) =>
      unsupportedOnWeb('ModelCompilationOptions_SetWeightlessEnabled', _why);

  @override
  @NativeOnly(_why)
  List<String> modelMetadataGetCustomMetadataMapKeys(
          OrtModelMetadataPtr modelMetadata, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('ModelMetadataGetCustomMetadataMapKeys', _why);

  @override
  @NativeOnly(_why)
  String modelMetadataGetDescription(
          OrtModelMetadataPtr modelMetadata, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('ModelMetadataGetDescription', _why);

  @override
  @NativeOnly(_why)
  String modelMetadataGetDomain(
          OrtModelMetadataPtr modelMetadata, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('ModelMetadataGetDomain', _why);

  @override
  @NativeOnly(_why)
  String modelMetadataGetGraphDescription(
          OrtModelMetadataPtr modelMetadata, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('ModelMetadataGetGraphDescription', _why);

  @override
  @NativeOnly(_why)
  String modelMetadataGetGraphName(
          OrtModelMetadataPtr modelMetadata, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('ModelMetadataGetGraphName', _why);

  @override
  @NativeOnly(_why)
  String modelMetadataGetProducerName(
          OrtModelMetadataPtr modelMetadata, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('ModelMetadataGetProducerName', _why);

  @override
  @NativeOnly(_why)
  int modelMetadataGetVersion(OrtModelMetadataPtr modelMetadata) =>
      unsupportedOnWeb('ModelMetadataGetVersion', _why);

  @override
  @NativeOnly(_why)
  String modelMetadataLookupCustomMetadataMap(OrtModelMetadataPtr modelMetadata,
          OrtAllocatorPtr allocator, String key) =>
      unsupportedOnWeb('ModelMetadataLookupCustomMetadataMap', _why);

  @override
  @NativeOnly(_why)
  OrtOpAttrPtr node_GetAttributeByName(OrtNodePtr node, String attributeName) =>
      unsupportedOnWeb('Node_GetAttributeByName', _why);

  @override
  @NativeOnly(_why)
  List<OrtOpAttrPtr> node_GetAttributes(OrtNodePtr node, int numAttributes) =>
      unsupportedOnWeb('Node_GetAttributes', _why);

  @override
  @NativeOnly(_why)
  String node_GetDomain(OrtNodePtr node) =>
      unsupportedOnWeb('Node_GetDomain', _why);

  @override
  @NativeOnly(_why)
  String node_GetEpName(OrtNodePtr node) =>
      unsupportedOnWeb('Node_GetEpName', _why);

  @override
  @NativeOnly(_why)
  OrtGraphPtr node_GetGraph(OrtNodePtr node) =>
      unsupportedOnWeb('Node_GetGraph', _why);

  @override
  @NativeOnly(_why)
  int node_GetId(OrtNodePtr node) => unsupportedOnWeb('Node_GetId', _why);

  @override
  @NativeOnly(_why)
  List<OrtValueInfoPtr> node_GetImplicitInputs(
          OrtNodePtr node, int numImplicitInputs) =>
      unsupportedOnWeb('Node_GetImplicitInputs', _why);

  @override
  @NativeOnly(_why)
  List<OrtValueInfoPtr> node_GetInputs(OrtNodePtr node, int numInputs) =>
      unsupportedOnWeb('Node_GetInputs', _why);

  @override
  @NativeOnly(_why)
  String node_GetName(OrtNodePtr node) =>
      unsupportedOnWeb('Node_GetName', _why);

  @override
  @NativeOnly(_why)
  int node_GetNumAttributes(OrtNodePtr node) =>
      unsupportedOnWeb('Node_GetNumAttributes', _why);

  @override
  @NativeOnly(_why)
  int node_GetNumImplicitInputs(OrtNodePtr node) =>
      unsupportedOnWeb('Node_GetNumImplicitInputs', _why);

  @override
  @NativeOnly(_why)
  int node_GetNumInputs(OrtNodePtr node) =>
      unsupportedOnWeb('Node_GetNumInputs', _why);

  @override
  @NativeOnly(_why)
  int node_GetNumOutputs(OrtNodePtr node) =>
      unsupportedOnWeb('Node_GetNumOutputs', _why);

  @override
  @NativeOnly(_why)
  int node_GetNumSubgraphs(OrtNodePtr node) =>
      unsupportedOnWeb('Node_GetNumSubgraphs', _why);

  @override
  @NativeOnly(_why)
  String node_GetOperatorType(OrtNodePtr node) =>
      unsupportedOnWeb('Node_GetOperatorType', _why);

  @override
  @NativeOnly(_why)
  List<OrtValueInfoPtr> node_GetOutputs(OrtNodePtr node, int numOutputs) =>
      unsupportedOnWeb('Node_GetOutputs', _why);

  @override
  @NativeOnly(_why)
  int node_GetSinceVersion(OrtNodePtr node) =>
      unsupportedOnWeb('Node_GetSinceVersion', _why);

  @override
  @NativeOnly(_why)
  (List<OrtGraphPtr> subgraphs, List<String> attributeNames) node_GetSubgraphs(
          OrtNodePtr node, int numSubgraphs) =>
      unsupportedOnWeb('Node_GetSubgraphs', _why);

  @override
  @NativeOnly(_why)
  String opAttr_GetName(OrtOpAttrPtr attribute) =>
      unsupportedOnWeb('OpAttr_GetName', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr opAttr_GetTensorAttributeAsOrtValue(OrtOpAttrPtr attribute) =>
      unsupportedOnWeb('OpAttr_GetTensorAttributeAsOrtValue', _why);

  @override
  @NativeOnly(_why)
  int opAttr_GetType(OrtOpAttrPtr attribute) =>
      unsupportedOnWeb('OpAttr_GetType', _why);

  @override
  @NativeOnly(_why)
  void optimizerStep(OrtTrainingSessionPtr sess, OrtRunOptionsPtr runOptions) =>
      unsupportedOnWeb('OptimizerStep', _why);

  @override
  @NativeOnly(_why)
  int readOpAttr(OrtOpAttrPtr opAttr, int type, OrtPtr data, int len) =>
      unsupportedOnWeb('ReadOpAttr', _why);

  @override
  @NativeOnly(_why)
  void registerAllocator(OrtEnvPtr env, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('RegisterAllocator', _why);

  @override
  @NativeOnly(_why)
  OrtPtr registerCustomOpsLibrary(
          OrtSessionOptionsPtr options, String libraryPath) =>
      unsupportedOnWeb('RegisterCustomOpsLibrary', _why);

  @override
  @NativeOnly(_why)
  void registerCustomOpsLibrary_V2(
          OrtSessionOptionsPtr options, String libraryName) =>
      unsupportedOnWeb('RegisterCustomOpsLibrary_V2', _why);

  @override
  @NativeOnly(_why)
  void registerCustomOpsUsingFunction(
          OrtSessionOptionsPtr options, String registrationFuncName) =>
      unsupportedOnWeb('RegisterCustomOpsUsingFunction', _why);

  @override
  @NativeOnly(_why)
  void registerExecutionProviderLibrary(
          OrtEnvPtr env, String registrationName, String path) =>
      unsupportedOnWeb('RegisterExecutionProviderLibrary', _why);

  @override
  @NativeOnly(_why)
  void registerLinearLRScheduler(OrtTrainingSessionPtr sess,
          int warmupStepCount, int totalStepCount, double initialLr) =>
      unsupportedOnWeb('RegisterLinearLRScheduler', _why);

  @override
  @NativeOnly(_why)
  void releaseAllocator(OrtAllocatorPtr input) =>
      unsupportedOnWeb('ReleaseAllocator', _why);

  @override
  @NativeOnly(_why)
  void releaseArenaCfg(OrtArenaCfgPtr input) =>
      unsupportedOnWeb('ReleaseArenaCfg', _why);

  @override
  @NativeOnly(_why)
  void releaseCANNProviderOptions(OrtCANNProviderOptionsPtr input) =>
      unsupportedOnWeb('ReleaseCANNProviderOptions', _why);

  @override
  @NativeOnly(_why)
  void releaseCUDAProviderOptions(OrtCUDAProviderOptionsV2Ptr input) =>
      unsupportedOnWeb('ReleaseCUDAProviderOptions', _why);

  @override
  @NativeOnly(_why)
  void releaseCheckpointState(OrtCheckpointStatePtr input) =>
      unsupportedOnWeb('ReleaseCheckpointState', _why);

  @override
  @NativeOnly(_why)
  void releaseCustomOpDomain(OrtCustomOpDomainPtr input) =>
      unsupportedOnWeb('ReleaseCustomOpDomain', _why);

  @override
  @NativeOnly(_why)
  void releaseDeviceEpIncompatibilityDetails(
          OrtDeviceEpIncompatibilityDetailsPtr input) =>
      unsupportedOnWeb('ReleaseDeviceEpIncompatibilityDetails', _why);

  @override
  @NativeOnly(_why)
  void releaseDnnlProviderOptions(OrtDnnlProviderOptionsPtr input) =>
      unsupportedOnWeb('ReleaseDnnlProviderOptions', _why);

  @override
  @NativeOnly(_why)
  void releaseEnv(OrtEnvPtr input) => unsupportedOnWeb('ReleaseEnv', _why);

  @override
  @NativeOnly(_why)
  void releaseExternalInitializerInfo(OrtExternalInitializerInfoPtr input) =>
      unsupportedOnWeb('ReleaseExternalInitializerInfo', _why);

  @override
  @NativeOnly(_why)
  void releaseExternalMemoryHandle(OrtExternalMemoryHandlePtr input) =>
      unsupportedOnWeb('ReleaseExternalMemoryHandle', _why);

  @override
  @NativeOnly(_why)
  void releaseExternalResourceImporter(OrtExternalResourceImporterPtr input) =>
      unsupportedOnWeb('ReleaseExternalResourceImporter', _why);

  @override
  @NativeOnly(_why)
  void releaseExternalSemaphoreHandle(OrtExternalSemaphoreHandlePtr input) =>
      unsupportedOnWeb('ReleaseExternalSemaphoreHandle', _why);

  @override
  @NativeOnly(_why)
  void releaseGraph(OrtGraphPtr input) =>
      unsupportedOnWeb('ReleaseGraph', _why);

  @override
  @NativeOnly(_why)
  void releaseIoBinding(OrtIoBindingPtr input) =>
      unsupportedOnWeb('ReleaseIoBinding', _why);

  @override
  @NativeOnly(_why)
  void releaseKernelInfo(OrtKernelInfoPtr input) =>
      unsupportedOnWeb('ReleaseKernelInfo', _why);

  @override
  @NativeOnly(_why)
  void releaseKeyValuePairs(OrtKeyValuePairsPtr input) =>
      unsupportedOnWeb('ReleaseKeyValuePairs', _why);

  @override
  @NativeOnly(_why)
  void releaseLoraAdapter(OrtLoraAdapterPtr input) =>
      unsupportedOnWeb('ReleaseLoraAdapter', _why);

  @override
  @NativeOnly(_why)
  void releaseMapTypeInfo(OrtMapTypeInfoPtr input) =>
      unsupportedOnWeb('ReleaseMapTypeInfo', _why);

  @override
  @NativeOnly(_why)
  void releaseMemoryInfo(OrtMemoryInfoPtr input) =>
      unsupportedOnWeb('ReleaseMemoryInfo', _why);

  @override
  @NativeOnly(_why)
  void releaseModel(OrtModelPtr input) =>
      unsupportedOnWeb('ReleaseModel', _why);

  @override
  @NativeOnly(_why)
  void releaseModelCompilationOptions(OrtModelCompilationOptionsPtr input) =>
      unsupportedOnWeb('ReleaseModelCompilationOptions', _why);

  @override
  @NativeOnly(_why)
  void releaseModelMetadata(OrtModelMetadataPtr input) =>
      unsupportedOnWeb('ReleaseModelMetadata', _why);

  @override
  @NativeOnly(_why)
  void releaseNode(OrtNodePtr input) => unsupportedOnWeb('ReleaseNode', _why);

  @override
  @NativeOnly(_why)
  void releaseOp(OrtOpPtr input) => unsupportedOnWeb('ReleaseOp', _why);

  @override
  @NativeOnly(_why)
  void releaseOpAttr(OrtOpAttrPtr input) =>
      unsupportedOnWeb('ReleaseOpAttr', _why);

  @override
  @NativeOnly(_why)
  void releasePrepackedWeightsContainer(
          OrtPrepackedWeightsContainerPtr input) =>
      unsupportedOnWeb('ReleasePrepackedWeightsContainer', _why);

  @override
  @NativeOnly(_why)
  void releaseROCMProviderOptions(OrtROCMProviderOptionsPtr input) =>
      unsupportedOnWeb('ReleaseROCMProviderOptions', _why);

  @override
  @NativeOnly(_why)
  void releaseSequenceTypeInfo(OrtSequenceTypeInfoPtr input) =>
      unsupportedOnWeb('ReleaseSequenceTypeInfo', _why);

  @override
  @NativeOnly(_why)
  void releaseSharedAllocator(
          OrtEnvPtr env, OrtEpDevicePtr epDevice, int memType) =>
      unsupportedOnWeb('ReleaseSharedAllocator', _why);

  @override
  @NativeOnly(_why)
  void releaseSyncStream(OrtSyncStreamPtr input) =>
      unsupportedOnWeb('ReleaseSyncStream', _why);

  @override
  @NativeOnly(_why)
  void releaseTensorRTProviderOptions(OrtTensorRTProviderOptionsV2Ptr input) =>
      unsupportedOnWeb('ReleaseTensorRTProviderOptions', _why);

  @override
  @NativeOnly(_why)
  void releaseTensorTypeAndShapeInfo(OrtTensorTypeAndShapeInfoPtr input) =>
      unsupportedOnWeb('ReleaseTensorTypeAndShapeInfo', _why);

  @override
  @NativeOnly(_why)
  void releaseThreadingOptions(OrtThreadingOptionsPtr input) =>
      unsupportedOnWeb('ReleaseThreadingOptions', _why);

  @override
  @NativeOnly(_why)
  void releaseTrainingSession(OrtTrainingSessionPtr input) =>
      unsupportedOnWeb('ReleaseTrainingSession', _why);

  @override
  @NativeOnly(_why)
  void releaseTypeInfo(OrtTypeInfoPtr input) =>
      unsupportedOnWeb('ReleaseTypeInfo', _why);

  @override
  @NativeOnly(_why)
  void releaseValue(OrtValuePtr input) =>
      unsupportedOnWeb('ReleaseValue', _why);

  @override
  @NativeOnly(_why)
  void releaseValueInfo(OrtValueInfoPtr input) =>
      unsupportedOnWeb('ReleaseValueInfo', _why);

  @override
  @NativeOnly(_why)
  void removeKeyValuePair(OrtKeyValuePairsPtr kvps, String key) =>
      unsupportedOnWeb('RemoveKeyValuePair', _why);

  @override
  @NativeOnly(_why)
  void runOptionsAddActiveLoraAdapter(
          OrtRunOptionsPtr options, OrtLoraAdapterPtr adapter) =>
      unsupportedOnWeb('RunOptionsAddActiveLoraAdapter', _why);

  @override
  @NativeOnly(_why)
  void runOptionsDisableProfiling(OrtRunOptionsPtr options) =>
      unsupportedOnWeb('RunOptionsDisableProfiling', _why);

  @override
  @NativeOnly(_why)
  void runOptionsEnableProfiling(
          OrtRunOptionsPtr options, String profileFilePrefix) =>
      unsupportedOnWeb('RunOptionsEnableProfiling', _why);

  @override
  @NativeOnly(_why)
  int runOptionsGetRunLogSeverityLevel(OrtRunOptionsPtr options) =>
      unsupportedOnWeb('RunOptionsGetRunLogSeverityLevel', _why);

  @override
  @NativeOnly(_why)
  int runOptionsGetRunLogVerbosityLevel(OrtRunOptionsPtr options) =>
      unsupportedOnWeb('RunOptionsGetRunLogVerbosityLevel', _why);

  @override
  @NativeOnly(_why)
  String runOptionsGetRunTag(OrtRunOptionsPtr options) =>
      unsupportedOnWeb('RunOptionsGetRunTag', _why);

  @override
  @NativeOnly(_why)
  void runOptionsSetRunLogSeverityLevel(
          OrtRunOptionsPtr options, int logSeverityLevel) =>
      unsupportedOnWeb('RunOptionsSetRunLogSeverityLevel', _why);

  @override
  @NativeOnly(_why)
  void runOptionsSetRunLogVerbosityLevel(
          OrtRunOptionsPtr options, int logVerbosityLevel) =>
      unsupportedOnWeb('RunOptionsSetRunLogVerbosityLevel', _why);

  @override
  @NativeOnly(_why)
  void runOptionsSetRunTag(OrtRunOptionsPtr options, String runTag) =>
      unsupportedOnWeb('RunOptionsSetRunTag', _why);

  @override
  @NativeOnly(_why)
  void runOptionsSetTerminate(OrtRunOptionsPtr options) =>
      unsupportedOnWeb('RunOptionsSetTerminate', _why);

  @override
  @NativeOnly(_why)
  void runOptionsUnsetTerminate(OrtRunOptionsPtr options) =>
      unsupportedOnWeb('RunOptionsUnsetTerminate', _why);

  @override
  @NativeOnly(_why)
  void saveCheckpoint(OrtCheckpointStatePtr checkpointState,
          String checkpointPath, bool includeOptimizerState) =>
      unsupportedOnWeb('SaveCheckpoint', _why);

  @override
  @NativeOnly(_why)
  void schedulerStep(OrtTrainingSessionPtr sess) =>
      unsupportedOnWeb('SchedulerStep', _why);

  @override
  @NativeOnly(_why)
  String sessionEndProfiling(
          OrtSessionPtr session, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('SessionEndProfiling', _why);

  @override
  @NativeOnly(_why)
  List<OrtEpDevicePtr> sessionGetEpDeviceForInputs(
          OrtSessionPtr session, int numInputs) =>
      unsupportedOnWeb('SessionGetEpDeviceForInputs', _why);

  @override
  @NativeOnly(_why)
  List<OrtEpDevicePtr> sessionGetEpDeviceForOutputs(
          OrtSessionPtr session, int numOutputs) =>
      unsupportedOnWeb('SessionGetEpDeviceForOutputs', _why);

  @override
  @NativeOnly(_why)
  int sessionGetInputCount(OrtSessionPtr session) =>
      unsupportedOnWeb('SessionGetInputCount', _why);

  @override
  @NativeOnly(_why)
  String sessionGetInputName(
          OrtSessionPtr session, int index, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('SessionGetInputName', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr sessionGetInputTypeInfo(OrtSessionPtr session, int index) =>
      unsupportedOnWeb('SessionGetInputTypeInfo', _why);

  @override
  @NativeOnly(_why)
  List<OrtMemoryInfoPtr> sessionGetMemoryInfoForInputs(
          OrtSessionPtr session, int numInputs) =>
      unsupportedOnWeb('SessionGetMemoryInfoForInputs', _why);

  @override
  @NativeOnly(_why)
  List<OrtMemoryInfoPtr> sessionGetMemoryInfoForOutputs(
          OrtSessionPtr session, int numOutputs) =>
      unsupportedOnWeb('SessionGetMemoryInfoForOutputs', _why);

  @override
  @NativeOnly(_why)
  OrtModelMetadataPtr sessionGetModelMetadata(OrtSessionPtr session) =>
      unsupportedOnWeb('SessionGetModelMetadata', _why);

  @override
  @NativeOnly(_why)
  int sessionGetOpsetForDomain(OrtSessionPtr session, String domain) =>
      unsupportedOnWeb('SessionGetOpsetForDomain', _why);

  @override
  @NativeOnly(_why)
  int sessionGetOutputCount(OrtSessionPtr session) =>
      unsupportedOnWeb('SessionGetOutputCount', _why);

  @override
  @NativeOnly(_why)
  String sessionGetOutputName(
          OrtSessionPtr session, int index, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('SessionGetOutputName', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr sessionGetOutputTypeInfo(OrtSessionPtr session, int index) =>
      unsupportedOnWeb('SessionGetOutputTypeInfo', _why);

  @override
  @NativeOnly(_why)
  int sessionGetOverridableInitializerCount(OrtSessionPtr session) =>
      unsupportedOnWeb('SessionGetOverridableInitializerCount', _why);

  @override
  @NativeOnly(_why)
  String sessionGetOverridableInitializerName(
          OrtSessionPtr session, int index, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('SessionGetOverridableInitializerName', _why);

  @override
  @NativeOnly(_why)
  OrtTypeInfoPtr sessionGetOverridableInitializerTypeInfo(
          OrtSessionPtr session, int index) =>
      unsupportedOnWeb('SessionGetOverridableInitializerTypeInfo', _why);

  @override
  @NativeOnly(_why)
  int sessionGetProfilingStartTimeNs(OrtSessionPtr session) =>
      unsupportedOnWeb('SessionGetProfilingStartTimeNs', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsAppendExecutionProvider(
          OrtSessionOptionsPtr options,
          String providerName,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      unsupportedOnWeb('SessionOptionsAppendExecutionProvider', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsAppendExecutionProvider_CANN(OrtSessionOptionsPtr options,
          OrtCANNProviderOptionsPtr cannOptions) =>
      unsupportedOnWeb('SessionOptionsAppendExecutionProvider_CANN', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsAppendExecutionProvider_CUDA(OrtSessionOptionsPtr options,
          OrtCUDAProviderOptionsPtr cudaOptions) =>
      unsupportedOnWeb('SessionOptionsAppendExecutionProvider_CUDA', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsAppendExecutionProvider_CUDA_V2(
          OrtSessionOptionsPtr options,
          OrtCUDAProviderOptionsV2Ptr cudaOptions) =>
      unsupportedOnWeb('SessionOptionsAppendExecutionProvider_CUDA_V2', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsAppendExecutionProvider_Dnnl(OrtSessionOptionsPtr options,
          OrtDnnlProviderOptionsPtr dnnlOptions) =>
      unsupportedOnWeb('SessionOptionsAppendExecutionProvider_Dnnl', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsAppendExecutionProvider_MIGraphX(
          OrtSessionOptionsPtr options,
          OrtMIGraphXProviderOptionsPtr migraphxOptions) =>
      unsupportedOnWeb('SessionOptionsAppendExecutionProvider_MIGraphX', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsAppendExecutionProvider_OpenVINO(
          OrtSessionOptionsPtr options,
          OrtOpenVINOProviderOptionsPtr providerOptions) =>
      unsupportedOnWeb('SessionOptionsAppendExecutionProvider_OpenVINO', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsAppendExecutionProvider_OpenVINO_V2(
          OrtSessionOptionsPtr options,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      unsupportedOnWeb(
          'SessionOptionsAppendExecutionProvider_OpenVINO_V2', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsAppendExecutionProvider_ROCM(OrtSessionOptionsPtr options,
          OrtROCMProviderOptionsPtr rocmOptions) =>
      unsupportedOnWeb('SessionOptionsAppendExecutionProvider_ROCM', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsAppendExecutionProvider_TensorRT(
          OrtSessionOptionsPtr options,
          OrtTensorRTProviderOptionsPtr tensorrtOptions) =>
      unsupportedOnWeb('SessionOptionsAppendExecutionProvider_TensorRT', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsAppendExecutionProvider_TensorRT_V2(
          OrtSessionOptionsPtr options,
          OrtTensorRTProviderOptionsV2Ptr tensorrtOptions) =>
      unsupportedOnWeb(
          'SessionOptionsAppendExecutionProvider_TensorRT_V2', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsAppendExecutionProvider_V2(
          OrtSessionOptionsPtr sessionOptions,
          OrtEnvPtr env,
          List<OrtEpDevicePtr> epDevices,
          int numEpDevices,
          List<String> epOptionKeys,
          List<String> epOptionVals,
          int numEpOptions) =>
      unsupportedOnWeb('SessionOptionsAppendExecutionProvider_V2', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsAppendExecutionProvider_VitisAI(
          OrtSessionOptionsPtr options,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      unsupportedOnWeb('SessionOptionsAppendExecutionProvider_VitisAI', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsSetCustomCreateThreadFn(
          OrtSessionOptionsPtr options, OrtPtr ortCustomCreateThreadFn) =>
      unsupportedOnWeb('SessionOptionsSetCustomCreateThreadFn', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsSetCustomJoinThreadFn(
          OrtSessionOptionsPtr options, OrtPtr ortCustomJoinThreadFn) =>
      unsupportedOnWeb('SessionOptionsSetCustomJoinThreadFn', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsSetCustomThreadCreationOptions(
          OrtSessionOptionsPtr options,
          OrtPtr ortCustomThreadCreationOptions) =>
      unsupportedOnWeb('SessionOptionsSetCustomThreadCreationOptions', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsSetEpSelectionPolicy(
          OrtSessionOptionsPtr sessionOptions, int policy) =>
      unsupportedOnWeb('SessionOptionsSetEpSelectionPolicy', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsSetEpSelectionPolicyDelegate(
          OrtSessionOptionsPtr sessionOptions,
          OrtPtr delegate,
          OrtPtr delegateState) =>
      unsupportedOnWeb('SessionOptionsSetEpSelectionPolicyDelegate', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsSetLoadCancellationFlag(
          OrtSessionOptionsPtr options, bool cancel) =>
      unsupportedOnWeb('SessionOptionsSetLoadCancellationFlag', _why);

  @override
  @NativeOnly(_why)
  void sessionOptionsSetWeightlessSourceModelBuffer(
          OrtSessionOptionsPtr options,
          OrtPtr sourceModelData,
          int sourceModelDataLength) =>
      unsupportedOnWeb('SessionOptionsSetWeightlessSourceModelBuffer', _why);

  @override
  @NativeOnly(_why)
  void sessionReleaseCapturedGraph(
          OrtSessionPtr session, int graphAnnotationId) =>
      unsupportedOnWeb('SessionReleaseCapturedGraph', _why);

  @override
  @NativeOnly(_why)
  List<OrtEpAssignedSubgraphPtr> session_GetEpGraphAssignmentInfo(
          OrtSessionPtr session) =>
      unsupportedOnWeb('Session_GetEpGraphAssignmentInfo', _why);

  @override
  @NativeOnly(_why)
  void setCurrentGpuDeviceId(int deviceId) =>
      unsupportedOnWeb('SetCurrentGpuDeviceId', _why);

  @override
  @NativeOnly(_why)
  void setDimensions(OrtTensorTypeAndShapeInfoPtr info, List<int> dimValues,
          int dimCount) =>
      unsupportedOnWeb('SetDimensions', _why);

  @override
  @NativeOnly(_why)
  void setEpDynamicOptions(OrtSessionPtr sess, List<String> keys,
          List<String> values, int kvLen) =>
      unsupportedOnWeb('SetEpDynamicOptions', _why);

  @override
  @NativeOnly(_why)
  void setGlobalCustomCreateThreadFn(
          OrtThreadingOptionsPtr tpOptions, OrtPtr ortCustomCreateThreadFn) =>
      unsupportedOnWeb('SetGlobalCustomCreateThreadFn', _why);

  @override
  @NativeOnly(_why)
  void setGlobalCustomJoinThreadFn(
          OrtThreadingOptionsPtr tpOptions, OrtPtr ortCustomJoinThreadFn) =>
      unsupportedOnWeb('SetGlobalCustomJoinThreadFn', _why);

  @override
  @NativeOnly(_why)
  void setGlobalCustomThreadCreationOptions(OrtThreadingOptionsPtr tpOptions,
          OrtPtr ortCustomThreadCreationOptions) =>
      unsupportedOnWeb('SetGlobalCustomThreadCreationOptions', _why);

  @override
  @NativeOnly(_why)
  void setGlobalDenormalAsZero(OrtThreadingOptionsPtr tpOptions) =>
      unsupportedOnWeb('SetGlobalDenormalAsZero', _why);

  @override
  @NativeOnly(_why)
  void setGlobalInterOpNumThreads(
          OrtThreadingOptionsPtr tpOptions, int interOpNumThreads) =>
      unsupportedOnWeb('SetGlobalInterOpNumThreads', _why);

  @override
  @NativeOnly(_why)
  void setGlobalIntraOpNumThreads(
          OrtThreadingOptionsPtr tpOptions, int intraOpNumThreads) =>
      unsupportedOnWeb('SetGlobalIntraOpNumThreads', _why);

  @override
  @NativeOnly(_why)
  void setGlobalIntraOpThreadAffinity(
          OrtThreadingOptionsPtr tpOptions, String affinityString) =>
      unsupportedOnWeb('SetGlobalIntraOpThreadAffinity', _why);

  @override
  @NativeOnly(_why)
  void setGlobalSpinControl(
          OrtThreadingOptionsPtr tpOptions, int allowSpinning) =>
      unsupportedOnWeb('SetGlobalSpinControl', _why);

  @override
  @NativeOnly(_why)
  void setGraphInputs(
          OrtGraphPtr graph, List<OrtValueInfoPtr> inputs, int inputsLen) =>
      unsupportedOnWeb('SetGraphInputs', _why);

  @override
  @NativeOnly(_why)
  void setGraphOutputs(
          OrtGraphPtr graph, List<OrtValueInfoPtr> outputs, int outputsLen) =>
      unsupportedOnWeb('SetGraphOutputs', _why);

  @override
  @NativeOnly(_why)
  void setLanguageProjection(OrtEnvPtr ortEnv, int projection) =>
      unsupportedOnWeb('SetLanguageProjection', _why);

  @override
  @NativeOnly(_why)
  void setLearningRate(OrtTrainingSessionPtr sess, double learningRate) =>
      unsupportedOnWeb('SetLearningRate', _why);

  @override
  @NativeOnly(_why)
  void setOptimizedModelFilePath(
          OrtSessionOptionsPtr options, String optimizedModelFilepath) =>
      unsupportedOnWeb('SetOptimizedModelFilePath', _why);

  @override
  @NativeOnly(_why)
  void setPerSessionThreadPoolCallbacks(
          OrtEnvPtr env, OrtThreadPoolCallbacksConfigPtr config) =>
      unsupportedOnWeb('SetPerSessionThreadPoolCallbacks', _why);

  @override
  @NativeOnly(_why)
  void setSeed(int seed) => unsupportedOnWeb('SetSeed', _why);

  @override
  @NativeOnly(_why)
  void setSessionExecutionMode(
          OrtSessionOptionsPtr options, int executionMode) =>
      unsupportedOnWeb('SetSessionExecutionMode', _why);

  @override
  @NativeOnly(_why)
  void setSessionGraphOptimizationLevel(
          OrtSessionOptionsPtr options, int graphOptimizationLevel) =>
      unsupportedOnWeb('SetSessionGraphOptimizationLevel', _why);

  @override
  @NativeOnly(_why)
  void setSessionLogId(OrtSessionOptionsPtr options, String logid) =>
      unsupportedOnWeb('SetSessionLogId', _why);

  @override
  @NativeOnly(_why)
  void setSessionLogSeverityLevel(
          OrtSessionOptionsPtr options, int sessionLogSeverityLevel) =>
      unsupportedOnWeb('SetSessionLogSeverityLevel', _why);

  @override
  @NativeOnly(_why)
  void setSessionLogVerbosityLevel(
          OrtSessionOptionsPtr options, int sessionLogVerbosityLevel) =>
      unsupportedOnWeb('SetSessionLogVerbosityLevel', _why);

  @override
  @NativeOnly(_why)
  void setTensorElementType(OrtTensorTypeAndShapeInfoPtr info, int type) =>
      unsupportedOnWeb('SetTensorElementType', _why);

  @override
  @NativeOnly(_why)
  void setUserLoggingFunction(OrtSessionOptionsPtr options,
          OrtPtr userLoggingFunction, OrtPtr userLoggingParam) =>
      unsupportedOnWeb('SetUserLoggingFunction', _why);

  @override
  @NativeOnly(_why)
  OrtOpAttrPtr shapeInferContext_GetAttribute(
          OrtShapeInferContextPtr context, String attrName) =>
      unsupportedOnWeb('ShapeInferContext_GetAttribute', _why);

  @override
  @NativeOnly(_why)
  int shapeInferContext_GetInputCount(OrtShapeInferContextPtr context) =>
      unsupportedOnWeb('ShapeInferContext_GetInputCount', _why);

  @override
  @NativeOnly(_why)
  OrtTensorTypeAndShapeInfoPtr shapeInferContext_GetInputTypeShape(
          OrtShapeInferContextPtr context, int index) =>
      unsupportedOnWeb('ShapeInferContext_GetInputTypeShape', _why);

  @override
  @NativeOnly(_why)
  void shapeInferContext_SetOutputTypeShape(OrtShapeInferContextPtr context,
          int index, OrtTensorTypeAndShapeInfoPtr info) =>
      unsupportedOnWeb('ShapeInferContext_SetOutputTypeShape', _why);

  @override
  @NativeOnly(_why)
  void signalSemaphore(
          OrtExternalResourceImporterPtr importer,
          OrtExternalSemaphoreHandlePtr semaphoreHandle,
          OrtSyncStreamPtr stream,
          int value) =>
      unsupportedOnWeb('SignalSemaphore', _why);

  @override
  @NativeOnly(_why)
  void synchronizeBoundInputs(OrtIoBindingPtr bindingPtr) =>
      unsupportedOnWeb('SynchronizeBoundInputs', _why);

  @override
  @NativeOnly(_why)
  void synchronizeBoundOutputs(OrtIoBindingPtr bindingPtr) =>
      unsupportedOnWeb('SynchronizeBoundOutputs', _why);

  @override
  @NativeOnly(_why)
  OrtPtr tensorAt(OrtValuePtr value, List<int> locationValues,
          int locationValuesCount) =>
      unsupportedOnWeb('TensorAt', _why);

  @override
  @NativeOnly(_why)
  void trainStep(
          OrtTrainingSessionPtr sess,
          OrtRunOptionsPtr runOptions,
          int inputsLen,
          List<OrtValuePtr> inputs,
          int outputsLen,
          List<OrtValuePtr> outputs) =>
      unsupportedOnWeb('TrainStep', _why);

  @override
  @NativeOnly(_why)
  int trainingSessionGetEvalModelInputCount(OrtTrainingSessionPtr sess) =>
      unsupportedOnWeb('TrainingSessionGetEvalModelInputCount', _why);

  @override
  @NativeOnly(_why)
  String trainingSessionGetEvalModelInputName(
          OrtTrainingSessionPtr sess, int index, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('TrainingSessionGetEvalModelInputName', _why);

  @override
  @NativeOnly(_why)
  int trainingSessionGetEvalModelOutputCount(OrtTrainingSessionPtr sess) =>
      unsupportedOnWeb('TrainingSessionGetEvalModelOutputCount', _why);

  @override
  @NativeOnly(_why)
  String trainingSessionGetEvalModelOutputName(
          OrtTrainingSessionPtr sess, int index, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('TrainingSessionGetEvalModelOutputName', _why);

  @override
  @NativeOnly(_why)
  int trainingSessionGetTrainingModelInputCount(OrtTrainingSessionPtr sess) =>
      unsupportedOnWeb('TrainingSessionGetTrainingModelInputCount', _why);

  @override
  @NativeOnly(_why)
  String trainingSessionGetTrainingModelInputName(
          OrtTrainingSessionPtr sess, int index, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('TrainingSessionGetTrainingModelInputName', _why);

  @override
  @NativeOnly(_why)
  int trainingSessionGetTrainingModelOutputCount(OrtTrainingSessionPtr sess) =>
      unsupportedOnWeb('TrainingSessionGetTrainingModelOutputCount', _why);

  @override
  @NativeOnly(_why)
  String trainingSessionGetTrainingModelOutputName(
          OrtTrainingSessionPtr sess, int index, OrtAllocatorPtr allocator) =>
      unsupportedOnWeb('TrainingSessionGetTrainingModelOutputName', _why);

  @override
  @NativeOnly(_why)
  void unregisterAllocator(OrtEnvPtr env, OrtMemoryInfoPtr memInfo) =>
      unsupportedOnWeb('UnregisterAllocator', _why);

  @override
  @NativeOnly(_why)
  void unregisterExecutionProviderLibrary(
          OrtEnvPtr env, String registrationName) =>
      unsupportedOnWeb('UnregisterExecutionProviderLibrary', _why);

  @override
  @NativeOnly(_why)
  void updateCANNProviderOptions(
          OrtCANNProviderOptionsPtr cannOptions,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      unsupportedOnWeb('UpdateCANNProviderOptions', _why);

  @override
  @NativeOnly(_why)
  void updateCUDAProviderOptions(
          OrtCUDAProviderOptionsV2Ptr cudaOptions,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      unsupportedOnWeb('UpdateCUDAProviderOptions', _why);

  @override
  @NativeOnly(_why)
  void updateCUDAProviderOptionsWithValue(
          OrtCUDAProviderOptionsV2Ptr cudaOptions, String key, OrtPtr value) =>
      unsupportedOnWeb('UpdateCUDAProviderOptionsWithValue', _why);

  @override
  @NativeOnly(_why)
  void updateDnnlProviderOptions(
          OrtDnnlProviderOptionsPtr dnnlOptions,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      unsupportedOnWeb('UpdateDnnlProviderOptions', _why);

  @override
  @NativeOnly(_why)
  void updateEnvWithCustomLogLevel(OrtEnvPtr ortEnv, int logSeverityLevel) =>
      unsupportedOnWeb('UpdateEnvWithCustomLogLevel', _why);

  @override
  @NativeOnly(_why)
  void updateParameter(OrtCheckpointStatePtr checkpointState,
          String parameterName, OrtValuePtr parameter) =>
      unsupportedOnWeb('UpdateParameter', _why);

  @override
  @NativeOnly(_why)
  void updateROCMProviderOptions(
          OrtROCMProviderOptionsPtr rocmOptions,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      unsupportedOnWeb('UpdateROCMProviderOptions', _why);

  @override
  @NativeOnly(_why)
  void updateTensorRTProviderOptions(
          OrtTensorRTProviderOptionsV2Ptr tensorrtOptions,
          List<String> providerOptionsKeys,
          List<String> providerOptionsValues,
          int numKeys) =>
      unsupportedOnWeb('UpdateTensorRTProviderOptions', _why);

  @override
  @NativeOnly(_why)
  void updateTensorRTProviderOptionsWithValue(
          OrtTensorRTProviderOptionsV2Ptr tensorrtOptions,
          String key,
          OrtPtr value) =>
      unsupportedOnWeb('UpdateTensorRTProviderOptionsWithValue', _why);

  @override
  @NativeOnly(_why)
  OrtExternalInitializerInfoPtr valueInfo_GetExternalInitializerInfo(
          OrtValueInfoPtr valueInfo) =>
      unsupportedOnWeb('ValueInfo_GetExternalInitializerInfo', _why);

  @override
  @NativeOnly(_why)
  OrtValuePtr valueInfo_GetInitializerValue(OrtValueInfoPtr valueInfo) =>
      unsupportedOnWeb('ValueInfo_GetInitializerValue', _why);

  @override
  @NativeOnly(_why)
  (List<OrtNodePtr> nodes, List<int> inputIndices) valueInfo_GetValueConsumers(
          OrtValueInfoPtr valueInfo, int numConsumers) =>
      unsupportedOnWeb('ValueInfo_GetValueConsumers', _why);

  @override
  @NativeOnly(_why)
  int valueInfo_GetValueNumConsumers(OrtValueInfoPtr valueInfo) =>
      unsupportedOnWeb('ValueInfo_GetValueNumConsumers', _why);

  @override
  @NativeOnly(_why)
  List<OrtNodePtr> valueInfo_GetValueProducer(OrtValueInfoPtr valueInfo) =>
      unsupportedOnWeb('ValueInfo_GetValueProducer', _why);

  @override
  @NativeOnly(_why)
  bool valueInfo_IsConstantInitializer(OrtValueInfoPtr valueInfo) =>
      unsupportedOnWeb('ValueInfo_IsConstantInitializer', _why);

  @override
  @NativeOnly(_why)
  bool valueInfo_IsFromOuterScope(OrtValueInfoPtr valueInfo) =>
      unsupportedOnWeb('ValueInfo_IsFromOuterScope', _why);

  @override
  @NativeOnly(_why)
  bool valueInfo_IsGraphOutput(OrtValueInfoPtr valueInfo) =>
      unsupportedOnWeb('ValueInfo_IsGraphOutput', _why);

  @override
  @NativeOnly(_why)
  bool valueInfo_IsOptionalGraphInput(OrtValueInfoPtr valueInfo) =>
      unsupportedOnWeb('ValueInfo_IsOptionalGraphInput', _why);

  @override
  @NativeOnly(_why)
  bool valueInfo_IsRequiredGraphInput(OrtValueInfoPtr valueInfo) =>
      unsupportedOnWeb('ValueInfo_IsRequiredGraphInput', _why);

  @override
  @NativeOnly(_why)
  void waitSemaphore(
          OrtExternalResourceImporterPtr importer,
          OrtExternalSemaphoreHandlePtr semaphoreHandle,
          OrtSyncStreamPtr stream,
          int value) =>
      unsupportedOnWeb('WaitSemaphore', _why);
}
